//! `#[derive(SinexConfig)]` — generate `from_env()` for env-driven config structs.
//!
//! See the design at `thoughtspace/crystal/decisions/sinex-config-derive.md`
//! and `sinex-macros/docs/sinex_config.md` for the attribute grammar and the
//! field-type inference table.

use proc_macro::TokenStream;
use proc_macro2::TokenStream as TokenStream2;
use quote::quote;
use syn::{Data, DataStruct, DeriveInput, Expr, Fields, Lit, Meta, Type, parse_macro_input};

pub fn expand(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    match try_expand(&input) {
        Ok(ts) => ts.into(),
        Err(e) => e.to_compile_error().into(),
    }
}

fn try_expand(input: &DeriveInput) -> syn::Result<TokenStream2> {
    let StructAttrs { prefix, context } = parse_struct_attrs(input)?;

    let Data::Struct(DataStruct { fields: Fields::Named(fields), .. }) = &input.data else {
        return Err(syn::Error::new_spanned(
            input,
            "SinexConfig can only be derived on structs with named fields",
        ));
    };

    let mut field_inits = Vec::with_capacity(fields.named.len());
    for field in &fields.named {
        let name = field.ident.as_ref().expect("named field has identifier");
        let attrs = parse_field_attrs(field)?;
        if attrs.skip {
            field_inits.push(quote! { #name: ::std::default::Default::default() });
            continue;
        }

        let env_suffix = attrs
            .env
            .clone()
            .unwrap_or_else(|| field_name_to_env(&name.to_string()));
        let env_key = format!("{}_{}", prefix, env_suffix);
        let helper_call = infer_helper(&field.ty, &env_key, &context, &attrs)?;
        field_inits.push(quote! { #name: #helper_call });
    }

    let struct_ident = &input.ident;
    let (impl_generics, ty_generics, where_clause) = input.generics.split_for_impl();

    Ok(quote! {
        impl #impl_generics #struct_ident #ty_generics #where_clause {
            /// Load this config from environment variables.
            ///
            /// Generated by `#[derive(SinexConfig)]`. Each non-`skip` field
            /// reads from its env key (struct prefix + field-name suffix)
            /// using the appropriate `sinex_primitives::env::*` helper for
            /// its type. Parse failures and invalid UTF-8 produce `warn!`
            /// logs and the field's declared default.
            #[must_use]
            pub fn from_env() -> Self {
                Self {
                    #(#field_inits,)*
                }
            }
        }
    })
}

struct StructAttrs {
    prefix: String,
    context: String,
}

fn parse_struct_attrs(input: &DeriveInput) -> syn::Result<StructAttrs> {
    let mut prefix = None;
    let mut context = None;
    for attr in &input.attrs {
        if !attr.path().is_ident("sinex_config") {
            continue;
        }
        attr.parse_nested_meta(|meta| {
            if meta.path.is_ident("prefix") {
                prefix = Some(lit_string(&meta.value()?.parse::<Expr>()?)?);
            } else if meta.path.is_ident("context") {
                context = Some(lit_string(&meta.value()?.parse::<Expr>()?)?);
            } else {
                return Err(meta.error(
                    "unknown sinex_config struct attribute (expected `prefix`, `context`)",
                ));
            }
            Ok(())
        })?;
    }
    let prefix = prefix.ok_or_else(|| {
        syn::Error::new_spanned(
            input,
            "missing `#[sinex_config(prefix = \"SINEX_X\", context = \"...\")]` on struct",
        )
    })?;
    let context = context.ok_or_else(|| {
        syn::Error::new_spanned(
            input,
            "missing `#[sinex_config(... context = \"...\")]` on struct",
        )
    })?;
    Ok(StructAttrs { prefix, context })
}

#[derive(Default)]
struct FieldAttrs {
    env: Option<String>,
    default: Option<Expr>,
    parser: Option<syn::Path>,
    skip: bool,
}

fn parse_field_attrs(field: &syn::Field) -> syn::Result<FieldAttrs> {
    let mut attrs = FieldAttrs::default();
    for attr in &field.attrs {
        if !attr.path().is_ident("sinex_config") {
            continue;
        }
        if matches!(attr.meta, Meta::Path(_)) {
            // Bare `#[sinex_config]` — interpret as skip
            attrs.skip = true;
            continue;
        }
        attr.parse_nested_meta(|meta| {
            if meta.path.is_ident("skip") {
                attrs.skip = true;
            } else if meta.path.is_ident("env") {
                attrs.env = Some(lit_string(&meta.value()?.parse::<Expr>()?)?);
            } else if meta.path.is_ident("default") {
                attrs.default = Some(meta.value()?.parse::<Expr>()?);
            } else if meta.path.is_ident("default_expr") {
                // Accept a string literal containing a Rust expression so
                // callers can use non-literal defaults like
                // `default_expr = "Seconds::from_secs(30)"`.
                let raw = lit_string(&meta.value()?.parse::<Expr>()?)?;
                attrs.default = Some(syn::parse_str::<Expr>(&raw).map_err(|e| {
                    meta.error(format!("could not parse default_expr as a Rust expression: {e}"))
                })?);
            } else if meta.path.is_ident("parser") {
                attrs.parser = Some(meta.value()?.parse::<syn::Path>()?);
            } else {
                return Err(meta.error(
                    "unknown sinex_config field attribute (expected `env`, `default`, `default_expr`, `parser`, `skip`)",
                ));
            }
            Ok(())
        })?;
    }
    Ok(attrs)
}

fn infer_helper(
    ty: &Type,
    env_key: &str,
    context: &str,
    attrs: &FieldAttrs,
) -> syn::Result<TokenStream2> {
    // Custom parser short-circuits inference.
    if let Some(parser) = &attrs.parser {
        let default = attrs.default.as_ref().ok_or_else(|| {
            syn::Error::new_spanned(
                ty,
                "field with `parser` must also have `default` or `default_expr`",
            )
        })?;
        return Ok(quote! {
            ::sinex_primitives::env::var_optional(#env_key, #context)
                .and_then(|raw| #parser(&raw).ok())
                .unwrap_or_else(|| #default)
        });
    }

    let kind = classify(ty);
    match kind {
        TypeKind::Bool => {
            let default = attrs.default.clone().unwrap_or_else(|| {
                syn::parse_quote!(false)
            });
            Ok(quote! {
                ::sinex_primitives::env::bool_or(#env_key, #default, #context)
            })
        }
        TypeKind::String => {
            let default = attrs.default.clone().unwrap_or_else(|| {
                syn::parse_quote!("")
            });
            Ok(quote! {
                ::sinex_primitives::env::var_or(#env_key, #default, #context)
            })
        }
        TypeKind::OptionString => Ok(quote! {
            ::sinex_primitives::env::var_optional(#env_key, #context)
        }),
        TypeKind::OptionPathBuf => Ok(quote! {
            ::sinex_primitives::env::path_optional(#env_key, #context)
        }),
        TypeKind::OptionOther => Ok(quote! {
            ::sinex_primitives::env::parse_optional(#env_key, #context)
        }),
        TypeKind::PathBuf => {
            let default = attrs.default.as_ref().ok_or_else(|| {
                syn::Error::new_spanned(
                    ty,
                    "non-optional PathBuf field requires `default` or `default_expr`",
                )
            })?;
            Ok(quote! {
                ::sinex_primitives::env::path_optional(#env_key, #context).unwrap_or_else(|| #default)
            })
        }
        TypeKind::Other => {
            let default = attrs.default.as_ref().ok_or_else(|| {
                syn::Error::new_spanned(
                    ty,
                    "field requires `default`, `default_expr`, or `skip` attribute",
                )
            })?;
            Ok(quote! {
                ::sinex_primitives::env::parse_or(#env_key, #default, #context)
            })
        }
    }
}

enum TypeKind {
    Bool,
    String,
    OptionString,
    OptionPathBuf,
    OptionOther,
    PathBuf,
    Other,
}

fn classify(ty: &Type) -> TypeKind {
    let Type::Path(tp) = ty else {
        return TypeKind::Other;
    };
    let Some(last) = tp.path.segments.last() else {
        return TypeKind::Other;
    };
    let ident = last.ident.to_string();
    match ident.as_str() {
        "bool" => TypeKind::Bool,
        "String" => TypeKind::String,
        "PathBuf" => TypeKind::PathBuf,
        "Option" => {
            // Drill into the Option<T>'s inner type.
            let syn::PathArguments::AngleBracketed(args) = &last.arguments else {
                return TypeKind::OptionOther;
            };
            let Some(syn::GenericArgument::Type(inner)) = args.args.first() else {
                return TypeKind::OptionOther;
            };
            let Type::Path(inner_tp) = inner else {
                return TypeKind::OptionOther;
            };
            let Some(inner_last) = inner_tp.path.segments.last() else {
                return TypeKind::OptionOther;
            };
            match inner_last.ident.to_string().as_str() {
                "String" => TypeKind::OptionString,
                "PathBuf" => TypeKind::OptionPathBuf,
                _ => TypeKind::OptionOther,
            }
        }
        _ => TypeKind::Other,
    }
}

fn lit_string(expr: &Expr) -> syn::Result<String> {
    if let Expr::Lit(syn::ExprLit { lit: Lit::Str(s), .. }) = expr {
        Ok(s.value())
    } else {
        Err(syn::Error::new_spanned(
            expr,
            "expected a string literal",
        ))
    }
}

fn field_name_to_env(name: &str) -> String {
    // snake_case → SCREAMING_SNAKE_CASE. The struct's prefix is joined
    // separately, so e.g. `max_connections` → `MAX_CONNECTIONS`, paired with
    // `SINEX_DB` becomes `SINEX_DB_MAX_CONNECTIONS`.
    name.to_uppercase()
}
