pub mod event_types;
pub mod agent_events;
pub mod dlq;
pub mod manifest;
pub mod database;
pub mod error;
pub mod validation;
pub mod assumption_detector;
pub mod ingestor_framework;
pub mod event_sink;
pub mod ingestor_runtime;
pub mod event_models;
pub mod error_handling;
pub mod observability;
pub mod config_management;
pub mod testing_framework;

pub use sinex_ulid::Ulid;
pub use sinex_db::models::RawEvent;
pub use event_types::{RawEventBuilder, sources, event_types as event_type_constants};
pub use agent_events::*;
pub use dlq::*;
pub use manifest::*;
pub use database::*;
pub use error::*;
pub use validation::{EventValidator, ValidationError};
pub use assumption_detector::{AssumptionDetector, AssumptionError};
pub use event_sink::{EventSink, DatabaseSink, LogSink, FileSink, MemorySink, MultiSink};
pub use ingestor_runtime::{SimpleIngestor, IngestorRuntime, RuntimeConfig};
pub use event_models::{TerminalEvent, FilesystemEvent, HyprlandEvent, EventPayload, ValidationError as EventValidationError};
pub use error_handling::{IngestorError, IngestorResult, ErrorExt, ErrorCategory, RetryPolicy, CircuitBreaker};
pub use observability::{IngestorMetrics, TraceContext, EventInstrumentation, HealthStatus, init_observability};
pub use config_management::{ValidatedConfig, ConfigManager, ConfigSource, FileConfigSource, EnvConfigSource};