// Comprehensive schema validation testing
//
// Tests for:
// - Malformed event detection
// - Schema constraint validation
// - JSON payload validation
// - Security validation (injection attacks, null bytes, etc.)
// - Performance under load

use chrono::Utc;
use serde_json::{json, Value};
use sinex_core::db::integrity::malformed_detection;
use sinex_core::db::models::event::{Event, Provenance, SourceMaterial};
use sinex_core::db::validation::{EventValidator, ValidationError, DEFAULT_MAX_PAYLOAD_BYTES};
use sinex_core::types::domain::{EventSource, EventType, HostName};
use sinex_core::types::Id;
use sinex_test_utils::{acquire_pool_test_guard, sinex_test, TestContext};

const FS_WATCHER_SOURCE: &str = "fs-watcher";

#[sinex_test]
async fn test_malformed_event_detection(ctx: TestContext) -> color_eyre::eyre::Result<()> {
    let pool = ctx.pool.clone();
    let validator = EventValidator::load_from_db(&pool).await?;

    // Test malformed events generated by the integrity module
    let malformed_events = malformed_detection::generate_malformed_test_events();
    let mut validation_results = Vec::new();

    for (i, event) in malformed_events.iter().enumerate() {
        let result = validator.validate(event);

        tracing::info!(
            "Testing malformed event {} (type: {}): validation result = {}",
            i,
            event.event_type,
            result.is_ok()
        );

        assert!(
            result.is_err(),
            "Malformed event {} should fail validation",
            i
        );

        let error = result.unwrap_err();
        let error_type = match event.event_type.as_str() {
            "null_payload" => {
                // Null payload should fail validation
                match error {
                    ValidationError::InvalidType { ref field, .. } if field == "payload" => {
                        "payload_invalid_type"
                    }
                    ValidationError::SecurityValidation(_) => "security_validation",
                    _ => {
                        panic!(
                            "Expected payload validation error for null payload, got: {:?}",
                            error
                        );
                    }
                }
            }
            "empty_source" => {
                // Empty source should fail validation
                match error {
                    ValidationError::InvalidValue { ref field, .. } if field == "source" => {
                        "source_invalid_value"
                    }
                    _ => {
                        panic!(
                            "Expected source validation error for empty source, got: {:?}",
                            error
                        );
                    }
                }
            }
            "oversized_payload" => {
                // Large payload should be detected
                tracing::debug!("Oversized payload validation result: {:?}", error);
                "oversized_payload_detected"
            }
            _ => "other_validation_error",
        };

        validation_results.push(serde_json::json!({
            "event_index": i,
            "event_type": event.event_type,
            "source": event.source,
            "error_type": error_type,
            "error_message": error.to_string(),
            "payload_size": event.payload.to_string().len()
        }));
    }

    Ok(())
}

#[sinex_test]
async fn test_schema_constraint_validation(ctx: TestContext) -> color_eyre::eyre::Result<()> {
    let _guard = acquire_pool_test_guard().await;
    ctx.ensure_clean().await?;
    let pool = ctx.pool.clone();
    let validator = EventValidator::load_from_db(&pool).await?;

    // Test filesystem events with missing required fields
    let invalid_filesystem_event = build_test_event(
        FS_WATCHER_SOURCE,
        "file.created",
        json!({
            // Missing required "path" field
            "size": 1024,
            "permissions": "644"
        }),
    );

    let result = validator.validate(&invalid_filesystem_event);
    assert!(
        result.is_err(),
        "Event missing required field should fail validation"
    );

    match result.unwrap_err() {
        ValidationError::MissingField { field } => {
            assert_eq!(field, "path", "Should detect missing path field");
        }
        _ => panic!("Expected MissingField error"),
    }

    // Test with invalid field types
    let invalid_type_event = build_test_event(
        FS_WATCHER_SOURCE,
        "file.created",
        json!({
            "path": "/test/file.txt",
            "size": "not_a_number", // Should be numeric
            "permissions": 644
        }),
    );

    let result = validator.validate(&invalid_type_event);
    assert!(
        result.is_err(),
        "Event with invalid field type should fail validation"
    );

    Ok(())
}

/// Test JSON payload validation with various malformed scenarios
#[sinex_test]
async fn test_json_payload_validation(ctx: TestContext) -> color_eyre::eyre::Result<()> {
    let validator = EventValidator::load_from_db(&ctx.pool).await?;
    let cases = vec![
        (json!("just a string"), "string payload should fail", false),
        (json!(42), "numeric payload should fail", false),
        (json!(true), "boolean payload should fail", false),
        (json!(null), "null payload should fail", false),
        (json!([1, 2, 3]), "array payload should fail", false),
        (json!({}), "empty object should pass basic validation", true),
        (
            json!({"data": "valid", "size": 100}),
            "valid object should pass",
            true,
        ),
    ];

    for (payload, description, should_pass) in cases {
        let event = build_test_event("test.validation", "json_test", payload);
        let result = validator.validate(&event);

        match (result.is_ok(), should_pass) {
            (true, true) | (false, false) => {}
            (true, false) => tracing::warn!("Unexpected validation pass: {}", description),
            (false, true) => {
                let error = result.unwrap_err();
                panic!(
                    "Expected validation to pass for {}, but got error: {}",
                    description, error
                );
            }
        }
    }

    Ok(())
}

/// Test security validation against various injection attack patterns
#[sinex_test]
async fn test_security_validation_injection_attacks(
    ctx: TestContext,
) -> color_eyre::eyre::Result<()> {
    let validator = EventValidator::load_from_db(&ctx.pool).await?;
    let cases = vec![
        (
            json!({"path": "/test'; DROP TABLE core.events; --", "size": 1024}),
            "sql_injection",
            "Should detect SQL injection attempts",
        ),
        (
            json!({"path": "/test/<script>alert('xss')</script>", "size": 1024}),
            "xss_injection",
            "Should detect XSS injection attempts",
        ),
        (
            json!({"path": "../../../etc/passwd", "size": 1024}),
            "path_traversal",
            "Should detect path traversal attempts",
        ),
        (
            json!({"path": "/test/file\u{0000}.txt", "size": 1024}),
            "null_byte_injection",
            "Should detect null byte injection",
        ),
        (
            json!({"path": "/test/file\x01\x02\x03.txt", "size": 1024}),
            "control_char_injection",
            "Should detect control character injection",
        ),
        (
            json!({"path": "/test/\u{202e}\u{0301}file.txt", "size": 1024}),
            "unicode_attack",
            "Should detect Unicode normalization attacks",
        ),
    ];

    for (payload, attack_type, description) in cases {
        let event = build_test_event(FS_WATCHER_SOURCE, "file.created", payload);
        let result = validator.validate(&event);
        tracing::info!("Testing {} attack: {}", attack_type, description);
        if result.is_err() {
            tracing::info!("{} attack blocked: {:?}", attack_type, result);
        }
    }

    Ok(())
}

#[sinex_test]
async fn test_schema_validation_performance_under_load(
    ctx: TestContext,
) -> color_eyre::eyre::Result<()> {
    let pool = ctx.pool.clone();
    let validator = EventValidator::load_from_db(&pool).await?;

    // Generate a large number of events to test performance
    let num_events = 1000;
    let mut events = Vec::new();

    for i in 0..num_events {
        let payload = json!({
            "path": format!("/test/performance/file_{i}.txt"),
            "size": 1024,
            "permissions": 0o644
        });
        events.push(build_test_event(FS_WATCHER_SOURCE, "file.created", payload));
    }

    // Measure validation performance
    let start_time = std::time::Instant::now();
    let mut validation_results = Vec::new();

    for event in &events {
        let result = validator.validate(event);
        validation_results.push(result.is_ok());
    }

    let elapsed = start_time.elapsed();
    let events_per_second = num_events as f64 / elapsed.as_secs_f64();

    println!(
        "Validated {} events in {:?} ({:.2} events/sec)",
        num_events, elapsed, events_per_second
    );

    // Verify all valid events passed
    let passed_count = validation_results.iter().filter(|&&passed| passed).count();
    assert_eq!(
        passed_count, num_events,
        "All valid events should pass validation"
    );

    // Performance should be reasonable (adjust threshold as needed)
    assert!(
        events_per_second > 100.0,
        "Validation performance too slow: {:.2} events/sec",
        events_per_second
    );

    Ok(())
}

#[sinex_test]
async fn test_comprehensive_integrity_validation(ctx: TestContext) -> color_eyre::eyre::Result<()> {
    let pool = ctx.pool.clone();
    let validator = EventValidator::load_from_db(&pool).await?;

    let persisted = ctx
        .create_test_event(
            "schema.comprehensive",
            "valid_event",
            json!({"data": "valid"}),
        )
        .await?;
    let _persisted_id = persisted.id.as_ref().map(|id| id.to_string());

    let scenarios = vec![
        (
            "valid_event",
            build_test_event(
                "schema.comprehensive",
                "valid_event",
                json!({"data": "valid"}),
            ),
            true,
        ),
        (
            "missing_path",
            build_test_event(FS_WATCHER_SOURCE, "file.created", json!({"size": 2048})),
            false,
        ),
        (
            "invalid_type",
            build_test_event(
                FS_WATCHER_SOURCE,
                "file.created",
                json!({"path": "/tmp/file.txt", "size": "oops"}),
            ),
            false,
        ),
        (
            "oversized_payload",
            build_test_event(
                FS_WATCHER_SOURCE,
                "file.created",
                json!({"path": "/tmp/big.bin", "size": 1024, "blob": "x".repeat(600_000)}),
            ),
            false,
        ),
    ];

    let mut summary = Vec::new();
    let mut pass_count = 0;
    let mut fail_count = 0;

    for (name, event, should_pass) in scenarios {
        let result = validator.validate(&event);
        if result.is_ok() {
            pass_count += 1;
        } else {
            fail_count += 1;
        }

        summary.push(json!({
            "scenario": name,
            "should_pass": should_pass,
            "passed": result.is_ok(),
            "error": result.err().map(|e| e.to_string())
        }));
    }

    assert!(pass_count >= 1, "expected at least one passing scenario");
    assert!(fail_count >= 1, "expected at least one failing scenario");

    Ok(())
}

/// Test malformed event anomaly detection with various problematic patterns
#[sinex_test]
async fn test_malformed_event_anomaly_detection(ctx: TestContext) -> color_eyre::eyre::Result<()> {
    let cases = vec![
        (
            "",
            "empty.source",
            json!({"data": "test"}),
            "empty_source",
            true,
            "Should detect empty source field",
        ),
        (
            "test\0source",
            "null.byte",
            json!({"data": "test"}),
            "null_bytes",
            true,
            "Should detect null bytes in source",
        ),
        (
            "test.source",
            "oversized",
            json!({"large_field": "x".repeat(DEFAULT_MAX_PAYLOAD_BYTES + 1024)}),
            "oversized_payload",
            true,
            "Should detect oversized payload",
        ),
        (
            "test.source",
            "valid",
            json!({"data": "valid"}),
            "valid_event",
            false,
            "Valid event should have no anomalies",
        ),
    ];

    for (source, event_type, payload, category, should_have_anomalies, description) in cases {
        let event = build_test_event(source, event_type, payload);
        let anomalies = malformed_detection::detect_schema_anomalies(&event);
        tracing::info!(
            "Testing {}: detected {} anomalies",
            description,
            anomalies.len()
        );

        if should_have_anomalies {
            assert!(
                !anomalies.is_empty(),
                "Expected anomalies for {}, but none detected",
                description
            );
        } else {
            assert!(
                anomalies.is_empty(),
                "Expected no anomalies for {}, but detected: {:?}",
                description,
                anomalies
            );
        }
        tracing::debug!("Anomalies for {}: {:?}", category, anomalies);
    }

    Ok(())
}

// Test schema validation with various event types
#[sinex_test]
async fn test_event_type_specific_validation(ctx: TestContext) -> color_eyre::eyre::Result<()> {
    let pool = ctx.pool.clone();
    let validator = EventValidator::load_from_db(&pool).await?;

    // Test filesystem events
    let filesystem_tests = vec![
        // Valid filesystem event
        (
            build_test_event(
                FS_WATCHER_SOURCE,
                "file.created",
                json!({"path": "/test/valid.txt", "size": 1024, "permissions": 0o644}),
            ),
            true,
        ),
        // Invalid filesystem event - missing path
        (
            build_test_event(FS_WATCHER_SOURCE, "file.created", json!({"size": 1024})),
            false,
        ),
        // Invalid filesystem event - invalid size type
        (
            build_test_event(
                FS_WATCHER_SOURCE,
                "file.created",
                json!({"path": "/test.txt", "size": "not_a_number"}),
            ),
            false,
        ),
    ];

    for (event, should_pass) in filesystem_tests {
        let result = validator.validate(&event);
        if should_pass {
            assert!(
                result.is_ok(),
                "Valid filesystem event should pass: {:?}",
                result
            );
        } else {
            assert!(result.is_err(), "Invalid filesystem event should fail");
        }
    }

    // Test terminal events
    let terminal_tests = vec![
        // Valid terminal event
        (
            build_test_event(
                "terminal.kitty",
                "command.executed",
                json!({"command": "echo test", "exit_code": 0, "timestamp": "2024-01-01T00:00:00Z"}),
            ),
            true,
        ),
        // Invalid terminal event - missing command
        (
            build_test_event(
                "terminal.kitty",
                "command.executed",
                json!({"exit_code": 0}),
            ),
            false,
        ),
    ];

    for (event, should_pass) in terminal_tests {
        let result = validator.validate(&event);
        if should_pass {
            assert!(
                result.is_ok(),
                "Valid terminal event should pass: {:?}",
                result
            );
        } else {
            assert!(result.is_err(), "Invalid terminal event should fail");
        }
    }

    Ok(())
}

fn build_test_event(source: &str, event_type: &str, payload: Value) -> Event<Value> {
    Event {
        id: None,
        source: EventSource::from(source.to_string()),
        event_type: EventType::from(event_type.to_string()),
        payload,
        ts_orig: Some(Utc::now()),
        host: HostName::from_static("schema-tests"),
        ingestor_version: None,
        payload_schema_id: None,
        provenance: Provenance::from_material(Id::<SourceMaterial>::new(), 0, None, None),
        associated_blob_ids: None,
    }
}
