changelog:
  categories:
    - title: Features and Changes
      labels:
        - enhancement
    - title: Bug Fixes
      labels:
        - bug
    - title: Research and Decisions
      labels:
        - question
    - title: Other
      labels:
        - "*"
