//! Nix Module Integration Tests
//!
//! Tests that verify Sinex integrates correctly with its NixOS module system.
//! This includes configuration validation, service management, and module behavior.

use serde_json::json;
use std::collections::{HashMap, HashSet};
use xtask::sandbox::{prelude::*, TestResult};

// =============================================================================
// NIXOS MODULE CONFIGURATION TESTS
// =============================================================================

#[sinex_test]
async fn test_nixos_module_config_validation(ctx: TestContext) -> TestResult<()> {
    // Test that NixOS module configuration structure is valid
    let module_config = create_test_module_config();

    // Validate configuration structure
    assert!(
        module_config.as_object().unwrap().contains_key("services"),
        "Should have services key"
    );
    assert!(
        module_config["services"].get("sinex").is_some(),
        "Should have sinex service config"
    );

    let sinex_config = &module_config["services"]["sinex"];
    assert!(
        sinex_config.get("enable").is_some(),
        "Should have enable flag"
    );
    assert!(
        sinex_config.get("database").is_some(),
        "Should have database config"
    );
    assert!(
        sinex_config.get("nodes").is_some(),
        "Should have node config"
    );
    assert!(
        sinex_config.get("shell").is_some(),
        "Should have shell helpers config"
    );

    // Validate database configuration
    let db_config = &sinex_config["database"];
    assert!(db_config.get("host").is_some(), "Should have database host");
    assert!(db_config.get("port").is_some(), "Should have database port");
    assert!(db_config.get("name").is_some(), "Should have database name");

    // Validate node event source configuration
    let node_config = &sinex_config["nodes"];
    assert!(
        node_config.get("eventSources").is_some(),
        "Node config should expose event sources"
    );

    let event_sources_config = &node_config["eventSources"];
    for source in ["filesystem", "terminal", "desktop", "system"] {
        assert!(
            event_sources_config.get(source).is_some(),
            "Node configuration should expose {} source config",
            source
        );
    }

    // Validate shell helper configuration
    let shell_config = &sinex_config["shell"];
    assert!(
        shell_config.get("asciinema").is_some(),
        "Shell config should expose asciinema settings"
    );
    assert!(
        shell_config.get("kitty").is_some(),
        "Shell config should expose kitty settings"
    );

    // Validate configuration can be serialized (basic structure test)
    let _config_json =
        serde_json::to_string(&module_config).expect("Module config should be valid JSON");

    Ok(())
}

#[sinex_test]
async fn test_nixos_service_definitions() -> TestResult<()> {
    // Test service definition structures that would be generated by the NixOS module
    let service_definitions = create_test_service_definitions();

    // Validate core services are defined
    let expected_services = vec![
        "sinex-ingestd",
        "sinex-gateway",
        "sinex-fs-ingestor-1",
        "sinex-terminal-ingestor-1",
        "sinex-desktop-ingestor-1",
        "sinex-system-ingestor-1",
        "sinex-health-automaton",
    ];

    for service in expected_services {
        assert!(
            service_definitions.contains_key(service),
            "Service {} should be defined",
            service
        );

        let service_def = &service_definitions[service];

        // Validate service has required systemd fields
        assert!(
            service_def.get("description").is_some(),
            "{} should have description",
            service
        );
        assert!(
            service_def.get("wantedBy").is_some(),
            "{} should specify wantedBy",
            service
        );
        assert!(
            service_def.get("after").is_some(),
            "{} should specify dependencies",
            service
        );
        assert!(
            service_def.get("serviceConfig").is_some(),
            "{} should have serviceConfig",
            service
        );

        // Validate serviceConfig has essential fields
        let service_config = &service_def["serviceConfig"];
        assert!(
            service_config.get("ExecStart").is_some(),
            "{} should have ExecStart",
            service
        );
        assert!(
            service_config.get("Restart").is_some(),
            "{} should have Restart policy",
            service
        );
        assert!(
            service_config.get("User").is_some(),
            "{} should specify User",
            service
        );
    }

    // Validate service definitions structure
    let _service_json = serde_json::to_string(&service_definitions)
        .expect("Service definitions should be valid JSON");

    Ok(())
}

#[sinex_test]
async fn test_nixos_module_options_schema() -> TestResult<()> {
    // Test the NixOS module options schema structure
    let module_options = create_test_module_options_schema();

    // Validate top-level option categories
    let expected_categories = vec!["enable", "database", "nodes", "shell", "logging"];

    for category in expected_categories {
        assert!(
            module_options.as_object().unwrap().contains_key(category),
            "Module should have {} options",
            category
        );

        let option_def = &module_options[category];

        // Each option should have type and description
        if let Some(obj) = option_def.as_object() {
            if !obj.contains_key("_meta") {
                // Skip meta entries
                assert!(obj.get("type").is_some(), "{} should have type", category);
                assert!(
                    obj.get("description").is_some(),
                    "{} should have description",
                    category
                );
            }
        }
    }

    // Validate source-specific options
    let event_source_options = &module_options["nodes"]["options"]["eventSources"]["options"];
    let source_types = vec!["filesystem", "terminal", "desktop", "system"];

    for source_type in source_types {
        let source_config = &event_source_options[source_type];
        let options = source_config["options"]
            .as_object()
            .expect("source options should be defined");
        assert!(
            options.contains_key("enable"),
            "{} source should expose an enable option",
            source_type
        );
    }

    // Validate module options can be serialized
    let _options_json =
        serde_json::to_string(&module_options).expect("Module options should be valid JSON");

    Ok(())
}

// =============================================================================
// SERVICE INTEGRATION TESTS
// =============================================================================

#[sinex_test]
async fn test_service_dependency_chain() -> TestResult<()> {
    // Test that service dependencies are properly configured
    let dependency_chain = create_test_dependency_chain();

    // Validate dependency ordering
    let postgres_deps = &dependency_chain["postgresql"];
    assert!(
        postgres_deps.is_empty(),
        "PostgreSQL should have no Sinex dependencies"
    );

    let ingestd_deps = &dependency_chain["sinex-ingestd"];
    assert!(
        ingestd_deps.contains(&"postgresql.service".to_string()),
        "ingestd should depend on postgres"
    );

    let watcher_services = [
        "sinex-fs-ingestor-1",
        "sinex-terminal-ingestor-1",
        "sinex-desktop-ingestor-1",
        "sinex-system-ingestor-1",
    ];

    for watcher in watcher_services {
        let deps = &dependency_chain[watcher];
        assert!(
            deps.contains(&"sinex-ingestd.service".to_string()),
            "{} should depend on ingestd",
            watcher
        );
    }

    let gateway_deps = &dependency_chain["sinex-gateway"];
    assert!(
        gateway_deps.contains(&"postgresql.service".to_string()),
        "gateway should depend on postgres"
    );

    // Validate no circular dependencies
    assert_no_circular_dependencies(&dependency_chain)?;

    // Validate dependency chain structure
    let _deps_json =
        serde_json::to_string(&dependency_chain).expect("Dependency chain should be valid JSON");

    Ok(())
}

#[sinex_test]
async fn test_systemd_service_configuration() -> TestResult<()> {
    // Test systemd service configuration details
    let service_config = create_test_systemd_service_config();

    for (service_name, config) in &service_config {
        let service_config_obj = &config["serviceConfig"];

        // Validate security settings
        if let Some(dynamic_user) = service_config_obj.get("DynamicUser") {
            assert_eq!(
                dynamic_user.as_bool().unwrap_or(false),
                false,
                "{} should not use DynamicUser (uses static sinex user)",
                service_name
            );
        }

        // Validate restart policy
        let restart = service_config_obj["Restart"].as_str().unwrap();
        assert!(
            restart == "always" || restart == "on-failure",
            "{} should have appropriate restart policy, got: {}",
            service_name,
            restart
        );

        // Validate user/group
        assert_eq!(
            service_config_obj["User"].as_str().unwrap(),
            "sinex",
            "{} should run as sinex user",
            service_name
        );

        // Validate environment variables are set
        if let Some(environment) = service_config_obj.get("Environment") {
            let env_vars = environment.as_array().unwrap();
            let has_db_url = env_vars
                .iter()
                .any(|var| var.as_str().unwrap().starts_with("DATABASE_URL="));
            assert!(has_db_url, "{} should have DATABASE_URL set", service_name);
        }
    }

    // Validate service configuration structure
    let _config_json =
        serde_json::to_string(&service_config).expect("Service config should be valid JSON");

    Ok(())
}

#[sinex_test]
async fn test_nixos_module_security_settings() -> TestResult<()> {
    // Test security-related NixOS module settings
    let security_config = create_test_security_config();

    // Validate user configuration
    let users = &security_config["users"];
    let sinex_user = &users["users"]["sinex"];

    assert!(
        sinex_user.get("isSystemUser").unwrap().as_bool().unwrap(),
        "sinex should be system user"
    );
    assert!(
        sinex_user.get("group").is_some(),
        "sinex user should have group"
    );
    assert!(
        sinex_user.get("home").is_some(),
        "sinex user should have home directory"
    );

    // Validate group configuration
    let groups = &users["groups"];
    assert!(groups.get("sinex").is_some(), "sinex group should exist");

    // Validate directory permissions
    let tmpfiles = &security_config["systemd"]["tmpfiles"]["rules"];
    let rules = tmpfiles.as_array().unwrap();

    let has_data_dir = rules.iter().any(|rule| {
        let rule_str = rule.as_str().unwrap();
        rule_str.contains("/var/lib/sinex") && rule_str.contains("0755 sinex sinex")
    });
    assert!(
        has_data_dir,
        "Should create sinex data directory with correct permissions"
    );

    let has_log_dir = rules.iter().any(|rule| {
        let rule_str = rule.as_str().unwrap();
        rule_str.contains("/var/log/sinex") && rule_str.contains("sinex sinex")
    });
    assert!(has_log_dir, "Should create sinex log directory");

    // Validate security configuration structure
    let _security_json =
        serde_json::to_string(&security_config).expect("Security config should be valid JSON");

    Ok(())
}

// =============================================================================
// CONFIGURATION VALIDATION TESTS
// =============================================================================

#[sinex_test]
async fn test_database_configuration_integration() -> TestResult<()> {
    // Test that database configuration from NixOS module works correctly
    let db_config = create_test_database_module_config();

    // Test connection string generation
    let conn_str = generate_connection_string(&db_config);
    assert!(
        conn_str.contains("postgresql://"),
        "Should generate PostgreSQL connection string"
    );
    assert!(conn_str.contains("sinex"), "Should include database name");

    // Test database initialization settings
    let pg_config = &db_config["services"]["postgresql"];
    assert!(
        pg_config["enable"].as_bool().unwrap(),
        "PostgreSQL should be enabled"
    );

    let extensions = pg_config["extraPlugins"].as_array().unwrap();
    let has_timescale = extensions
        .iter()
        .any(|ext| ext.as_str().unwrap().contains("timescaledb"));
    assert!(has_timescale, "Should include TimescaleDB extension");

    let has_jsonschema = extensions
        .iter()
        .any(|ext| ext.as_str().unwrap().contains("pg_jsonschema"));
    assert!(has_jsonschema, "Should include pg_jsonschema extension");

    // Test database initialization scripts
    let init_scripts = &db_config["services"]["postgresql"]["initialScript"];
    let script_content = init_scripts.as_str().unwrap();
    assert!(
        script_content.contains("CREATE DATABASE sinex"),
        "Should create sinex database"
    );
    assert!(
        script_content.contains("CREATE USER sinex"),
        "Should create sinex user"
    );

    // Validate database configuration structure
    let _db_json = serde_json::to_string(&db_config).expect("Database config should be valid JSON");

    Ok(())
}

#[sinex_test]
async fn test_node_source_configuration() -> TestResult<()> {
    // Test individual node source configurations from the NixOS module
    let sources_config = create_test_sources_config();

    // Test filesystem source
    let fs_config = &sources_config["filesystem"];
    assert!(
        fs_config["enable"].as_bool().unwrap_or(false),
        "Filesystem source should be enabled by default"
    );

    if let Some(watch_paths) = fs_config.get("watchPaths") {
        let paths = watch_paths.as_array().unwrap();
        assert!(!paths.is_empty(), "Should have default watch paths");

        // Verify paths are reasonable
        for path in paths {
            let path_str = path.as_str().unwrap();
            assert!(
                path_str.starts_with('/'),
                "Watch paths should be absolute: {}",
                path_str
            );
        }
    }

    // Test terminal source
    let terminal_config = &sources_config["terminal"];
    assert!(
        terminal_config["enable"].as_bool().unwrap_or(false),
        "Terminal source should be enabled"
    );
    if let Some(instances) = terminal_config.get("instances") {
        assert!(
            instances.as_i64().unwrap_or(0) >= 1,
            "Terminal source should define instances >= 1"
        );
    }

    // Desktop and system sources should exist
    assert!(
        sources_config.get("desktop").is_some(),
        "Desktop source should be present"
    );
    assert!(
        sources_config.get("system").is_some(),
        "System source should be present"
    );

    // Validate sources configuration structure
    let _sources_json =
        serde_json::to_string(&sources_config).expect("Sources config should be valid JSON");

    Ok(())
}

// =============================================================================
// SYSTEM INTEGRATION TESTS
// =============================================================================

#[sinex_test]
async fn test_nixos_system_integration_points() -> TestResult<()> {
    // Test key system integration points that the NixOS module provides
    let system_integration = create_test_system_integration_config();

    // Test systemd integration
    let systemd_config = &system_integration["systemd"];

    // Validate service definitions
    let services = &systemd_config["services"];
    for (service_name, _config) in services.as_object().unwrap() {
        assert!(
            service_name.starts_with("sinex-"),
            "Sinex services should have sinex- prefix: {}",
            service_name
        );
    }

    // Test logging integration
    let logging = &system_integration["logging"];
    assert!(
        logging.get("journaldIntegration").is_some(),
        "Should integrate with journald"
    );
    assert!(
        logging.get("logRotation").is_some(),
        "Should configure log rotation"
    );

    // Test monitoring integration
    let monitoring = &system_integration["monitoring"];
    if monitoring["enable"].as_bool().unwrap_or(false) {
        assert!(
            monitoring.get("healthChecks").is_some(),
            "Should provide health check endpoints"
        );
        assert!(
            monitoring.get("metrics").is_some(),
            "Should expose metrics for monitoring"
        );
    }

    // Test backup integration points
    let backup = &system_integration["backup"];
    if backup["enable"].as_bool().unwrap_or(false) {
        assert!(
            backup.get("dataDirectories").is_some(),
            "Should specify directories to backup"
        );
        assert!(
            backup.get("excludePatterns").is_some(),
            "Should specify backup exclusions"
        );
    }

    // Validate system integration configuration
    let _system_json = serde_json::to_string(&system_integration)
        .expect("System integration config should be valid JSON");

    Ok(())
}

#[sinex_test]
async fn test_module_upgrade_compatibility() -> TestResult<()> {
    // Test that module configuration remains compatible across versions
    let version_configs = create_test_version_configs();

    for (version, config) in &version_configs {
        // Validate that essential configuration structure is preserved
        assert!(
            config
                .get("services")
                .and_then(|s| s.get("sinex"))
                .is_some(),
            "Version {} should have services.sinex configuration",
            version
        );

        let sinex_config = &config["services"]["sinex"];

        // Core options should be present in all versions
        let core_options = vec!["enable", "database", "nodes", "shell"];
        for option in core_options {
            assert!(
                sinex_config.get(option).is_some(),
                "Version {} should have {} option",
                version,
                option
            );
        }

        // Validate database configuration compatibility
        let db_config = &sinex_config["database"];
        let required_db_fields = vec!["host", "port", "name"];
        for field in required_db_fields {
            assert!(
                db_config.get(field).is_some(),
                "Version {} database config should have {} field",
                version,
                field
            );
        }
    }

    // Test configuration migration/compatibility patterns
    let migration_info = create_test_migration_info(&version_configs);
    assert!(
        !migration_info["breaking_changes"]
            .as_array()
            .unwrap()
            .is_empty()
            || migration_info["backward_compatible"].as_bool().unwrap(),
        "Should either have no breaking changes or provide migration path"
    );

    // Validate version compatibility structure
    let _version_json =
        serde_json::to_string(&version_configs).expect("Version configs should be valid JSON");
    let _migration_json =
        serde_json::to_string(&migration_info).expect("Migration info should be valid JSON");

    Ok(())
}

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

fn create_test_module_config() -> serde_json::Value {
    json!({
        "services": {
            "sinex": {
                "enable": true,
                "database": {
                    "host": "localhost",
                    "port": 5432,
                    "name": "sinex",
                    "user": "sinex"
                },
                "nodes": {
                    "enable": true,
                    "eventSources": {
                        "filesystem": {"enable": true, "watchPaths": ["/home"]},
                        "terminal": {"enable": true, "instances": 2},
                        "desktop": {"enable": false},
                        "system": {"enable": true}
                    }
                },
                "shell": {
                    "asciinema": {
                        "autoRecord": false,
                        "recordingsPath": "~/.local/share/asciinema"
                    },
                    "kitty": {
                        "enable": true,
                        "autoConfigure": true,
                        "userConfigPath": "~/.config/kitty/kitty.conf"
                    }
                },
                "gateway": {
                    "enable": true,
                    "port": 8080
                },
                "logging": {
                    "level": "info",
                    "structured": true
                }
            }
        }
    })
}

fn create_test_service_definitions() -> HashMap<String, serde_json::Value> {
    let mut services = HashMap::new();

    services.insert(
        "sinex-ingestd".to_string(),
        json!({
            "description": "Sinex Event Ingestion Daemon",
            "wantedBy": ["multi-user.target"],
            "after": ["postgresql.service"],
            "requires": ["postgresql.service"],
            "serviceConfig": {
                "ExecStart": "/nix/store/.../bin/sinex-ingestd",
                "Restart": "always",
                "RestartSec": 10,
                "User": "sinex",
                "Group": "sinex",
                "Environment": [
                    "DATABASE_URL=postgresql://sinex@localhost/sinex"
                ]
            }
        }),
    );

    services.insert(
        "sinex-gateway".to_string(),
        json!({
            "description": "Sinex API Gateway",
            "wantedBy": ["multi-user.target"],
            "after": ["postgresql.service"],
            "serviceConfig": {
                "ExecStart": "/nix/store/.../bin/sinex-gateway rpc-server",
                "Restart": "on-failure",
                "User": "sinex",
                "Group": "sinex"
            }
        }),
    );

    services.insert(
        "sinex-fs-ingestor-1".to_string(),
        json!({
            "description": "Sinex filesystem watcher (instance 1)",
            "wantedBy": ["multi-user.target"],
            "after": ["sinex-ingestd.service"],
            "requires": ["sinex-ingestd.service"],
            "serviceConfig": {
                "ExecStart": "/nix/store/.../bin/sinex-fs-ingestor --service-name sinex-fs-ingestor",
                "Restart": "on-failure",
                "User": "sinex",
                "Group": "sinex"
            }
        }),
    );

    services.insert("sinex-terminal-ingestor-1".to_string(), json!({
        "description": "Sinex terminal event source (instance 1)",
        "wantedBy": ["multi-user.target"],
        "after": ["sinex-ingestd.service"],
        "serviceConfig": {
            "ExecStart": "/nix/store/.../bin/sinex-terminal-ingestor --service-name sinex-terminal-ingestor",
            "Restart": "on-failure",
            "User": "sinex",
            "Group": "sinex"
        }
    }));

    services.insert("sinex-desktop-ingestor-1".to_string(), json!({
        "description": "Sinex desktop event source (instance 1)",
        "wantedBy": ["multi-user.target"],
        "after": ["sinex-ingestd.service"],
        "serviceConfig": {
            "ExecStart": "/nix/store/.../bin/sinex-desktop-ingestor --service-name sinex-desktop-ingestor",
            "Restart": "on-failure",
            "User": "sinex",
            "Group": "sinex"
        }
    }));

    services.insert("sinex-system-ingestor-1".to_string(), json!({
        "description": "Sinex system event source (instance 1)",
        "wantedBy": ["multi-user.target"],
        "after": ["sinex-ingestd.service"],
        "serviceConfig": {
            "ExecStart": "/nix/store/.../bin/sinex-system-ingestor --service-name sinex-system-ingestor",
            "Restart": "on-failure",
            "User": "sinex",
            "Group": "sinex"
        }
    }));

    services.insert(
        "sinex-health-automaton".to_string(),
        json!({
            "description": "Sinex Health Aggregator",
            "wantedBy": ["multi-user.target"],
            "after": ["sinex-ingestd.service"],
            "serviceConfig": {
                "ExecStart": "/nix/store/.../bin/sinex-health-automaton",
                "Restart": "on-failure",
                "User": "sinex",
                "Group": "sinex"
            }
        }),
    );

    services
}

fn create_test_module_options_schema() -> serde_json::Value {
    json!({
        "enable": {
            "type": "bool",
            "default": false,
            "description": "Whether to enable Sinex event capture system"
        },
        "database": {
            "type": "submodule",
            "description": "Database configuration",
            "options": {
                "host": {
                    "type": "str",
                    "default": "localhost",
                    "description": "Database host"
                },
                "port": {
                    "type": "int",
                    "default": 5432,
                    "description": "Database port"
                },
                "name": {
                    "type": "str",
                    "default": "sinex",
                    "description": "Database name"
                }
            }
        },
        "nodes": {
            "type": "submodule",
            "description": "Node configuration",
            "options": {
                "enable": {
                    "type": "bool",
                    "default": true,
                    "description": "Enable node ecosystem"
                },
                "eventSources": {
                    "type": "submodule",
                    "options": {
                        "filesystem": {
                            "type": "submodule",
                            "options": {
                                "enable": {"type": "bool", "default": true},
                                "watchPaths": {"type": "list", "default": ["/home"]}
                            }
                        },
                        "terminal": {
                            "type": "submodule",
                            "options": {
                                "enable": {"type": "bool", "default": true},
                                "instances": {"type": "int", "default": 2}
                            }
                        },
                        "desktop": {
                            "type": "submodule",
                            "options": {
                                "enable": {"type": "bool", "default": false}
                            }
                        },
                        "system": {
                            "type": "submodule",
                            "options": {
                                "enable": {"type": "bool", "default": true}
                            }
                        }
                    }
                }
            }
        },
        "shell": {
            "type": "submodule",
            "description": "Workstation shell helpers",
            "options": {
                "asciinema": {
                    "type": "submodule",
                    "options": {
                        "autoRecord": {"type": "bool", "default": false},
                        "recordingsPath": {"type": "str", "default": "~/.local/share/asciinema"}
                    }
                },
                "kitty": {
                    "type": "submodule",
                    "options": {
                        "enable": {"type": "bool", "default": true},
                        "autoConfigure": {"type": "bool", "default": true},
                        "userConfigPath": {"type": "str", "default": "~/.config/kitty/kitty.conf"}
                    }
                }
            }
        },
        "logging": {
            "type": "submodule",
            "description": "Logging configuration"
        }
    })
}

fn create_test_dependency_chain() -> HashMap<String, Vec<String>> {
    let mut deps = HashMap::new();

    deps.insert("postgresql".to_string(), vec![]);
    deps.insert(
        "sinex-ingestd".to_string(),
        vec!["postgresql.service".to_string()],
    );
    deps.insert(
        "sinex-gateway".to_string(),
        vec!["postgresql.service".to_string()],
    );
    deps.insert(
        "sinex-fs-ingestor-1".to_string(),
        vec!["sinex-ingestd.service".to_string()],
    );
    deps.insert(
        "sinex-terminal-ingestor-1".to_string(),
        vec!["sinex-ingestd.service".to_string()],
    );
    deps.insert(
        "sinex-desktop-ingestor-1".to_string(),
        vec!["sinex-ingestd.service".to_string()],
    );
    deps.insert(
        "sinex-system-ingestor-1".to_string(),
        vec!["sinex-ingestd.service".to_string()],
    );
    deps.insert(
        "sinex-health-automaton".to_string(),
        vec!["sinex-ingestd.service".to_string()],
    );

    deps
}

fn assert_no_circular_dependencies(deps: &HashMap<String, Vec<String>>) -> TestResult<()> {
    use std::collections::HashSet;

    for (service, _dependencies) in deps {
        let mut visited = HashSet::new();
        let mut path = Vec::new();

        if has_circular_dependency(service, deps, &mut visited, &mut path) {
            return Err(color_eyre::eyre::eyre!(
                "Circular dependency detected involving {}: {:?}",
                service,
                path
            ));
        }
    }

    Ok(())
}

fn has_circular_dependency(
    service: &str,
    deps: &HashMap<String, Vec<String>>,
    visited: &mut HashSet<String>,
    path: &mut Vec<String>,
) -> bool {
    if path.contains(&service.to_string()) {
        return true;
    }

    if visited.contains(service) {
        return false;
    }

    visited.insert(service.to_string());
    path.push(service.to_string());

    if let Some(dependencies) = deps.get(service) {
        for dep in dependencies {
            let dep_name = dep.replace(".service", "");
            if has_circular_dependency(&dep_name, deps, visited, path) {
                return true;
            }
        }
    }

    path.pop();
    false
}

fn create_test_systemd_service_config() -> HashMap<String, serde_json::Value> {
    create_test_service_definitions()
}

fn create_test_security_config() -> serde_json::Value {
    json!({
        "users": {
            "users": {
                "sinex": {
                    "isSystemUser": true,
                    "group": "sinex",
                    "home": "/var/lib/sinex",
                    "shell": "/run/current-system/sw/bin/nologin"
                }
            },
            "groups": {
                "sinex": {}
            }
        },
        "systemd": {
            "tmpfiles": {
                "rules": [
                    "d /var/lib/sinex 0755 sinex sinex -",
                    "d /var/log/sinex 0755 sinex sinex -",
                    "d /var/lib/sinex/.local 0755 sinex sinex -",
                    "d /var/lib/sinex/.local/share 0755 sinex sinex -"
                ]
            }
        }
    })
}

fn create_test_database_module_config() -> serde_json::Value {
    json!({
        "services": {
            "postgresql": {
                "enable": true,
                "package": "postgresql_15",
                "extraPlugins": [
                    "timescaledb",
                    "pg_jsonschema"
                ],
                "initialScript": r#"
                    CREATE USER sinex;
                    CREATE DATABASE sinex OWNER sinex;
                    GRANT ALL PRIVILEGES ON DATABASE sinex TO sinex;
                    ALTER USER sinex CREATEDB;
                "#,
                "authentication": "local sinex sinex peer"
            }
        }
    })
}

fn generate_connection_string(_config: &serde_json::Value) -> String {
    let host = "localhost";
    let port = 5432;
    let dbname = "sinex";
    let user = "sinex";

    format!("postgresql://{}@{}:{}/{}", user, host, port, dbname)
}

fn create_test_sources_config() -> serde_json::Value {
    json!({
        "filesystem": {
            "enable": true,
            "watchPaths": ["/home", "/var/log"]
        },
        "terminal": {
            "enable": true,
            "instances": 2
        },
        "desktop": {
            "enable": false
        },
        "system": {
            "enable": true
        }
    })
}
fn create_test_system_integration_config() -> serde_json::Value {
    json!({
        "systemd": {
            "services": {
                "sinex-ingestd": {"enable": true},
                "sinex-gateway": {"enable": true},
                "sinex-fs-ingestor-1": {"enable": true}
            }
        },
        "logging": {
            "journaldIntegration": true,
            "logRotation": {
                "maxFiles": 10,
                "maxSize": "100M"
            }
        },
        "monitoring": {
            "enable": false,
            "healthChecks": {
                "port": 9090,
                "path": "/health"
            },
            "metrics": {
                "prometheus": true,
                "port": 9091
            }
        },
        "backup": {
            "enable": false,
            "dataDirectories": [
                "/var/lib/sinex"
            ],
            "excludePatterns": [
                "*.tmp",
                "cache/*"
            ]
        }
    })
}

fn create_test_version_configs() -> HashMap<String, serde_json::Value> {
    let mut versions = HashMap::new();

    versions.insert(
        "0.1.0".to_string(),
        json!({
            "services": {
                "sinex": {
                    "enable": true,
                    "database": {
                        "host": "localhost",
                        "port": 5432,
                        "name": "sinex"
                    },
                    "nodes": {
                        "enable": true
                    },
                    "shell": {
                        "kitty": {"enable": true}
                    }
                }
            }
        }),
    );

    versions.insert(
        "0.2.0".to_string(),
        json!({
            "services": {
                "sinex": {
                    "enable": true,
                    "database": {
                        "host": "localhost",
                        "port": 5432,
                        "name": "sinex",
                        "user": "sinex"
                    },
                    "nodes": {
                        "enable": true,
                        "eventSources": {
                            "filesystem": {"enable": true}
                        }
                    },
                    "shell": {
                        "kitty": {"enable": true}
                    }
                }
            }
        }),
    );

    versions.insert(
        "0.3.0".to_string(),
        json!({
            "services": {
                "sinex": {
                    "enable": true,
                    "database": {
                        "host": "localhost",
                        "port": 5432,
                        "name": "sinex",
                        "user": "sinex"
                    },
                    "nodes": {
                        "enable": true,
                        "eventSources": {
                            "filesystem": {"enable": true},
                            "terminal": {"enable": true},
                            "system": {"enable": true}
                        }
                    },
                    "shell": {
                        "kitty": {"enable": true}
                    }
                }
            }
        }),
    );

    versions
}

fn create_test_migration_info(_versions: &HashMap<String, serde_json::Value>) -> serde_json::Value {
    json!({
        "backward_compatible": true,
        "breaking_changes": [],
        "deprecated_options": [
            {"version": "0.2.0", "option": "old_collector_config", "replacement": "node.eventSources"}
        ],
        "migration_path": {
            "0.1.0_to_0.2.0": "automatic",
            "0.2.0_to_0.3.0": "automatic"
        }
    })
}
