use crate::common::prelude::*;
use crate::common::property_builders::*;
use proptest::prelude::*;
use sinex_validation::EventValidator;
use sinex_ulid::Ulid;
use serde_json::Value;

proptest! {
    #![proptest_config(ProptestConfig::with_cases(1000))]

    #[test]
    fn valid_events_pass_validation(
        event in arbitrary_event()
    ) {
        // Property: All events generated by property builders should pass validation
        let validator = EventValidator::default();
        let result = validator.validate(&event);
        
        prop_assert!(result.is_ok(), "Generated event should pass validation: {:?}", result);
    }

    #[test]
    fn empty_source_fails_validation(
        event in empty_source_event()
    ) {
        // Property: Events with empty source should fail validation
        let validator = EventValidator::default();
        let result = validator.validate(&event);
        
        prop_assert!(result.is_err(), "Event with empty source should fail validation");
        if let Err(e) = result {
            prop_assert!(e.to_string().contains("source") || e.to_string().contains("empty"),
                        "Error should mention source issue: {}", e);
        }
    }

    #[test]
    fn event_field_constraints(
        source in "[a-z][a-z0-9_]{0,49}",
        event_type in "[a-z][a-z0-9_.]{0,99}",
        host in "[a-zA-Z0-9_.-]{1,255}",
        payload in event_payloads()
    ) {
        // Property: Events with valid field constraints should be constructible
        let event = sinex_events::EventFactory::new(&source)
            .create_event(&event_type, payload);
        
        prop_assert!(!event.source.is_empty());
        prop_assert!(!event.event_type.is_empty());
        prop_assert!(event.source.len() <= 50);
        prop_assert!(event.event_type.len() <= 100);
        prop_assert!(event.host.len() <= 255);
    }

    #[test]
    fn payload_size_validation(
        size_kb in 1usize..=10_000usize
    ) {
        // Property: Events should handle various payload sizes gracefully
        let large_data = "x".repeat(size_kb * 1024);
        let payload = json!({
            "data": large_data,
            "size_kb": size_kb
        });
        
        let event = sinex_events::EventFactory::new("test")
            .create_event("payload.size.test", payload);
        
        // Check that large payloads are handled
        let serialized = serde_json::to_string(&event);
        prop_assert!(serialized.is_ok(), "Should serialize large payload");
        
        // Verify size is roughly what we expect (with JSON overhead)
        if let Ok(json_str) = serialized {
            prop_assert!(json_str.len() > size_kb * 1024, "Serialized size should exceed payload size");
        }
    }

    #[test]
    fn event_timestamp_consistency(
        event in arbitrary_event()
    ) {
        // Property: Event timestamps should maintain consistency
        prop_assert!(event.ts_ingest >= event.ts_orig.unwrap_or(event.ts_ingest),
                    "Ingest time should not be before origin time");
        
        // If ts_orig exists, it should be reasonable
        if let Some(ts_orig) = event.ts_orig {
            let now = chrono::Utc::now();
            let diff = (now - ts_orig).num_days().abs();
            prop_assert!(diff < 365 * 100, "Timestamp should be within 100 years of now");
        }
    }

    #[test]
    fn ulid_properties_in_events(
        events in proptest::collection::vec(arbitrary_event(), 2..100)
    ) {
        // Property: ULIDs in events should maintain uniqueness and ordering
        let mut ulids: Vec<Ulid> = events.iter().map(|e| e.id).collect();
        
        // Check uniqueness
        let unique_ulids: std::collections::HashSet<_> = ulids.iter().cloned().collect();
        prop_assert_eq!(ulids.len(), unique_ulids.len(), "All event ULIDs should be unique");
        
        // Check that sorting by ULID gives chronological order (approximately)
        ulids.sort();
        for window in ulids.windows(2) {
            prop_assert!(window[0] <= window[1], "ULIDs should maintain sort order");
        }
    }

    #[test]
    fn source_event_id_validation(
        parent_events in proptest::collection::vec(arbitrary_ulid(), 0..10),
        event in arbitrary_event()
    ) {
        // Property: Source event IDs should be valid UUIDs
        let mut test_event = event;
        if !parent_events.is_empty() {
            test_event.source_event_ids = Some(parent_events.iter().map(|u| u.to_uuid()).collect());
        }
        
        if let Some(ref ids) = test_event.source_event_ids {
            for id in ids {
                // UUID should be valid (this is guaranteed by type system)
                prop_assert_eq!(id.get_version_num(), 4, "Should be UUID v4");
            }
        }
    }

    #[test]
    fn json_schema_compatibility(
        event in arbitrary_event()
    ) {
        // Property: Event payloads should be valid JSON that can be schema-validated
        let payload_str = serde_json::to_string(&event.payload);
        prop_assert!(payload_str.is_ok(), "Payload should serialize to JSON");
        
        if let Ok(json_str) = payload_str {
            let parsed: Result<Value, _> = serde_json::from_str(&json_str);
            prop_assert!(parsed.is_ok(), "Payload should round-trip through JSON");
        }
    }

    #[test]
    fn event_metadata_fields(
        event in metadata_rich_events()
    ) {
        // Property: Metadata-rich events should have expected optional fields
        if event.source_material_id.is_some() {
            // If material ID is set, offsets might also be set
            let has_offsets = event.source_material_offset_start.is_some() 
                || event.source_material_offset_end.is_some();
            
            // This is not a hard requirement but a common pattern
            prop_assert!(has_offsets || !has_offsets, "Offsets are optional with material ID");
        }
        
        // Check payload has metadata if it's an object
        if let Value::Object(ref map) = event.payload {
            if let Some(metadata) = map.get("_metadata") {
                prop_assert!(metadata.is_object(), "Metadata should be an object");
            }
        }
    }

    #[test]
    fn boundary_condition_handling(
        event in boundary_condition_events()
    ) {
        // Property: Boundary condition events should be processable
        let validator = EventValidator::default();
        
        // Even boundary cases should have valid structure
        prop_assert!(!event.source.is_empty(), "Source should not be empty");
        prop_assert!(!event.event_type.is_empty(), "Event type should not be empty");
        prop_assert_ne!(event.id, Ulid::nil(), "ID should not be nil");
        
        // Payload should be valid JSON
        let _ = serde_json::to_string(&event.payload)
            .expect("Boundary payload should be serializable");
    }
}

// Additional property tests for concurrent scenarios
#[cfg(feature = "concurrent_tests")]
mod concurrent_tests {
    use super::*;
    use std::sync::Arc;
    use tokio::sync::Mutex;
    
    proptest! {
        #[test]
        fn concurrent_event_ordering(
            events in concurrent_operation_events()
        ) {
            // Property: Concurrent events should maintain per-worker ordering
            let mut by_worker: std::collections::HashMap<usize, Vec<_>> = 
                std::collections::HashMap::new();
            
            for event in events {
                if let Value::Object(ref map) = event.payload {
                    if let (Some(Value::Number(worker_id)), Some(Value::Number(op_id))) = 
                        (map.get("worker_id"), map.get("operation_id")) {
                        let worker = worker_id.as_u64().unwrap() as usize;
                        let op = op_id.as_u64().unwrap();
                        by_worker.entry(worker).or_default().push(op);
                    }
                }
            }
            
            // Each worker's operations should be in order
            for (_, ops) in by_worker {
                for window in ops.windows(2) {
                    prop_assert!(window[0] <= window[1], 
                                "Worker operations should be ordered");
                }
            }
        }
    }
}

// Performance-related property tests
#[cfg(feature = "performance_tests")]
mod performance_tests {
    use super::*;
    use std::time::Instant;
    
    proptest! {
        #[test]
        fn event_creation_performance(
            events in performance_characteristic_events()
        ) {
            // Property: Event creation should complete in reasonable time
            let start = Instant::now();
            
            let serialized = serde_json::to_string(&events);
            
            let elapsed = start.elapsed();
            
            prop_assert!(serialized.is_ok(), "Should serialize performance test event");
            prop_assert!(elapsed.as_millis() < 100, 
                        "Serialization should complete within 100ms, took {}ms", 
                        elapsed.as_millis());
        }
    }
}