use sinex_test_utils::prelude::*;
use proptest::prelude::*;
// EventValidator doesn't exist, using ValidationChain instead
use sinex_validation::ValidationChain;
use sinex_types::ulid::Ulid;
use serde_json::Value;

proptest! {
    #![proptest_config(ProptestConfig::with_cases(1000))]

    #[sinex_test]
    fn valid_events_pass_validation(
        event in arbitrary_event()
    ) {
        // Property: All events generated by property builders should pass validation
        // Simple validation function for events
        let validate_event = |event: &RawEvent| -> Result<(), String> {
            if event.source.is_empty() {
                return Err("Empty source".to_string());
            }
            if event.event_type.is_empty() {
                return Err("Empty event_type".to_string());
            }
            Ok(())
        };
        let result = validate_event(&event);
        
        prop_assert!(result.is_ok(), "Generated event should pass validation: {:?}", result);
    }

    #[sinex_test]
    fn empty_source_fails_validation(
        event in empty_source_event()
    ) {
        // Property: Events with empty source should fail validation
        // Simple validation function for events
        let validate_event = |event: &RawEvent| -> Result<(), String> {
            if event.source.is_empty() {
                return Err("Empty source".to_string());
            }
            if event.event_type.is_empty() {
                return Err("Empty event_type".to_string());
            }
            Ok(())
        };
        let result = validate_event(&event);
        
        prop_assert!(result.is_err(), "Event with empty source should fail validation");
        if let Err(e) = result {
            prop_assert!(e.to_string().contains("source") || e.to_string().contains("empty"),
                        "Error should mention source issue: {}", e);
        }
    }

    #[sinex_test]
    fn event_field_constraints(
        source in "[a-z][a-z0-9_]{0,49}",
        event_type in "[a-z][a-z0-9_.]{0,99}",
        host in "[a-zA-Z0-9_.-]{1,255}",
        payload in event_payloads()
    ) {
        // Property: Events with valid field constraints should be constructible
        let event = sinex_events::EventFactory::new(&source)
            .create_event(&event_type, payload);
        
        prop_assert!(!event.source.is_empty());
        prop_assert!(!event.event_type.is_empty());
        prop_assert!(event.source.len() <= 50);
        prop_assert!(event.event_type.len() <= 100);
        prop_assert!(event.host.len() <= 255);
    }

    #[sinex_test]
    fn payload_size_validation(
        size_kb in 1usize..=10_000usize
    ) {
        // Property: Events should handle various payload sizes gracefully
        let large_data = "x".repeat(size_kb * 1024);
        let payload = json!({
            "data": large_data,
            "size_kb": size_kb
        });
        
        let event = sinex_events::EventFactory::new("test")
            .create_event("payload.size.test", payload);
        
        // Check that large payloads are handled
        let serialized = serde_json::to_string(&event);
        prop_assert!(serialized.is_ok(), "Should serialize large payload");
        
        // Verify size is roughly what we expect (with JSON overhead)
        if let Ok(json_str) = serialized {
            prop_assert!(json_str.len() > size_kb * 1024, "Serialized size should exceed payload size");
        }
    }

    #[sinex_test]
    fn event_timestamp_consistency(
        event in arbitrary_event()
    ) {
        // Property: Event timestamps should maintain consistency
        prop_assert!(event.ts_ingest >= event.ts_orig.unwrap_or(event.ts_ingest),
                    "Ingest time should not be before origin time");
        
        // If ts_orig exists, it should be reasonable
        if let Some(ts_orig) = event.ts_orig {
            let now = chrono::Utc::now();
            let diff = (now - ts_orig).num_days().abs();
            prop_assert!(diff < 365 * 100, "Timestamp should be within 100 years of now");
        }
    }

    #[sinex_test]
    fn ulid_properties_in_events(
        events in proptest::collection::vec(arbitrary_event(), 2..100)
    ) {
        // Property: ULIDs in events should maintain uniqueness and ordering
        let mut ulids: Vec<Ulid> = events.iter().map(|e| e.id).collect();
        
        // Check uniqueness
        let unique_ulids: std::collections::HashSet<_> = ulids.iter().cloned().collect();
        prop_assert_eq!(ulids.len(), unique_ulids.len(), "All event ULIDs should be unique");
        
        // Check that sorting by ULID gives chronological order (approximately)
        ulids.sort();
        for window in ulids.windows(2) {
            prop_assert!(window[0] <= window[1], "ULIDs should maintain sort order");
        }
    }

    #[sinex_test]
    fn source_event_id_validation(
        parent_events in proptest::collection::vec(crate::property::ulid_property_test::arbitrary_ulid(), 0..10),
        event in arbitrary_event()
    ) {
        // Property: Source event IDs should be valid UUIDs
        let mut test_event = event;
        if !parent_events.is_empty() {
            test_event.source_event_ids = Some(parent_events.clone());
        }
        
        if let Some(ref ids) = test_event.source_event_ids {
            for id in ids {
                // UUID should be valid (this is guaranteed by type system)
                // ULIDs don't have version numbers like UUIDs
                prop_assert!(!id.is_nil(), "ULID should not be nil");
            }
        }
    }

    #[sinex_test]
    fn json_schema_compatibility(
        event in arbitrary_event()
    ) {
        // Property: Event payloads should be valid JSON that can be schema-validated
        let payload_str = serde_json::to_string(&event.payload);
        prop_assert!(payload_str.is_ok(), "Payload should serialize to JSON");
        
        if let Ok(json_str) = payload_str {
            let parsed: Result<Value, _> = serde_json::from_str(&json_str);
            prop_assert!(parsed.is_ok(), "Payload should round-trip through JSON");
        }
    }

    #[sinex_test]
    fn event_metadata_fields(
        event in metadata_rich_events()
    ) {
        // Property: Metadata-rich events should have expected optional fields
        if event.source_material_id.is_some() {
            // If material ID is set, offsets might also be set
            let has_offsets = event.source_material_offset_start.is_some() 
                || event.source_material_offset_end.is_some();
            
            // This is not a hard requirement but a common pattern
            prop_assert!(has_offsets || !has_offsets, "Offsets are optional with material ID");
        }
        
        // Check payload has metadata if it's an object
        if let Value::Object(ref map) = event.payload {
            if let Some(metadata) = map.get("_metadata") {
                prop_assert!(metadata.is_object(), "Metadata should be an object");
            }
        }
    }

    #[sinex_test]
    fn boundary_condition_handling(
        event in boundary_condition_events()
    ) {
        // Property: Boundary condition events should be processable
        // Simple validation function for events
        let validate_event = |event: &RawEvent| -> Result<(), String> {
            if event.source.is_empty() {
                return Err("Empty source".to_string());
            }
            if event.event_type.is_empty() {
                return Err("Empty event_type".to_string());
            }
            Ok(())
        };
        
        // Even boundary cases should have valid structure
        prop_assert!(!event.source.is_empty(), "Source should not be empty");
        prop_assert!(!event.event_type.is_empty(), "Event type should not be empty");
        prop_assert_ne!(event.id, Ulid::nil(), "ID should not be nil");
        
        // Payload should be valid JSON
        let _ = serde_json::to_string(&event.payload)
            .expect("Boundary payload should be serializable");
    }
}

// Additional property tests for concurrent scenarios
#[cfg(feature = "concurrent_tests")]
mod concurrent_tests {
    use super::*;
    use std::sync::Arc;
    use tokio::sync::Mutex;
    
    proptest! {
        #[sinex_test]
        fn concurrent_event_ordering(
            events in concurrent_operation_events()
        ) {
            // Property: Concurrent events should maintain per-worker ordering
            let mut by_worker: std::collections::HashMap<usize, Vec<_>> = 
                std::collections::HashMap::new();
            
            for event in events {
                if let Value::Object(ref map) = event.payload {
                    if let (Some(Value::Number(worker_id)), Some(Value::Number(op_id))) = 
                        (map.get("worker_id"), map.get("operation_id")) {
                        let worker = worker_id.as_u64().unwrap() as usize;
                        let op = op_id.as_u64().unwrap();
                        by_worker.entry(worker).or_default().push(op);
                    }
                }
            }
            
            // Each worker's operations should be in order
            for (_, ops) in by_worker {
                for window in ops.windows(2) {
                    prop_assert!(window[0] <= window[1], 
                                "Worker operations should be ordered");
                }
            }
        }
    }
}

// Performance-related property tests
#[cfg(feature = "performance_tests")]
mod performance_tests {
    use super::*;
    use std::time::Instant;
    
    proptest! {
        #[sinex_test]
        fn event_creation_performance(
            events in performance_characteristic_events()
        ) {
            // Property: Event creation should complete in reasonable time
            let start = Instant::now();
            
            let serialized = serde_json::to_string(&events);
            
            let elapsed = start.elapsed();
            
            prop_assert!(serialized.is_ok(), "Should serialize performance test event");
            prop_assert!(elapsed.as_millis() < 100, 
                        "Serialization should complete within 100ms, took {}ms", 
                        elapsed.as_millis());
        }
    }
    
    proptest! {
        #[sinex_test]
        fn validation_errors_are_deterministic(
            source in "[a-z]*", // May be empty
            event_type in "[a-z]*", // May be empty
            payload in arbitrary_json_value()
        ) {
        // Property: Same invalid input should always produce same error
        if source.is_empty() || event_type.is_empty() {
            use sinex_db::models::EventFactory;
            let factory = EventFactory::new(&source);
            let event1 = factory.create_event(&event_type, payload.clone());
            let event2 = factory.create_event(&event_type, payload);
            
            // Simple validation function for events
        let validate_event = |event: &RawEvent| -> Result<(), String> {
            if event.source.is_empty() {
                return Err("Empty source".to_string());
            }
            if event.event_type.is_empty() {
                return Err("Empty event_type".to_string());
            }
            Ok(())
        };
            let result1 = validate_event(&event1);
            let result2 = validate_event(&event2);
            
            // Both should fail with similar errors
            prop_assert!(result1.is_err() && result2.is_err());
            
            // Error messages should be consistent
            if let (Err(e1), Err(e2)) = (result1, result2) {
                let msg1 = e1.to_string();
                let msg2 = e2.to_string();
                prop_assert_eq!(msg1, msg2, "Validation errors should be deterministic");
            }
        }

        #[sinex_test]
        fn validation_preserves_error_hierarchy(
            event in arbitrary_event()
        ) {
        // Property: Validation errors should preserve proper error hierarchy
        // Simple validation function for events
        let validate_event = |event: &RawEvent| -> Result<(), String> {
            if event.source.is_empty() {
                return Err("Empty source".to_string());
            }
            if event.event_type.is_empty() {
                return Err("Empty event_type".to_string());
            }
            Ok(())
        };
        let result = validate_event(&event);
        
        if let Err(error) = result {
            let error_string = error.to_string();
            
            // Error should contain contextual information
            prop_assert!(!error_string.is_empty(), "Error message should not be empty");
            
            // Error should be structured (contain field information if validation failed)
            if event.source.is_empty() {
                prop_assert!(error_string.contains("source"), 
                           "Empty source error should mention 'source': {}", error_string);
            }
            if event.event_type.is_empty() {
                prop_assert!(error_string.contains("event_type") || error_string.contains("type"), 
                           "Empty event_type error should mention type: {}", error_string);
            }
        }
    }
    } // End of proptest! block
}

// Helper function for property tests
fn arbitrary_json_value() -> impl Strategy<Value = serde_json::Value> {
    prop_oneof![
        Just(serde_json::json!(null)),
        Just(serde_json::json!({})),
        Just(serde_json::json!([])),
        Just(serde_json::json!("string")),
        Just(serde_json::json!(42)),
        Just(serde_json::json!(true)),
        Just(serde_json::json!({"field": "value"})),
        Just(serde_json::json!([1, 2, 3])),
    ]
}

// === ENHANCED VALIDATION ERROR TESTS USING ERROR MACROS ===

// Test empty source validation failure using test_validation_error! macro
test_validation_error!(
    test_empty_source_validation_error,
    "source",
    "",
    "source"
);

// Test empty event_type validation failure
test_validation_error!(
    test_empty_event_type_validation_error,
    "event_type", 
    "",
    "event_type"
);

// Test invalid payload validation failure
test_validation_error!(
    test_invalid_payload_validation_error,
    "payload",
    serde_json::json!({"invalid": "structure that doesn't match schema"}),
    "schema"
);

// === CONCURRENT VALIDATION ERROR TESTS ===

// Test concurrent validation errors using test_concurrent_errors! macro
test_concurrent_errors!(
    test_concurrent_validation_failures,
    5,
    |pool, task_id| async move {
        use sinex_db::models::EventFactory;
        let factory = EventFactory::new("");
        let invalid_event = factory.create_event("invalid.type", serde_json::json!(null));
        
        // Simple validation function for events
        let validate_event = |event: &RawEvent| -> Result<(), String> {
            if event.source.is_empty() {
                return Err("Empty source".to_string());
            }
            if event.event_type.is_empty() {
                return Err("Empty event_type".to_string());
            }
            Ok(())
        };
        validate_event(&invalid_event)
            .map_err(|e| Box::new(e) as Box<dyn std::error::Error + Send + Sync>)
    },
    5 // Expected all 5 to fail
);

// === CONSTRAINT VIOLATION TESTS ===

// Test database constraint violations using test_constraint_violation! macro
test_constraint_violation!(
    test_unique_constraint_violation,
    |pool| async move {
        // Setup: Insert an event first
        // This test is broken - needs TestContext to insert events
        // let event = TestEventBuilder::new("test", "constraint.test")
        //     .with_payload(serde_json::json!({"test": true}))
        //     .insert(pool)
        //     .await?;
        let event_id = sinex_ulid::Ulid::new();
        Ok(event.id)
    },
    |pool, event_id| async move {
        // Violating operation: Try to insert event with same ID
        let duplicate_event = sinex_db::RawEvent {
            id: event_id,
            source: "test".to_string(),
            event_type: "constraint.test".to_string(),
            ts_ingest: chrono::Utc::now(),
            ts_orig: None,
            host: "test-host".to_string(),
            ingestor_version: None,
            payload_schema_id: None,
            payload: serde_json::json!({"duplicate": true}),
            source_event_ids: None,
            source_material_id: None,
            source_material_offset_start: None,
            source_material_offset_end: None,
            anchor_byte: None,
            associated_blob_ids: None,
        };
        
        sinex_db::insert_event_with_validator(pool, &duplicate_event, None).await
            .map_err(|e| Box::new(e) as Box<dyn std::error::Error + Send + Sync>)
    },
    "unique_constraint"
);

// === ERROR RECOVERY TESTS ===

// Test validation error recovery using test_recovery! macro
test_recovery!(
    test_validation_error_recovery,
    |pool| async move {
        // Failing operation: Insert invalid event
        // This test is broken - needs proper error handling
        Err(Box::new(CoreError::validation("Test broken - missing error_helpers".to_string())) as Box<dyn std::error::Error + Send + Sync>)
    },
    |pool| async move {
        // Recovery operation: Insert valid event
        // This test is broken - needs TestContext
        let valid_event_id = sinex_ulid::Ulid::new();
        Ok(valid_event.id)
    }
);

// === PARTIAL FAILURE TESTS ===

// Test partial validation failures in batches using test_partial_failure! macro
test_partial_failure!(
    test_batch_validation_partial_failure,
    |pool| async move {
        // Batch operation: Mix of valid and invalid events
        let events = vec![
            // Valid events
            {
                let factory = EventFactory::new("batch");
                factory.create_event("valid.event1", serde_json::json!({"valid": 1}))
            },
            {
                let factory = EventFactory::new("batch");
                factory.create_event("valid.event2", serde_json::json!({"valid": 2}))
            },
            {
                let factory = EventFactory::new("batch");
                factory.create_event("valid.event3", serde_json::json!({"valid": 3}))
            },
            // Invalid events
            {
                let factory = EventFactory::new("");
                factory.create_event("invalid.event1", serde_json::json!(null))
            },
            {
                let factory = EventFactory::new("batch");
                factory.create_event("", serde_json::json!({"invalid": true}))
            },
        ];
        
        let mut results = Vec::new();
        for event in events {
            let result = sinex_db::insert_event_with_validator(pool, &event, None).await;
            results.push(result);
        }
        
        Ok(results)
    },
    3, // Expected successes
    2  // Expected failures
);

// === ERROR CONTEXT PRESERVATION TESTS ===

// Test error context preservation using test_error_context! macro
test_error_context!(
    test_validation_error_context,
    |pool| async move {
        // This test is broken - needs proper error handling  
        Err(Box::new(CoreError::validation("Test broken - missing error_helpers".to_string())) as Box<dyn std::error::Error + Send + Sync>)
    },
    vec!["event_type", "validation", "context"]
);}
