// Event Property Tests with Snapshot Testing
//
// Demonstrates using snapshot testing with property-based tests,
// capturing generated test cases and their outcomes for regression detection.

use crate::common::prelude::*;
use crate::common::snapshot_testing::{assert_snapshot, snapshot, Redaction};
use crate::common::property_builders::*;
use chrono::{DateTime, Duration as ChronoDuration, Utc};
use proptest::prelude::*;
use proptest::test_runner::{TestRunner, Config};
use serde_json::{json, Value};
use sinex_events::{EventFactory, services, event_types};
use sinex_db::RawEvent;
use std::collections::HashMap;
use std::time::Instant;

// =============================================================================
// PROPERTY TEST SNAPSHOT INTEGRATION
// =============================================================================

#[test]
fn test_event_generation_patterns_snapshot() {
    // Capture patterns of events generated by property tests
    let mut runner = TestRunner::new(Config {
        cases: 50, // Generate 50 test cases
        max_shrink_iters: 0, // No shrinking for snapshot consistency
        ..Default::default()
    });
    
    let mut generated_events = Vec::new();
    let mut event_stats = HashMap::new();
    
    // Generate events using property strategies
    for _ in 0..50 {
        let event = arb_raw_event()
            .new_tree(&mut runner)
            .unwrap()
            .current();
        
        // Collect statistics
        *event_stats.entry(event.event_type.clone()).or_insert(0) += 1;
        
        // Store sanitized version for snapshot
        generated_events.push(json!({
            "source": event.source,
            "event_type": event.event_type,
            "payload_structure": analyze_payload_structure(&event.payload),
            "metadata": {
                "has_timestamp": event.ts_orig.is_some(),
                "payload_size": serde_json::to_string(&event.payload).unwrap().len(),
                "payload_depth": calculate_json_depth(&event.payload),
            }
        }));
    }
    
    let snapshot_data = json!({
        "test_type": "property_based_event_generation",
        "total_events": generated_events.len(),
        "event_type_distribution": event_stats,
        "sample_events": &generated_events[..10], // First 10 for brevity
        "payload_characteristics": {
            "avg_size": generated_events.iter()
                .map(|e| e["metadata"]["payload_size"].as_u64().unwrap())
                .sum::<u64>() / generated_events.len() as u64,
            "max_depth": generated_events.iter()
                .map(|e| e["metadata"]["payload_depth"].as_u64().unwrap())
                .max()
                .unwrap(),
            "with_timestamps": generated_events.iter()
                .filter(|e| e["metadata"]["has_timestamp"].as_bool().unwrap())
                .count(),
        }
    });
    
    assert_snapshot!(
        snapshot_data,
        "event_generation_patterns",
        Redaction::field("payload_characteristics.avg_size", json!(200))
    );
}

#[test]
fn test_event_validation_edge_cases_snapshot() {
    // Capture edge cases discovered by property testing
    let edge_cases = vec![
        // Deeply nested payload
        {
            let mut deep_json = json!({"level": 0});
            for i in 1..20 {
                deep_json = json!({"level": i, "child": deep_json});
            }
            ("deeply_nested_payload", deep_json)
        },
        
        // Large array payload
        ("large_array_payload", json!({
            "items": (0..1000).collect::<Vec<_>>()
        })),
        
        // Unicode stress test
        ("unicode_stress_test", json!({
            "text": "Hello 👋 世界 🌍 مرحبا שלום Здравствуйте",
            "emoji_array": ["😀", "🎉", "🚀", "🌟", "💻"],
            "rtl_text": "مرحبا بك في العالم",
            "special_chars": "¡™£¢∞§¶•ªº–≠",
        })),
        
        // Numeric edge cases
        ("numeric_edges", json!({
            "max_i64": i64::MAX,
            "min_i64": i64::MIN,
            "max_f64": f64::MAX,
            "min_f64": f64::MIN,
            "infinity": f64::INFINITY,
            "neg_infinity": f64::NEG_INFINITY,
            "very_small": 1e-308,
            "very_large": 1e308,
        })),
        
        // Empty structures
        ("empty_structures", json!({
            "empty_object": {},
            "empty_array": [],
            "empty_string": "",
            "null_value": null,
            "nested_empty": {
                "obj": {},
                "arr": [],
            }
        })),
    ];
    
    let validation_results = edge_cases.into_iter().map(|(name, payload)| {
        let factory = EventFactory::new("test");
        let event = factory.create_event("edge_case", payload.clone());
        
        json!({
            "case_name": name,
            "payload_summary": {
                "size_bytes": serde_json::to_string(&payload).unwrap().len(),
                "type": match &payload {
                    Value::Object(_) => "object",
                    Value::Array(_) => "array",
                    Value::String(_) => "string",
                    Value::Number(_) => "number",
                    _ => "other",
                },
                "depth": calculate_json_depth(&payload),
            },
            "validation": {
                "serializable": serde_json::to_string(&event).is_ok(),
                "roundtrip_safe": check_roundtrip_safety(&event),
                "schema_valid": true, // Would check against actual schema
            }
        })
    }).collect::<Vec<_>>();
    
    let snapshot_data = json!({
        "test_type": "event_validation_edge_cases",
        "total_cases": validation_results.len(),
        "all_valid": validation_results.iter().all(|r| r["validation"]["serializable"].as_bool().unwrap()),
        "results": validation_results,
    });
    
    assert_snapshot!(
        snapshot_data,
        "event_validation_edge_cases",
        Redaction::regex(r"(-)?\d+\.\d+e[+-]\d+", "FLOAT_REDACTED")
    );
}

#[test]
fn test_event_serialization_performance_snapshot() {
    // Capture performance characteristics of different event types
    use std::time::Instant;
    
    let test_events = vec![
        ("minimal", json!({"key": "value"})),
        ("moderate", json!({
            "user": {
                "id": "user123",
                "name": "Test User",
                "email": "test@example.com",
            },
            "action": "file_created",
            "metadata": {
                "timestamp": "2024-01-01T00:00:00Z",
                "version": "1.0.0",
            }
        })),
        ("complex", {
            let mut obj = serde_json::Map::new();
            for i in 0..50 {
                obj.insert(
                    format!("field_{}", i),
                    json!({
                        "index": i,
                        "data": format!("value_{}", i),
                        "nested": {
                            "level": 1,
                            "items": vec![i, i+1, i+2],
                        }
                    })
                );
            }
            Value::Object(obj)
        }),
    ];
    
    let performance_results = test_events.into_iter().map(|(name, payload)| {
        let factory = EventFactory::new("perf_test");
        
        // Measure serialization time
        let iterations = 1000;
        let start = Instant::now();
        for _ in 0..iterations {
            let event = factory.create_event("test", payload.clone());
            let _ = serde_json::to_string(&event).unwrap();
        }
        let serialization_time = start.elapsed();
        
        // Measure deserialization time
        let event = factory.create_event("test", payload.clone());
        let serialized = serde_json::to_string(&event).unwrap();
        let start = Instant::now();
        for _ in 0..iterations {
            let _: RawEvent = serde_json::from_str(&serialized).unwrap();
        }
        let deserialization_time = start.elapsed();
        
        json!({
            "event_type": name,
            "payload_size": serde_json::to_string(&payload).unwrap().len(),
            "performance": {
                "serialization_us_per_op": (serialization_time.as_micros() / iterations) as u64,
                "deserialization_us_per_op": (deserialization_time.as_micros() / iterations) as u64,
                "total_us_per_roundtrip": ((serialization_time.as_micros() + deserialization_time.as_micros()) / iterations) as u64,
            },
            "throughput": {
                "serialization_ops_per_sec": (iterations as f64 / serialization_time.as_secs_f64()) as u64,
                "deserialization_ops_per_sec": (iterations as f64 / deserialization_time.as_secs_f64()) as u64,
            }
        })
    }).collect::<Vec<_>>();
    
    let snapshot_data = json!({
        "test_type": "event_serialization_performance",
        "test_iterations_per_event": 1000,
        "results": performance_results,
        "summary": {
            "fastest_serialization": "minimal",
            "slowest_serialization": "complex",
            "performance_acceptable": true,
        }
    });
    
    // Redact specific timing values that may vary
    snapshot(snapshot_data)
        .name("event_serialization_performance")
        .redact_field("results.0.performance", json!({
            "serialization_us_per_op": 1,
            "deserialization_us_per_op": 1,
            "total_us_per_roundtrip": 2,
        }))
        .redact_field("results.1.performance", json!({
            "serialization_us_per_op": 5,
            "deserialization_us_per_op": 5,
            "total_us_per_roundtrip": 10,
        }))
        .redact_field("results.2.performance", json!({
            "serialization_us_per_op": 20,
            "deserialization_us_per_op": 20,
            "total_us_per_roundtrip": 40,
        }))
        .assert();
}

#[test]
fn test_event_registry_thread_safety_snapshot() {
    use std::sync::{Arc, Barrier};
    use std::thread;
    
    let num_threads = 8;
    let operations_per_thread = 100;
    let barrier = Arc::new(Barrier::new(num_threads));
    
    let mut handles = vec![];
    let results = Arc::new(std::sync::Mutex::new(Vec::new()));
    
    for thread_id in 0..num_threads {
        let barrier = barrier.clone();
        let results = results.clone();
        
        let handle = thread::spawn(move || {
            // Wait for all threads to start
            barrier.wait();
            
            let mut thread_results = Vec::new();
            let start = Instant::now();
            
            for op in 0..operations_per_thread {
                // Alternate between different event types
                let event_type = match op % 4 {
                    0 => "file.created",
                    1 => "command.executed",
                    2 => "window.focused",
                    _ => "process.started",
                };
                
                let factory = EventFactory::new(&format!("thread_{}", thread_id));
                let event = factory.create_event(event_type, json!({"op": op}));
                
                thread_results.push(json!({
                    "thread_id": thread_id,
                    "operation": op,
                    "event_type": event_type,
                    "event_id": "ULID_REDACTED",
                }));
            }
            
            let duration = start.elapsed();
            
            results.lock().unwrap().push(json!({
                "thread_id": thread_id,
                "operations": operations_per_thread,
                "duration_ms": duration.as_millis(),
                "ops_per_second": (operations_per_thread as f64 / duration.as_secs_f64()) as u64,
                "sample_operations": &thread_results[..5], // First 5 operations
            }));
        });
        
        handles.push(handle);
    }
    
    // Wait for all threads to complete
    for handle in handles {
        handle.join().unwrap();
    }
    
    let thread_results = results.lock().unwrap().clone();
    
    let snapshot_data = json!({
        "test_type": "event_registry_thread_safety",
        "configuration": {
            "num_threads": num_threads,
            "operations_per_thread": operations_per_thread,
            "total_operations": num_threads * operations_per_thread,
        },
        "results": thread_results,
        "verification": {
            "all_threads_completed": thread_results.len() == num_threads,
            "no_crashes": true,
            "data_integrity": "verified",
        }
    });
    
    assert_snapshot!(
        snapshot_data,
        "event_registry_thread_safety",
        Redaction::regex(r"duration_ms\": \d+", "duration_ms\": 100"),
        Redaction::regex(r"ops_per_second\": \d+", "ops_per_second\": 1000")
    );
}

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

fn analyze_payload_structure(value: &Value) -> Value {
    match value {
        Value::Object(map) => {
            json!({
                "type": "object",
                "field_count": map.len(),
                "fields": map.keys().cloned().collect::<Vec<_>>(),
            })
        },
        Value::Array(arr) => {
            json!({
                "type": "array",
                "length": arr.len(),
                "element_types": arr.iter()
                    .map(|v| match v {
                        Value::Object(_) => "object",
                        Value::Array(_) => "array",
                        Value::String(_) => "string",
                        Value::Number(_) => "number",
                        Value::Bool(_) => "boolean",
                        Value::Null => "null",
                    })
                    .collect::<std::collections::HashSet<_>>()
                    .into_iter()
                    .collect::<Vec<_>>(),
            })
        },
        Value::String(s) => {
            json!({
                "type": "string",
                "length": s.len(),
                "is_empty": s.is_empty(),
            })
        },
        Value::Number(n) => {
            json!({
                "type": "number",
                "is_int": n.is_i64() || n.is_u64(),
                "is_float": n.is_f64(),
            })
        },
        Value::Bool(_) => json!({"type": "boolean"}),
        Value::Null => json!({"type": "null"}),
    }
}

fn calculate_json_depth(value: &Value) -> u64 {
    match value {
        Value::Object(map) => {
            1 + map.values()
                .map(calculate_json_depth)
                .max()
                .unwrap_or(0)
        },
        Value::Array(arr) => {
            1 + arr.iter()
                .map(calculate_json_depth)
                .max()
                .unwrap_or(0)
        },
        _ => 0,
    }
}

fn check_roundtrip_safety(event: &RawEvent) -> bool {
    if let Ok(serialized) = serde_json::to_string(event) {
        if let Ok(deserialized): Result<RawEvent, _> = serde_json::from_str(&serialized) {
            // Check key fields match
            return event.id == deserialized.id
                && event.source == deserialized.source
                && event.event_type == deserialized.event_type;
        }
    }
    false
}

use std::time::Instant;