//! `terminal.atuin-history` — Atuin `SQLite` history source.
//!
//! Pilot for `#[derive(SourceDefinition)]` (#1727, SNX-41). One annotated
//! struct ([`AtuinHistoryRecord`]) replaces the four hand-wired, string-cross-
//! referenced registration sites a source author used to maintain:
//!
//!   1. the `SourceContract` (semantic identity),
//!   2. the `SourceRuntimeBinding` (deployment shape),
//!   3. the `register_source!` adapter + parser factory wiring,
//!   4. the `impl MaterialParser`.
//!
//! Adapter: [`SqliteRowAdapter`](crate::runtime::parser::SqliteRowAdapter) —
//! reads from `~/.local/share/atuin/history.db`.
//!
//! Field-level privacy hints are declared inline via `#[privacy(...)]`; they
//! are exported through the parser manifest for the DB/user policy layer and
//! never auto-act (#1611).
//!
//! # Migration note (#1727 slice 1 follow-up, resolved by #1750)
//!
//! The previous imperative `AtuinHistoryParser` performed validations the
//! declarative DSL v1 could not express. Those are now restored as declarative
//! field hooks (#1750):
//!   - `#[transform(split_first = ":")]` on `hostname` recovers the
//!     `host:user` → `host` normalization (`normalize_atuin_hostname`).
//!   - `#[validate(timestamp_nanos)]` on `timestamp` recovers the nanosecond
//!     range check.
//!   - `#[validate(i32)]` on `exit_code` recovers the exit-code narrowing
//!     check.

use sinex_macros::SourceDefinition;
use sinex_primitives::privacy::ProcessingContext;
use sinex_primitives::source_contracts::{
    AccessScope, CheckpointFamily, Horizon, OccurrenceIdentity, PrivacyTier, ResourceProfile,
    RetentionPolicy, RunnerPack, RuntimeShape,
};

/// Declarative Atuin history source definition.
///
/// Field names are the emitted payload keys; `#[source(column_name = …)]` maps
/// each to the corresponding `history` table column (the adapter expands
/// `query = "history"` to `SELECT rowid, * FROM history`).
// `Default` is generated by the `SourceDefinition` derive (the struct is a
// parser marker), so it is intentionally absent from this derive list.
#[derive(SourceDefinition, Debug, Clone)]
#[source_definition(
    id = "terminal.atuin-history",
    namespace = "terminal",
    event_source = "shell.atuin",
    event_type = "command.executed",
    input_shape = "sqlite_row",
    adapter = "SqliteRowAdapter",
    default_privacy_context = "Command",
    privacy_tier = PrivacyTier::Sensitive,
    horizons(Horizon::Continuous, Horizon::Historical),
    retention = RetentionPolicy::Forever,
    occurrence_identity = OccurrenceIdentity::Natural,
    access_scope = AccessScope::TargetHome { path: ".local/share/atuin/history.db" },
    implementation = "sinexd",
    privacy_context = ProcessingContext::Command,
    resource_profile = ResourceProfile::BoundedStream,
    runner_pack = RunnerPack::SinexdSource,
    checkpoint_family = CheckpointFamily::MutableSnapshot { backing_store_kind: "sqlite", occurrence_anchor: "atuin_history_id" },
    runtime_shape = RuntimeShape::Continuous,
    baseline_adapter_config = r#"{"query":"history","table":"history"}"#
)]
pub struct AtuinHistoryRecord {
    /// `SQLite` rowid — occurrence anchor (excluded from the emitted payload).
    #[source(column_name = "rowid")]
    #[occurrence_key]
    #[skip]
    pub rowid: i64,

    /// Command start time, unix nanoseconds.
    #[source(column_name = "timestamp")]
    #[timestamp(format = "unix_seconds_nanos", fallback = "material_timing")]
    #[validate(timestamp_nanos)]
    pub timestamp: i64,

    /// Executed command line.
    #[source(column_name = "command")]
    #[privacy(context = "Command")]
    #[privacy(sensitivity = "free_text, credential_bearing")]
    pub command_string: String,

    /// Working directory.
    #[source(column_name = "cwd")]
    #[privacy(sensitivity = "source_path")]
    pub cwd: String,

    /// Process exit code (defaults to 0 when absent).
    #[source(column_name = "exit")]
    #[default = "0"]
    #[validate(i32)]
    pub exit_code: i64,

    /// Command duration in nanoseconds (defaults to 0 when absent).
    #[source(column_name = "duration")]
    #[default = "0"]
    pub duration_ns: i64,

    /// Atuin history row id.
    #[source(column_name = "id")]
    pub atuin_history_id: String,

    /// Atuin session id.
    #[source(column_name = "session")]
    pub atuin_session_id: String,

    /// Originating hostname. Atuin stores `host:user`; the `split_first`
    /// transform collapses it to the host segment (#1750).
    #[source(column_name = "hostname")]
    #[transform(split_first = ":")]
    pub hostname: String,
}

#[cfg(test)]
mod tests {
    use super::*;
    use sinex_primitives::Id;
    use sinex_primitives::parser::{
        BindingConfig, DeclarativeParser, MaterialAnchor, ParserContext, ParserError, SourceId,
        SourceRecord,
    };
    use sinex_primitives::temporal::Timestamp;
    use xtask::sandbox::prelude::*;

    fn ctx() -> ParserContext {
        ParserContext {
            source_id: SourceId::from_static("terminal.atuin-history"),
            source_material_id: Id::from_uuid(uuid::Uuid::nil()),
            record_anchor: MaterialAnchor::SqliteRow {
                table: "history".into(),
                rowid: 1,
            },
            operation_id: uuid::Uuid::nil(),
            job_id: uuid::Uuid::nil(),
            host: "test-host".into(),
            acquisition_time: Timestamp::now(),
        }
    }

    fn record(json: &str) -> SourceRecord {
        SourceRecord {
            material_id: Id::from_uuid(uuid::Uuid::nil()),
            anchor: MaterialAnchor::SqliteRow {
                table: "history".into(),
                rowid: 1,
            },
            bytes: json.as_bytes().to_vec(),
            logical_path: None,
            source_ts_hint: None,
            metadata: serde_json::Value::Null,
        }
    }

    /// Atuin parity (#1750): `host:user` hostname is normalized to the host
    /// segment via the declarative `split_first` transform.
    #[sinex_test]
    async fn hostname_is_normalized_to_host_segment() -> TestResult<()> {
        let row = r#"{
            "rowid": 1,
            "timestamp": 1700000000000000000,
            "command": "ls -la",
            "cwd": "/home/me",
            "exit": 0,
            "duration": 1000,
            "id": "atuin-id-1",
            "session": "session-1",
            "hostname": "myhost:myuser"
        }"#;
        let intents = DeclarativeParser::evaluate(
            AtuinHistoryRecord::parser_spec(),
            &record(row),
            &ctx(),
            &BindingConfig::default(),
        )?;
        assert_eq!(intents.len(), 1);
        assert_eq!(intents[0].payload["hostname"], "myhost");
        // rowid is the occurrence anchor (skipped from payload).
        assert!(intents[0].payload.get("rowid").is_none());
        Ok(())
    }

    /// Atuin parity (#1750): an exit code outside `i32` range is rejected by
    /// the declarative `validate(i32)` hook.
    #[sinex_test]
    async fn out_of_range_exit_code_is_rejected() -> TestResult<()> {
        let row = r#"{
            "rowid": 2,
            "timestamp": 1700000000000000000,
            "command": "true",
            "cwd": "/home/me",
            "exit": 9999999999,
            "duration": 1000,
            "id": "atuin-id-2",
            "session": "session-1",
            "hostname": "myhost"
        }"#;
        let result = DeclarativeParser::evaluate(
            AtuinHistoryRecord::parser_spec(),
            &record(row),
            &ctx(),
            &BindingConfig::default(),
        );
        assert!(matches!(result, Err(ParserError::Field(_))));
        Ok(())
    }
}
