//! `terminal.atuin-history` — Atuin `SQLite` history source.
//!
//! Pilot for `#[derive(SourceDefinition)]` (#1727, SNX-41). One annotated
//! struct ([`AtuinHistoryRecord`]) replaces the four hand-wired, string-cross-
//! referenced registration sites a source author used to maintain:
//!
//!   1. the `SourceContract` (semantic identity),
//!   2. the `SourceRuntimeBinding` (deployment shape),
//!   3. the `register_source!` adapter + parser factory wiring,
//!   4. the `impl MaterialParser`.
//!
//! Adapter: [`SqliteRowAdapter`](crate::runtime::parser::SqliteRowAdapter) —
//! reads from `~/.local/share/atuin/history.db`.
//!
//! Field-level privacy hints are declared inline via `#[privacy(...)]`; they
//! are exported through the parser manifest for the DB/user policy layer and
//! never auto-act (#1611).
//!
//! # Migration note (#1727 slice 1 follow-up)
//!
//! The previous imperative `AtuinHistoryParser` performed two validations the
//! declarative DSL v1 cannot yet express: `host:user` hostname normalization
//! and timestamp range checks. Under the declarative parser these become
//! runtime concerns rather than typed-at-construction checks. Restoring them as
//! declarative validation hooks is tracked as a follow-up referenced from the
//! source-definition PR.

use sinex_macros::SourceDefinition;

/// Declarative Atuin history source definition.
///
/// Field names are the emitted payload keys; `#[source(column_name = …)]` maps
/// each to the corresponding `history` table column (the adapter expands
/// `query = "history"` to `SELECT rowid, * FROM history`).
// `Default` is generated by the `SourceDefinition` derive (the struct is a
// parser marker), so it is intentionally absent from this derive list.
#[derive(SourceDefinition, Debug, Clone)]
#[source_definition(
    id = "terminal.atuin-history",
    namespace = "terminal",
    event_source = "shell.atuin",
    event_type = "command.executed",
    input_shape = "sqlite_row",
    adapter = "SqliteRowAdapter",
    default_privacy_context = "Command",
    privacy_tier = "Sensitive",
    horizons = "continuous, historical",
    retention = "forever",
    occurrence_identity = "natural",
    access_policy = "target_home_read:.local/share/atuin/history.db",
    implementation = "sinexd",
    privacy_context = "Command",
    material_policy = "sqlite_row_id",
    checkpoint_policy = "mutable_snapshot",
    resource_shape = "linear_rows_bounded_memory",
    runner_pack = "sinexd-source",
    checkpoint_family = "mutable_snapshot:sqlite:atuin_history_id",
    runtime_shape = "continuous",
    package_impact = "atuin_history_source",
    implementation_mode = "sinexd:source",
    baseline_adapter_config = r#"{"query":"history","table":"history"}"#
)]
pub struct AtuinHistoryRecord {
    /// `SQLite` rowid — occurrence anchor (excluded from the emitted payload).
    #[source(column_name = "rowid")]
    #[occurrence_key]
    #[skip]
    pub rowid: i64,

    /// Command start time, unix nanoseconds.
    #[source(column_name = "timestamp")]
    #[timestamp(format = "unix_seconds_nanos", fallback = "material_timing")]
    pub timestamp: i64,

    /// Executed command line.
    #[source(column_name = "command")]
    #[privacy(context = "Command")]
    #[privacy(sensitivity = "free_text, credential_bearing")]
    pub command_string: String,

    /// Working directory.
    #[source(column_name = "cwd")]
    #[privacy(sensitivity = "source_path")]
    pub cwd: String,

    /// Process exit code (defaults to 0 when absent).
    #[source(column_name = "exit")]
    #[default = "0"]
    pub exit_code: i64,

    /// Command duration in nanoseconds (defaults to 0 when absent).
    #[source(column_name = "duration")]
    #[default = "0"]
    pub duration_ns: i64,

    /// Atuin history row id.
    #[source(column_name = "id")]
    pub atuin_history_id: String,

    /// Atuin session id.
    #[source(column_name = "session")]
    pub atuin_session_id: String,

    /// Originating hostname (`host:user` form; not normalized in DSL v1).
    #[source(column_name = "hostname")]
    pub hostname: String,
}
