//! `terminal.fish-history` — fish shell `SQLite` history source.
//!
//! Migrated to `#[derive(SourceDefinition)]` as part of #1727 slice 2.
//! Replaces the imperative `FishHistoryParser` — the four manual registration
//! sites (SourceContract, SourceRuntimeBinding, `register_source!`,
//! `impl MaterialParser`) collapse into the annotated [`FishHistoryRecord`]
//! struct.
//!
//! Adapter: [`SqliteRowAdapter`](crate::runtime::parser::SqliteRowAdapter) —
//! reads from `~/.local/share/fish/fish_history` (table `fish_history`).
//!
//! The original parser returned `HistoryCommandImportedPayload`; the
//! declarative struct emits its own field set as the payload (pre-release,
//! no production events — payload-shape change is acceptable).
//! Preserved exactly: occurrence identity (natural / rowid anchor),
//! `when` unix-seconds timestamp with `material_timing` fallback, and
//! `Command` privacy context.

use sinex_macros::SourceDefinition;

/// Declarative fish shell history source definition.
///
/// Each row from the `fish_history` SQLite table becomes one
/// `shell.history / command.imported` event. The SQLite `rowid` is the
/// natural occurrence anchor (excluded from the payload).
// `Default` is generated by `SourceDefinition`; absent from the derive list
// intentionally (see atuin_history.rs for the same note).
#[derive(SourceDefinition, Debug, Clone)]
#[source_definition(
    id = "terminal.fish-history",
    namespace = "terminal",
    event_source = "shell.history",
    event_type = "command.imported",
    input_shape = "sqlite_row",
    adapter = "SqliteRowAdapter",
    default_privacy_context = "Command",
    privacy_tier = "Sensitive",
    horizons = "continuous, historical",
    retention = "forever",
    occurrence_identity = "natural",
    access_policy = "target_home_read:.local/share/fish/fish_history",
    implementation = "sinexd",
    privacy_context = "Command",
    material_policy = "sqlite_row_id",
    checkpoint_policy = "mutable_snapshot",
    resource_shape = "linear_rows_bounded_memory",
    runner_pack = "sinexd-source",
    checkpoint_family = "mutable_snapshot:sqlite:fish_history_row_id",
    runtime_shape = "continuous",
    package_impact = "fish_history_source",
    implementation_mode = "sinexd:source",
    baseline_adapter_config = r#"{"query":"fish_history","table":"fish_history"}"#
)]
pub struct FishHistoryRecord {
    /// `SQLite` rowid — natural occurrence anchor (excluded from the emitted
    /// payload).
    #[source(column_name = "rowid")]
    #[occurrence_key]
    #[skip]
    pub rowid: i64,

    /// Executed command text.
    #[source(column_name = "command")]
    #[required]
    #[privacy(context = "Command")]
    #[privacy(sensitivity = "free_text, credential_bearing")]
    pub command: String,

    /// Command timestamp in unix seconds (optional; absent or null rows fall
    /// back to the material's acquisition time via `material_timing`).
    #[source(column_name = "when")]
    #[timestamp(format = "unix_seconds", fallback = "material_timing")]
    pub when: i64,
}
