use crate::{EventSender, Result};
use async_trait::async_trait;
use schemars::schema::RootSchema;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::path::PathBuf;

// ===== Event output configuration (from event_output.rs) =====

/// Simple event output configuration
#[derive(Debug, Clone, Default)]
pub struct EventOutput {
    pub write_to_db: bool,
    pub log_events: bool,
    pub debug_file: Option<PathBuf>,
}

impl EventOutput {
    pub fn database() -> Self {
        Self {
            write_to_db: true,
            log_events: false,
            debug_file: None,
        }
    }

    pub fn dry_run() -> Self {
        Self {
            write_to_db: false,
            log_events: true,
            debug_file: None,
        }
    }

    pub fn with_debug_file(mut self, path: PathBuf) -> Self {
        self.debug_file = Some(path);
        self
    }
}

// ===== Traits (from traits.rs) =====

/// Core trait for event types - events are primary entities
pub trait EventType: Send + Sync + 'static {
    /// The payload type for this event
    type Payload: Serialize + for<'de> Deserialize<'de> + JsonSchema + Send + Sync + 'static;

    /// The source implementation(s) that produce this event
    /// Can be a single source or tuple of sources
    type SourceImpl: EventSourceProvider;

    /// Canonical event name (e.g., "file.created")
    const EVENT_NAME: &'static str;

    /// Source name - derived from SourceImpl
    const SOURCE_NAME: &'static str = <Self::SourceImpl as EventSourceProvider>::SOURCE_NAME;
}

/// Trait for event sources - implementation details that produce events
#[async_trait]
pub trait EventSource: Send + Sync + 'static {
    /// Configuration type for this source
    type Config: Clone + Serialize + for<'de> Deserialize<'de> + Send + Sync + 'static;

    /// Canonical source name
    const SOURCE_NAME: &'static str;

    /// Initialize the source with context containing config and shared resources
    async fn initialize(ctx: crate::EventSourceContext) -> Result<Self>
    where
        Self: Sized;

    /// Stream ALL events this source can detect
    /// The registry will filter based on enabled events
    async fn stream_events(&mut self, tx: EventSender) -> Result<()>;

    /// Graceful shutdown
    async fn shutdown(&mut self) -> Result<()> {
        Ok(())
    }
}

/// Trait to support both single sources and tuples of sources
pub trait EventSourceProvider: Send + Sync + 'static {
    const SOURCE_NAME: &'static str;
}

// Single source implementation
impl<T: EventSource> EventSourceProvider for T {
    const SOURCE_NAME: &'static str = T::SOURCE_NAME;
}

// Tuple implementations for multiple sources
impl<A: EventSource, B: EventSource> EventSourceProvider for (A, B) {
    const SOURCE_NAME: &'static str = "multiple"; // Or could concatenate
}

impl<A: EventSource, B: EventSource, C: EventSource> EventSourceProvider for (A, B, C) {
    const SOURCE_NAME: &'static str = "multiple";
}

// ===== Registry (from registry.rs) =====

/// Event registry - compile-time discovered events
pub struct EventRegistry {
    /// All event types in the system
    pub event_types: &'static [&'static str],

    /// Mapping from event type to source name
    pub event_to_source: &'static [(&'static str, &'static str)],

    /// Schema generators for each event type
    pub schema_generators: HashMap<&'static str, fn() -> RootSchema>,
}

impl EventRegistry {
    /// Get source name for an event type
    pub fn source_for_event(&self, event_type: &str) -> Option<&'static str> {
        self.event_to_source
            .iter()
            .find(|(e, _)| *e == event_type)
            .map(|(_, s)| *s)
    }

    /// Get all events for a source
    pub fn events_for_source(&self, source: &str) -> Vec<&'static str> {
        self.event_to_source
            .iter()
            .filter(|(_, s)| *s == source)
            .map(|(e, _)| *e)
            .collect()
    }

    /// Get schema for an event type
    pub fn schema_for_event(&self, event_type: &str) -> Option<RootSchema> {
        self.schema_generators.get(event_type).map(|f| f())
    }

    /// Check if an event type exists
    pub fn has_event(&self, event_type: &str) -> bool {
        self.event_types.contains(&event_type)
    }

    /// Get all unique source names
    pub fn all_sources(&self) -> Vec<&'static str> {
        let mut sources: Vec<_> = self.event_to_source.iter().map(|(_, s)| *s).collect();
        sources.sort();
        sources.dedup();
        sources
    }
}

// This will be generated by a build script or macro
// For now, we'll create it manually
pub fn create_registry() -> EventRegistry {
    EventRegistry {
        event_types: &[
            "file.created",
            "file.modified",
            "file.deleted",
            "command.executed",
            "shell.command.executed_atuin",
            // Window events
            "window.focused",
            "window.opened",
            "window.closed",
            "window.moved",
            "window.title_changed",
            "window.urgent",
            // Workspace events
            "workspace.changed",
            "workspace.created",
            "workspace.destroyed",
            // Monitor events
            "monitor.focused",
            "monitor.added",
            "monitor.removed",
            // State dumps
            "state.snapshot",
            // Shell history
            "shell.history.command",
            // Terminal recording
            "terminal.asciinema.session_started",
            "terminal.asciinema.session_ended",
            "terminal.scrollback.captured",
            "terminal.command_output.captured",
            // D-Bus events
            "dbus.signal",
            "dbus.method_call",
            "system.notification",
            "media.playback.changed",
            "system.power.event",
            "hardware.device.event",
            "session.state.changed",
            "security.policykit.authorization",
            "bluetooth.device.event",
            "network.connection.event",
            "screen.saver.event",
            "storage.mount.event",
            // Clipboard events
            "clipboard.content.changed",
            "clipboard.selection.changed",
            // Journal events
            "system.journal.entry",
            "system.journal.sync",
        ],
        event_to_source: &[
            ("file.created", "filesystem"),
            ("file.modified", "filesystem"),
            ("file.deleted", "filesystem"),
            ("command.executed", "terminal.kitty"),
            ("shell.command.executed_atuin", "ingestor.atuin_db_reader"),
            ("shell.history.command", "ingestor.shell_history_reader"),
            (
                "terminal.asciinema.session_started",
                "ingestor.asciinema_recorder",
            ),
            (
                "terminal.asciinema.session_ended",
                "ingestor.asciinema_recorder",
            ),
            (
                "terminal.scrollback.captured",
                "ingestor.scrollback_capture",
            ),
            (
                "terminal.command_output.captured",
                "ingestor.scrollback_capture",
            ),
            // All window manager events
            ("window.focused", "window_manager.hyprland"),
            ("window.opened", "window_manager.hyprland"),
            ("window.closed", "window_manager.hyprland"),
            ("window.moved", "window_manager.hyprland"),
            ("window.title_changed", "window_manager.hyprland"),
            ("window.urgent", "window_manager.hyprland"),
            ("workspace.changed", "window_manager.hyprland"),
            ("workspace.created", "window_manager.hyprland"),
            ("workspace.destroyed", "window_manager.hyprland"),
            ("monitor.focused", "window_manager.hyprland"),
            ("monitor.added", "window_manager.hyprland"),
            ("monitor.removed", "window_manager.hyprland"),
            ("state.snapshot", "window_manager.hyprland"),
            // Shell history
            ("shell.history.command", "ingestor.shell_history_reader"),
            // Terminal recording
            (
                "terminal.asciinema.session_started",
                "ingestor.asciinema_recorder",
            ),
            (
                "terminal.asciinema.session_ended",
                "ingestor.asciinema_recorder",
            ),
            (
                "terminal.scrollback.captured",
                "ingestor.scrollback_capture",
            ),
            (
                "terminal.command_output.captured",
                "ingestor.scrollback_capture",
            ),
            // D-Bus events
            ("dbus.signal", "dbus.monitor"),
            ("dbus.method_call", "dbus.monitor"),
            ("system.notification", "dbus.monitor"),
            ("media.playback.changed", "dbus.monitor"),
            ("system.power.event", "dbus.monitor"),
            ("hardware.device.event", "dbus.monitor"),
            ("session.state.changed", "dbus.monitor"),
            ("security.policykit.authorization", "dbus.monitor"),
            ("bluetooth.device.event", "dbus.monitor"),
            ("network.connection.event", "dbus.monitor"),
            ("screen.saver.event", "dbus.monitor"),
            ("storage.mount.event", "dbus.monitor"),
            // Clipboard events
            ("clipboard.content.changed", "clipboard"),
            ("clipboard.selection.changed", "clipboard"),
            // Journal events
            ("system.journal.entry", "journal.monitor"),
            ("system.journal.sync", "journal.monitor"),
        ],
        schema_generators: {
            let mut generators: HashMap<&'static str, fn() -> RootSchema> = HashMap::new();

            fn file_created_schema() -> RootSchema {
                use schemars::schema::*;
                RootSchema {
                    meta_schema: None,
                    schema: SchemaObject {
                        instance_type: Some(InstanceType::Object.into()),
                        object: Some(Box::new(ObjectValidation {
                            properties: {
                                let mut props = std::collections::BTreeMap::new();
                                props.insert(
                                    "path".to_string(),
                                    Schema::Object(SchemaObject {
                                        instance_type: Some(InstanceType::String.into()),
                                        ..Default::default()
                                    }),
                                );
                                props.insert(
                                    "size".to_string(),
                                    Schema::Object(SchemaObject {
                                        instance_type: Some(InstanceType::Integer.into()),
                                        ..Default::default()
                                    }),
                                );
                                props
                            },
                            required: vec!["path".to_string(), "size".to_string()]
                                .into_iter()
                                .collect(),
                            ..Default::default()
                        })),
                        ..Default::default()
                    },
                    definitions: Default::default(),
                }
            }

            fn file_modified_schema() -> RootSchema {
                file_created_schema() // Same schema as file.created
            }

            fn file_deleted_schema() -> RootSchema {
                use schemars::schema::*;
                RootSchema {
                    meta_schema: None,
                    schema: SchemaObject {
                        instance_type: Some(InstanceType::Object.into()),
                        object: Some(Box::new(ObjectValidation {
                            properties: {
                                let mut props = std::collections::BTreeMap::new();
                                props.insert(
                                    "path".to_string(),
                                    Schema::Object(SchemaObject {
                                        instance_type: Some(InstanceType::String.into()),
                                        ..Default::default()
                                    }),
                                );
                                props
                            },
                            required: vec!["path".to_string()].into_iter().collect(),
                            ..Default::default()
                        })),
                        ..Default::default()
                    },
                    definitions: Default::default(),
                }
            }

            fn command_executed_schema() -> RootSchema {
                use schemars::schema::*;
                RootSchema {
                    meta_schema: None,
                    schema: SchemaObject {
                        instance_type: Some(InstanceType::Object.into()),
                        object: Some(Box::new(ObjectValidation {
                            properties: {
                                let mut props = std::collections::BTreeMap::new();
                                props.insert(
                                    "command".to_string(),
                                    Schema::Object(SchemaObject {
                                        instance_type: Some(InstanceType::String.into()),
                                        ..Default::default()
                                    }),
                                );
                                props.insert(
                                    "exit_code".to_string(),
                                    Schema::Object(SchemaObject {
                                        instance_type: Some(InstanceType::Integer.into()),
                                        ..Default::default()
                                    }),
                                );
                                props
                            },
                            required: vec!["command".to_string()].into_iter().collect(),
                            ..Default::default()
                        })),
                        ..Default::default()
                    },
                    definitions: Default::default(),
                }
            }

            generators.insert("file.created", file_created_schema);
            generators.insert("file.modified", file_modified_schema);
            generators.insert("file.deleted", file_deleted_schema);
            generators.insert("command.executed", command_executed_schema);

            generators
        },
    }
}
