use crate::{EventSender, Result};
use async_trait::async_trait;
use schemars::schema::RootSchema;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::path::PathBuf;

// ===== Event output configuration (from event_output.rs) =====

/// Simple event output configuration
#[derive(Debug, Clone, Default)]
pub struct EventOutput {
    pub write_to_db: bool,
    pub log_events: bool,
    pub debug_file: Option<PathBuf>,
}

impl EventOutput {
    pub fn database() -> Self {
        Self {
            write_to_db: true,
            log_events: false,
            debug_file: None,
        }
    }

    pub fn dry_run() -> Self {
        Self {
            write_to_db: false,
            log_events: true,
            debug_file: None,
        }
    }

    pub fn with_debug_file(mut self, path: PathBuf) -> Self {
        self.debug_file = Some(path);
        self
    }
}

// ===== Traits (from traits.rs) =====

/// Core trait for event types - events are primary entities
pub trait EventType: Send + Sync + 'static {
    /// The payload type for this event
    type Payload: Serialize + for<'de> Deserialize<'de> + JsonSchema + Send + Sync + 'static;

    /// The source implementation(s) that produce this event
    /// Can be a single source or tuple of sources
    type SourceImpl: EventSourceProvider;

    /// Canonical event name (e.g., "file.created")
    const EVENT_NAME: &'static str;

    /// Source name - derived from SourceImpl
    const SOURCE_NAME: &'static str = <Self::SourceImpl as EventSourceProvider>::SOURCE_NAME;
}

/// Trait for event sources - implementation details that produce events
#[async_trait]
pub trait EventSource: Send + Sync + 'static {
    /// Configuration type for this source
    type Config: Clone + Serialize + for<'de> Deserialize<'de> + Send + Sync + 'static;

    /// Canonical source name
    const SOURCE_NAME: &'static str;

    /// Initialize the source with context containing config and shared resources
    async fn initialize(ctx: crate::EventSourceContext) -> Result<Self>
    where
        Self: Sized;

    /// Stream ALL events this source can detect
    /// The registry will filter based on enabled events
    async fn stream_events(&mut self, tx: EventSender) -> Result<()>;

    /// Graceful shutdown
    async fn shutdown(&mut self) -> Result<()> {
        Ok(())
    }
}

/// Trait to support both single sources and tuples of sources
pub trait EventSourceProvider: Send + Sync + 'static {
    const SOURCE_NAME: &'static str;
}

// Single source implementation
impl<T: EventSource> EventSourceProvider for T {
    const SOURCE_NAME: &'static str = T::SOURCE_NAME;
}

// Tuple implementations for multiple sources
impl<A: EventSource, B: EventSource> EventSourceProvider for (A, B) {
    const SOURCE_NAME: &'static str = "multiple"; // Or could concatenate
}

impl<A: EventSource, B: EventSource, C: EventSource> EventSourceProvider for (A, B, C) {
    const SOURCE_NAME: &'static str = "multiple";
}

// ===== Registry (from registry.rs) =====

/// Event registry - compile-time discovered events
pub struct EventRegistry {
    /// All event types in the system
    pub event_types: &'static [&'static str],

    /// Mapping from event type to source name
    pub event_to_source: &'static [(&'static str, &'static str)],

    /// Schema generators for each event type
    pub schema_generators: HashMap<&'static str, fn() -> RootSchema>,
}

impl EventRegistry {
    /// Get source name for an event type
    pub fn source_for_event(&self, event_type: &str) -> Option<&'static str> {
        self.event_to_source
            .iter()
            .find(|(e, _)| *e == event_type)
            .map(|(_, s)| *s)
    }

    /// Get all events for a source
    pub fn events_for_source(&self, source: &str) -> Vec<&'static str> {
        self.event_to_source
            .iter()
            .filter(|(_, s)| *s == source)
            .map(|(e, _)| *e)
            .collect()
    }

    /// Get schema for an event type
    pub fn schema_for_event(&self, event_type: &str) -> Option<RootSchema> {
        self.schema_generators.get(event_type).map(|f| f())
    }

    /// Check if an event type exists
    pub fn has_event(&self, event_type: &str) -> bool {
        self.event_types.contains(&event_type)
    }

    /// Get all unique source names
    pub fn all_sources(&self) -> Vec<&'static str> {
        let mut sources: Vec<_> = self.event_to_source.iter().map(|(_, s)| *s).collect();
        sources.sort();
        sources.dedup();
        sources
    }
}

// This will be generated by a build script or macro
// For now, we'll create it manually
pub fn create_registry() -> EventRegistry {
    EventRegistry {
        event_types: &[
            // Filesystem events
            "file.created",
            "file.modified",
            "file.deleted",
            "file.moved",
            "dir.created",
            "dir.deleted",
            // Shell events
            "command.executed",
            "command.failed",
            "session.started",
            "session.ended",
            // Shell history/atuin events
            "command.imported",
            // Shell recording events
            "recording.started",
            "recording.ended",
            // Shell scrollback events
            "output.captured",
            // Window manager events
            "window.opened",
            "window.closed",
            "window.focused",
            "window.moved",
            "window.resized",
            "workspace.switched",
            "workspace.created",
            "workspace.destroyed",
            "display.connected",
            "display.disconnected",
            "monitor.focused",
            "state.captured",
            // Clipboard events
            "copied",
            "selected",
            // D-Bus events
            "signal.received",
            "method.called",
            "notification.sent",
            "device.connected",
            "device.disconnected",
            "media.state_changed",
            "power.state_changed",
            "network.state_changed",
            "bluetooth.device_changed",
            "mount.changed",
            // Journal events
            "entry.written",
        ],
        event_to_source: &[
            // Filesystem events
            ("file.created", "fs"),
            ("file.modified", "fs"),
            ("file.deleted", "fs"),
            ("file.moved", "fs"),
            ("dir.created", "fs"),
            ("dir.deleted", "fs"),
            // Shell events
            ("command.executed", "shell.kitty"),
            ("command.failed", "shell.kitty"),
            ("session.started", "shell.kitty"),
            ("session.ended", "shell.kitty"),
            // Shell history/atuin events
            ("command.imported", "shell.atuin"),
            ("command.imported", "shell.history"),
            // Shell recording events
            ("recording.started", "shell.recording"),
            ("recording.ended", "shell.recording"),
            // Shell scrollback events
            ("output.captured", "shell.scrollback"),
            // Window manager events
            ("window.opened", "wm.hyprland"),
            ("window.closed", "wm.hyprland"),
            ("window.focused", "wm.hyprland"),
            ("window.moved", "wm.hyprland"),
            ("window.resized", "wm.hyprland"),
            ("workspace.switched", "wm.hyprland"),
            ("workspace.created", "wm.hyprland"),
            ("workspace.destroyed", "wm.hyprland"),
            ("display.connected", "wm.hyprland"),
            ("display.disconnected", "wm.hyprland"),
            ("monitor.focused", "wm.hyprland"),
            ("state.captured", "wm.hyprland"),
            // Clipboard events
            ("copied", "clipboard"),
            ("selected", "clipboard"),
            // D-Bus events
            ("signal.received", "dbus"),
            ("method.called", "dbus"),
            ("notification.sent", "dbus"),
            ("device.connected", "dbus"),
            ("device.disconnected", "dbus"),
            ("media.state_changed", "dbus"),
            ("power.state_changed", "dbus"),
            ("network.state_changed", "dbus"),
            ("bluetooth.device_changed", "dbus"),
            ("mount.changed", "dbus"),
            // Journal events
            ("entry.written", "journald"),
        ],
        schema_generators: {
            let mut generators: HashMap<&'static str, fn() -> RootSchema> = HashMap::new();

            fn file_created_schema() -> RootSchema {
                use schemars::schema::*;
                RootSchema {
                    meta_schema: None,
                    schema: SchemaObject {
                        instance_type: Some(InstanceType::Object.into()),
                        object: Some(Box::new(ObjectValidation {
                            properties: {
                                let mut props = std::collections::BTreeMap::new();
                                props.insert(
                                    "path".to_string(),
                                    Schema::Object(SchemaObject {
                                        instance_type: Some(InstanceType::String.into()),
                                        ..Default::default()
                                    }),
                                );
                                props.insert(
                                    "size".to_string(),
                                    Schema::Object(SchemaObject {
                                        instance_type: Some(InstanceType::Integer.into()),
                                        ..Default::default()
                                    }),
                                );
                                props
                            },
                            required: vec!["path".to_string(), "size".to_string()]
                                .into_iter()
                                .collect(),
                            ..Default::default()
                        })),
                        ..Default::default()
                    },
                    definitions: Default::default(),
                }
            }

            fn file_modified_schema() -> RootSchema {
                file_created_schema() // Same schema as file.created
            }

            fn file_deleted_schema() -> RootSchema {
                use schemars::schema::*;
                RootSchema {
                    meta_schema: None,
                    schema: SchemaObject {
                        instance_type: Some(InstanceType::Object.into()),
                        object: Some(Box::new(ObjectValidation {
                            properties: {
                                let mut props = std::collections::BTreeMap::new();
                                props.insert(
                                    "path".to_string(),
                                    Schema::Object(SchemaObject {
                                        instance_type: Some(InstanceType::String.into()),
                                        ..Default::default()
                                    }),
                                );
                                props
                            },
                            required: vec!["path".to_string()].into_iter().collect(),
                            ..Default::default()
                        })),
                        ..Default::default()
                    },
                    definitions: Default::default(),
                }
            }

            fn command_executed_schema() -> RootSchema {
                use schemars::schema::*;
                RootSchema {
                    meta_schema: None,
                    schema: SchemaObject {
                        instance_type: Some(InstanceType::Object.into()),
                        object: Some(Box::new(ObjectValidation {
                            properties: {
                                let mut props = std::collections::BTreeMap::new();
                                props.insert(
                                    "command".to_string(),
                                    Schema::Object(SchemaObject {
                                        instance_type: Some(InstanceType::String.into()),
                                        ..Default::default()
                                    }),
                                );
                                props.insert(
                                    "exit_code".to_string(),
                                    Schema::Object(SchemaObject {
                                        instance_type: Some(InstanceType::Integer.into()),
                                        ..Default::default()
                                    }),
                                );
                                props
                            },
                            required: vec!["command".to_string()].into_iter().collect(),
                            ..Default::default()
                        })),
                        ..Default::default()
                    },
                    definitions: Default::default(),
                }
            }

            fn file_moved_schema() -> RootSchema {
                use schemars::schema::*;
                RootSchema {
                    meta_schema: None,
                    schema: SchemaObject {
                        instance_type: Some(InstanceType::Object.into()),
                        object: Some(Box::new(ObjectValidation {
                            properties: {
                                let mut props = std::collections::BTreeMap::new();
                                props.insert(
                                    "path".to_string(),
                                    Schema::Object(SchemaObject {
                                        instance_type: Some(InstanceType::String.into()),
                                        ..Default::default()
                                    }),
                                );
                                props.insert(
                                    "old_path".to_string(),
                                    Schema::Object(SchemaObject {
                                        instance_type: Some(InstanceType::String.into()),
                                        ..Default::default()
                                    }),
                                );
                                props.insert(
                                    "moved_at".to_string(),
                                    Schema::Object(SchemaObject {
                                        instance_type: Some(InstanceType::String.into()),
                                        ..Default::default()
                                    }),
                                );
                                props
                            },
                            required: vec!["path".to_string(), "moved_at".to_string()]
                                .into_iter()
                                .collect(),
                            ..Default::default()
                        })),
                        ..Default::default()
                    },
                    definitions: Default::default(),
                }
            }

            fn dir_created_schema() -> RootSchema {
                use schemars::schema::*;
                RootSchema {
                    meta_schema: None,
                    schema: SchemaObject {
                        instance_type: Some(InstanceType::Object.into()),
                        object: Some(Box::new(ObjectValidation {
                            properties: {
                                let mut props = std::collections::BTreeMap::new();
                                props.insert(
                                    "path".to_string(),
                                    Schema::Object(SchemaObject {
                                        instance_type: Some(InstanceType::String.into()),
                                        ..Default::default()
                                    }),
                                );
                                props.insert(
                                    "created_at".to_string(),
                                    Schema::Object(SchemaObject {
                                        instance_type: Some(InstanceType::String.into()),
                                        ..Default::default()
                                    }),
                                );
                                props.insert(
                                    "permissions".to_string(),
                                    Schema::Object(SchemaObject {
                                        instance_type: Some(InstanceType::Integer.into()),
                                        ..Default::default()
                                    }),
                                );
                                props
                            },
                            required: vec!["path".to_string(), "created_at".to_string()]
                                .into_iter()
                                .collect(),
                            ..Default::default()
                        })),
                        ..Default::default()
                    },
                    definitions: Default::default(),
                }
            }

            fn dir_deleted_schema() -> RootSchema {
                file_deleted_schema() // Same schema as file.deleted
            }

            generators.insert("file.created", file_created_schema);
            generators.insert("file.modified", file_modified_schema);
            generators.insert("file.deleted", file_deleted_schema);
            generators.insert("file.moved", file_moved_schema);
            generators.insert("dir.created", dir_created_schema);
            generators.insert("dir.deleted", dir_deleted_schema);
            generators.insert("command.executed", command_executed_schema);

            generators
        },
    }
}
