-- Create synthesis schema for derived events and higher-order synthesis
-- This implements the dual-log database architecture from the refactoring plan

CREATE SCHEMA IF NOT EXISTS synthesis;
COMMENT ON SCHEMA synthesis IS 'Schema for derived, synthesized, and higher-order events generated by automata';

-- Create synthesis.events table mirroring raw.events structure with provenance tracking
CREATE TABLE synthesis.events (
    id ULID PRIMARY KEY DEFAULT gen_ulid(),
    source TEXT NOT NULL CHECK (LENGTH(TRIM(source)) > 0), -- The name of the Automaton/Agent that generated it
    event_type TEXT NOT NULL CHECK (LENGTH(TRIM(event_type)) > 0), -- The new, higher-level event type
    ts_ingest TIMESTAMPTZ GENERATED ALWAYS AS (id::timestamp) STORED, -- Generated from ULID like raw.events
    ts_orig TIMESTAMPTZ, -- The conceptual time of the synthesized event
    host TEXT NOT NULL CHECK (LENGTH(TRIM(host)) > 0),
    ingestor_version TEXT, -- Version of the automaton that generated this
    payload_schema_id ULID REFERENCES sinex_schemas.event_payload_schemas(id) ON DELETE SET NULL ON UPDATE CASCADE,
    payload JSONB NOT NULL,
    
    -- Schema fields matching raw.events
    payload_schema_name TEXT,
    payload_schema_version TEXT,
    
    -- Crucial Provenance Links - tracks which events were used as evidence
    source_raw_event_ids ULID[], -- The raw events used as evidence
    source_synthesis_event_ids ULID[] -- Optional, for cascading synthesis
);

-- Convert to TimescaleDB hypertable using ULID partitioning (same pattern as raw.events)
-- First ensure the ulid_to_timestamptz function exists (it should from raw.events migration)
DO $$
BEGIN
  -- Create function if it doesn't exist (should already exist from raw.events migration)
  IF NOT EXISTS (SELECT 1 FROM pg_proc WHERE proname = 'ulid_to_timestamptz') THEN
    CREATE OR REPLACE FUNCTION ulid_to_timestamptz(ulid_val ULID) 
    RETURNS TIMESTAMPTZ AS $func$
    BEGIN
        RETURN ulid_val::timestamp;
    END;
    $func$ LANGUAGE plpgsql IMMUTABLE STRICT PARALLEL SAFE;
  END IF;

  -- Check if already a hypertable
  IF EXISTS (
    SELECT 1 FROM _timescaledb_catalog.hypertable 
    WHERE table_name = 'events' AND schema_name = 'synthesis'
  ) THEN
    RAISE NOTICE 'synthesis.events is already a hypertable, skipping';
    RETURN;
  END IF;

  -- Create hypertable partitioned by ULID using the same function as raw.events
  PERFORM create_hypertable(
    'synthesis.events',
    by_range('id', partition_func => 'ulid_to_timestamptz'::regproc)
  );
END;
$$;

-- Add necessary indexes for efficient querying
CREATE INDEX idx_synthesis_events_source_type_ts ON synthesis.events (source, event_type, ts_orig DESC);
CREATE INDEX idx_synthesis_source_raw_ids ON synthesis.events USING GIN (source_raw_event_ids);
CREATE INDEX idx_synthesis_source_synthesis_ids ON synthesis.events USING GIN (source_synthesis_event_ids);
CREATE INDEX idx_synthesis_events_id ON synthesis.events (id);
CREATE INDEX idx_synthesis_events_ts_ingest ON synthesis.events (ts_ingest DESC);

-- Add comments for documentation
COMMENT ON TABLE synthesis.events IS 'Derived, synthesized events created by automata from raw events';
COMMENT ON COLUMN synthesis.events.source_raw_event_ids IS 'ULIDs of raw events used as evidence for this synthesis';
COMMENT ON COLUMN synthesis.events.source_synthesis_event_ids IS 'ULIDs of synthesis events used for cascading synthesis';