-- Create synthesis schema for derived events and higher-order synthesis
-- This implements the dual-log database architecture from the refactoring plan
--
-- BUSINESS RULES:
-- 1. All synthesis events must have provenance links (source_raw_event_ids or source_synthesis_event_ids)
-- 2. Synthesis events are immutable once written (same as raw events)
-- 3. ULID partitioning ensures time-ordered processing and efficient queries
-- 4. Provenance arrays enable full event lineage tracking
--
-- PERFORMANCE CHARACTERISTICS:
-- - TimescaleDB hypertable for time-series optimizations
-- - GIN indexes on provenance arrays for fast ancestry queries
-- - Composite indexes for source + event_type filtering
-- - Automatic compression and retention policies (configured separately)

CREATE SCHEMA IF NOT EXISTS synthesis;
COMMENT ON SCHEMA synthesis IS 'Schema for derived, synthesized, and higher-order events generated by automata. Implements dual-log architecture with full provenance tracking.';

-- Create synthesis.events table mirroring raw.events structure with provenance tracking
CREATE TABLE synthesis.events (
    id ULID PRIMARY KEY DEFAULT gen_ulid(),
    source TEXT NOT NULL CHECK (LENGTH(TRIM(source)) > 0), -- The name of the Automaton/Agent that generated it
    event_type TEXT NOT NULL CHECK (LENGTH(TRIM(event_type)) > 0), -- The new, higher-level event type
    ts_ingest TIMESTAMPTZ GENERATED ALWAYS AS (id::timestamp) STORED, -- Generated from ULID like raw.events
    ts_orig TIMESTAMPTZ, -- The conceptual time of the synthesized event
    host TEXT NOT NULL CHECK (LENGTH(TRIM(host)) > 0),
    ingestor_version TEXT, -- Version of the automaton that generated this
    payload_schema_id ULID REFERENCES sinex_schemas.event_payload_schemas(id) ON DELETE SET NULL ON UPDATE CASCADE,
    payload JSONB NOT NULL,
    
    -- Schema fields matching raw.events
    payload_schema_name TEXT,
    payload_schema_version TEXT,
    
    -- Crucial Provenance Links - tracks which events were used as evidence
    source_raw_event_ids ULID[], -- The raw events used as evidence
    source_synthesis_event_ids ULID[] -- Optional, for cascading synthesis
);

-- Convert to TimescaleDB hypertable using ULID partitioning (same pattern as raw.events)
-- First ensure the ulid_to_timestamptz function exists (it should from raw.events migration)
DO $$
BEGIN
  -- Create function if it doesn't exist (should already exist from raw.events migration)
  IF NOT EXISTS (SELECT 1 FROM pg_proc WHERE proname = 'ulid_to_timestamptz') THEN
    CREATE OR REPLACE FUNCTION ulid_to_timestamptz(ulid_val ULID) 
    RETURNS TIMESTAMPTZ AS $func$
    BEGIN
        RETURN ulid_val::timestamp;
    END;
    $func$ LANGUAGE plpgsql IMMUTABLE STRICT PARALLEL SAFE;
  END IF;

  -- Check if already a hypertable
  IF EXISTS (
    SELECT 1 FROM _timescaledb_catalog.hypertable 
    WHERE table_name = 'events' AND schema_name = 'synthesis'
  ) THEN
    RAISE NOTICE 'synthesis.events is already a hypertable, skipping';
    RETURN;
  END IF;

  -- Create hypertable partitioned by ULID using the same function as raw.events
  PERFORM create_hypertable(
    'synthesis.events',
    by_range('id', partition_func => 'ulid_to_timestamptz'::regproc)
  );
END;
$$;

-- Add necessary indexes for efficient querying
CREATE INDEX idx_synthesis_events_source_type_ts ON synthesis.events (source, event_type, ts_orig DESC);
CREATE INDEX idx_synthesis_source_raw_ids ON synthesis.events USING GIN (source_raw_event_ids);
CREATE INDEX idx_synthesis_source_synthesis_ids ON synthesis.events USING GIN (source_synthesis_event_ids);
CREATE INDEX idx_synthesis_events_id ON synthesis.events (id);
CREATE INDEX idx_synthesis_events_ts_ingest ON synthesis.events (ts_ingest DESC);

-- Add comprehensive comments for documentation
COMMENT ON TABLE synthesis.events IS 'Derived, synthesized events created by automata from raw events. Mirrors raw.events structure with provenance tracking. Immutable once written.';

-- Core event fields (mirroring raw.events)
COMMENT ON COLUMN synthesis.events.id IS 'Globally unique ULID identifier. Generated automatically, provides time-ordering and partitioning key.';
COMMENT ON COLUMN synthesis.events.source IS 'Name of the automaton/agent that generated this synthesis event (e.g., "command-canonicalizer", "health-aggregator").';
COMMENT ON COLUMN synthesis.events.event_type IS 'Higher-level event type produced by synthesis (e.g., "command.canonical", "health.alert").';
COMMENT ON COLUMN synthesis.events.ts_ingest IS 'Timestamp when this event was created, extracted from ULID. Primary TimescaleDB partitioning dimension.';
COMMENT ON COLUMN synthesis.events.ts_orig IS 'Conceptual timestamp of the synthesized event. May differ from ts_ingest for historical analysis.';
COMMENT ON COLUMN synthesis.events.host IS 'Hostname where the synthesis occurred. Enables distributed processing tracking.';
COMMENT ON COLUMN synthesis.events.ingestor_version IS 'Version of the automaton that generated this event. Enables compatibility and debugging.';
COMMENT ON COLUMN synthesis.events.payload_schema_id IS 'Foreign key to event schema registry. NULL for ad-hoc synthesis events.';
COMMENT ON COLUMN synthesis.events.payload IS 'Complete synthesis event data as JSONB. Contains derived insights and metadata.';

-- Schema validation fields
COMMENT ON COLUMN synthesis.events.payload_schema_name IS 'Human-readable schema name for payload validation (e.g., "command-canonical-v1").';
COMMENT ON COLUMN synthesis.events.payload_schema_version IS 'Schema version for payload compatibility tracking.';

-- Provenance tracking fields (critical for lineage)
COMMENT ON COLUMN synthesis.events.source_raw_event_ids IS 'Array of raw event ULIDs used as evidence for this synthesis. Enables full event lineage tracking.';
COMMENT ON COLUMN synthesis.events.source_synthesis_event_ids IS 'Array of synthesis event ULIDs used for cascading synthesis. Enables multi-level event derivation.';

-- Index documentation
COMMENT ON INDEX idx_synthesis_events_source_type_ts IS 'Primary query index for filtering by automaton source and event type, ordered by time.';
COMMENT ON INDEX idx_synthesis_source_raw_ids IS 'GIN index for fast provenance queries on raw event ancestry.';
COMMENT ON INDEX idx_synthesis_source_synthesis_ids IS 'GIN index for fast provenance queries on synthesis event ancestry.';
COMMENT ON INDEX idx_synthesis_events_id IS 'Unique identifier index for direct event lookups.';
COMMENT ON INDEX idx_synthesis_events_ts_ingest IS 'Time-based index for chronological event queries and time-series analysis.';