use clap::Subcommand;
use color_eyre::Result;
use inquire::{Select, Text};
use std::process::Command;

use crate::config::Config;
use crate::model::OutputFormat;

/// Config subcommands
#[derive(Debug, Subcommand)]
#[command(after_help = "\
EXAMPLES:
    # Initialize config with guided setup
    sinexctl config init

    # Force overwrite existing config
    sinexctl config init --force

    # Show current configuration
    sinexctl config show

    # Show config as JSON
    sinexctl config show -f json

    # Show config file path
    sinexctl config path

    # Edit config in $EDITOR
    sinexctl config edit
")]
pub enum ConfigCommands {
    /// Initialize config file with guided setup
    Init {
        /// Overwrite existing config file
        #[arg(long)]
        force: bool,
    },

    /// Show current configuration (merged from all sources)
    Show {
        /// Output format
        #[arg(long, short = 'f', value_enum, default_value = "yaml")]
        format: OutputFormat,
    },

    /// Show config file path
    Path,

    /// Open config file in $EDITOR
    Edit,
}

impl ConfigCommands {
    pub async fn execute(&self) -> Result<()> {
        match self {
            Self::Init { force } => config_init(*force).await,
            Self::Show { format } => config_show(*format).await,
            Self::Path => config_path().await,
            Self::Edit => config_edit().await,
        }
    }
}

/// Initialize config file with guided setup
async fn config_init(force: bool) -> Result<()> {
    let config_path = Config::config_file_path()?;

    if config_path.exists() && !force {
        println!("Config file already exists at: {}", config_path.display());
        println!();
        println!("Use --force to overwrite, or edit with:");
        println!("  sinexctl config edit");
        return Ok(());
    }

    println!("Sinex CLI Configuration Wizard");
    println!("==============================");
    println!();

    // Gateway URL
    let rpc_url = Text::new("Gateway RPC URL:")
        .with_default("https://127.0.0.1:9999")
        .with_help_message("The URL of your Sinex gateway")
        .prompt()?;

    // Authentication method
    let auth_options = vec![
        "Environment variable (SINEX_RPC_TOKEN)",
        "Token file",
        "No authentication (dev mode)",
    ];
    let auth_method = Select::new("Authentication method:", auth_options)
        .with_help_message("How to authenticate with the gateway")
        .prompt()?;

    let (_token, token_file): (Option<String>, Option<String>) = match auth_method {
        "Token file" => {
            let path = Text::new("Token file path:")
                .with_default("~/.config/sinex/token")
                .prompt()?;
            (None, Some(expand_tilde(&path)))
        }
        _ => (None, None),
    };

    // TLS options
    let use_insecure = Select::new(
        "Accept invalid TLS certificates? (dev only)",
        vec!["No (recommended)", "Yes (insecure)"],
    )
    .prompt()?
        == "Yes (insecure)";

    // Default output format
    let format_options = vec![
        "table (human-readable)",
        "json (for scripting)",
        "yaml (for config files)",
    ];
    let default_format = Select::new("Default output format:", format_options).prompt()?;
    let default_format = match default_format {
        "json (for scripting)" => "json",
        "yaml (for config files)" => "yaml",
        _ => "table",
    };

    // Generate config TOML
    let mut config_content = String::new();
    config_content.push_str("# Sinex CLI Configuration\n");
    config_content.push_str("# Generated by sinexctl config init\n\n");

    config_content.push_str(&format!("rpc_url = \"{rpc_url}\"\n"));

    if let Some(tf) = &token_file {
        config_content.push_str(&format!("token_file = \"{tf}\"\n"));
    }

    if use_insecure {
        config_content.push_str("insecure = true\n");
    }

    config_content.push_str(&format!("default_format = \"{default_format}\"\n"));

    config_content.push_str("\n# Request timeout in seconds\n");
    config_content.push_str("timeout = 30\n");

    config_content.push_str("\n# Theme settings\n");
    config_content.push_str("[theme]\n");
    config_content.push_str("table_style = \"rounded\"\n");

    // Create parent directories
    if let Some(parent) = config_path.parent() {
        std::fs::create_dir_all(parent)?;
    }

    // Write config file
    std::fs::write(&config_path, config_content)?;

    println!();
    println!("Configuration saved to: {}", config_path.display());
    println!();
    println!("You can edit it anytime with:");
    println!("  sinexctl config edit");

    Ok(())
}

/// Show current configuration
async fn config_show(format: OutputFormat) -> Result<()> {
    let config = Config::load().unwrap_or_else(|_| Config::default());

    match format {
        OutputFormat::Json => {
            let json = serde_json::to_string_pretty(&config)?;
            println!("{json}");
        }
        OutputFormat::Yaml | OutputFormat::Table => {
            // YAML is more readable for config display
            let yaml = serde_yaml::to_string(&config)?;
            println!("{yaml}");
        }
    }

    // Show config sources
    let config_path = Config::config_file_path()?;
    println!("---");
    println!("# Config sources (in priority order):");
    println!("#   1. CLI arguments (highest)");
    println!("#   2. Environment variables (SINEX_*)");
    if config_path.exists() {
        println!("#   3. Config file: {}", config_path.display());
    } else {
        println!("#   3. Config file: (not found)");
    }
    println!("#   4. Defaults (lowest)");

    Ok(())
}

/// Show config file path
async fn config_path() -> Result<()> {
    let config_path = Config::config_file_path()?;
    println!("{}", config_path.display());

    if !config_path.exists() {
        eprintln!();
        eprintln!("(File does not exist yet. Run 'sinexctl config init' to create it.)");
    }

    Ok(())
}

/// Open config file in $EDITOR
async fn config_edit() -> Result<()> {
    let config_path = Config::config_file_path()?;

    // Create config if it doesn't exist
    if !config_path.exists() {
        println!("Config file does not exist. Creating default config...");
        Config::init_config_file()?;
    }

    // Get editor from environment
    let editor = std::env::var("EDITOR")
        .unwrap_or_else(|_| std::env::var("VISUAL").unwrap_or_else(|_| "vi".to_string()));

    println!("Opening {} with {}...", config_path.display(), editor);

    // Open editor
    let status = Command::new(&editor).arg(&config_path).status()?;

    if !status.success() {
        return Err(color_eyre::eyre::eyre!(
            "Editor exited with status: {}",
            status
        ));
    }

    println!("Config file saved.");

    Ok(())
}

/// Expand ~ to home directory
fn expand_tilde(path: &str) -> String {
    if path.starts_with("~/")
        && let Some(home) = dirs::home_dir() {
            return path.replacen('~', &home.to_string_lossy(), 1);
        }
    path.to_string()
}
