#![doc = include_str!("../../docs/api/cascade_analyzer.md")]

use petgraph::graphmap::DiGraphMap;
use serde::{Deserialize, Serialize};
use sinex_db::query_helpers::db_error;
use sinex_db::repositories::{DbPoolExt, EventRepositoryTx};
use sinex_macros::SinexConfig;
use sinex_primitives::constants::replay::DEFAULT_CASCADE_MAX_DEPTH;
use sinex_primitives::{Result, SinexError};
use sqlx::PgPool;
use std::collections::{HashMap, VecDeque};
use std::time::Duration;
use tracing::{debug, info, warn};
use uuid::Uuid;

// Default cascade analyzer configuration values
const DEFAULT_CASCADE_BATCH_SIZE: usize = 1000;
const DEFAULT_CASCADE_MEMORY_LIMIT: usize = 1024 * 1024 * 1024; // 1GB
const DEFAULT_CASCADE_TIMEOUT_SECS: u64 = 60;

/// Analysis of cascade effects for a replay operation
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CascadeAnalysis {
    /// Maximum cascade depth found
    pub max_depth: usize,
    /// Histogram of cascade depths (depth -> count)
    pub depth_histogram: HashMap<usize, usize>,
    /// Events that would violate integrity if archived
    pub integrity_violations: Vec<IntegrityViolation>,
    /// Total events affected
    pub total_affected: usize,
    /// Events with circular dependencies
    pub circular_dependencies: Vec<CircularDependency>,
    /// Memory estimate for full analysis (bytes)
    pub memory_estimate: usize,
}

/// Integrity violation detected during analysis
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IntegrityViolation {
    /// Event that would be archived
    pub archived_event_id: Uuid,
    /// Live event that references it
    pub live_event_id: Uuid,
    /// Type of violation
    pub violation_type: ViolationType,
    /// Severity of the violation
    pub severity: Severity,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum ViolationType {
    /// Live event references archived event
    LiveToArchived,
    /// Material anchor would be orphaned
    OrphanedAnchor,
    /// Schema version mismatch
    SchemaMismatch,
    /// Temporal paradox (child before parent)
    TemporalParadox,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum Severity {
    Critical, // Must be fixed
    Warning,  // Should be reviewed
    Info,     // Informational only
}

/// Circular dependency detected
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CircularDependency {
    /// Events involved in the cycle
    pub cycle: Vec<Uuid>,
    /// Whether this is a strong cycle (all edges mandatory)
    pub is_strong: bool,
}

/// Configuration for cascade analysis
///
/// The `from_env()` method is generated by `#[derive(SinexConfig)]`.
#[derive(Debug, Clone, SinexConfig)]
#[sinex_config(prefix = "SINEX_CASCADE", context = "cascade analyzer")]
pub struct CascadeAnalyzerConfig {
    /// Maximum batch size for processing events at each depth
    #[sinex_config(
        env = "SINEX_CASCADE_BATCH_SIZE",
        default = DEFAULT_CASCADE_BATCH_SIZE,
        parser = parse_positive_usize
    )]
    pub batch_size: usize,
    /// Maximum cascade depth to analyze
    #[sinex_config(
        env = "SINEX_CASCADE_MAX_DEPTH",
        default = DEFAULT_CASCADE_MAX_DEPTH,
        parser = parse_positive_usize
    )]
    pub max_depth: usize,
    /// Whether to include weak dependencies
    #[sinex_config(env = "SINEX_CASCADE_INCLUDE_WEAK", default = false)]
    pub include_weak_dependencies: bool,
    /// Memory limit for analysis (bytes). Enforced during analysis — returns error if exceeded.
    #[sinex_config(
        env = "SINEX_CASCADE_MEMORY_LIMIT_BYTES",
        default_expr = "Some(DEFAULT_CASCADE_MEMORY_LIMIT)",
        parser = parse_positive_optional_usize
    )]
    pub memory_limit_bytes: Option<usize>,
    /// Timeout for analysis operations (prevents indefinite transaction hold)
    #[sinex_config(
        env = "SINEX_CASCADE_TIMEOUT_SECS",
        default_expr = "Duration::from_secs(DEFAULT_CASCADE_TIMEOUT_SECS)",
        duration = "secs",
        nonzero
    )]
    pub timeout: Duration,
}

impl Default for CascadeAnalyzerConfig {
    fn default() -> Self {
        Self {
            batch_size: DEFAULT_CASCADE_BATCH_SIZE,
            max_depth: DEFAULT_CASCADE_MAX_DEPTH,
            include_weak_dependencies: false,
            memory_limit_bytes: Some(DEFAULT_CASCADE_MEMORY_LIMIT),
            timeout: Duration::from_secs(DEFAULT_CASCADE_TIMEOUT_SECS),
        }
    }
}

fn parse_positive_usize(raw: &str) -> std::result::Result<usize, String> {
    let value = raw.parse::<usize>().map_err(|error| error.to_string())?;
    if value == 0 {
        Err("expected a positive integer".to_string())
    } else {
        Ok(value)
    }
}

fn parse_positive_optional_usize(raw: &str) -> std::result::Result<Option<usize>, String> {
    parse_positive_usize(raw).map(Some)
}

/// Memory-efficient cascade analyzer using streaming algorithms
pub struct StreamingCascadeAnalyzer {
    pool: PgPool,
    config: CascadeAnalyzerConfig,
}

impl StreamingCascadeAnalyzer {
    fn quote_identifier(name: &str) -> String {
        let mut quoted = String::with_capacity(name.len() + 2);
        quoted.push('"');
        for ch in name.chars() {
            if ch == '"' {
                quoted.push('"');
            }
            quoted.push(ch);
        }
        quoted.push('"');
        quoted
    }

    /// Create new analyzer with default configuration
    #[must_use]
    pub fn new(pool: PgPool) -> Self {
        Self::with_config(pool, CascadeAnalyzerConfig::default())
    }

    /// Validate session ID to prevent SQL injection
    fn validate_session_id(session_id: &str) -> Result<()> {
        // Session ID should only contain alphanumeric characters and underscores
        // and be reasonable length (max 64 chars)
        if session_id.len() > 64 {
            return Err(SinexError::validation("Session ID too long")
                .with_context("session_id_len", session_id.len().to_string())
                .with_context("max_len", "64"));
        }

        if session_id.is_empty() {
            return Err(SinexError::validation("Session ID cannot be empty"));
        }

        if !session_id
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_')
        {
            return Err(
                SinexError::validation("Session ID contains invalid characters")
                    .with_context("allowed_characters", "ascii_alphanumeric_or_underscore"),
            );
        }

        Ok(())
    }

    /// Create new analyzer with custom configuration
    #[must_use]
    pub fn with_config(pool: PgPool, config: CascadeAnalyzerConfig) -> Self {
        Self { pool, config }
    }

    /// Analyze cascades for a set of events to be modified
    pub async fn analyze_cascades(&self, event_ids: &[Uuid]) -> Result<CascadeAnalysis> {
        info!(
            "Analyzing cascades for {} events (timeout: {:?})",
            event_ids.len(),
            self.config.timeout
        );

        // Generate unique session ID for this analysis
        let session_id = uuid::Uuid::now_v7().simple().to_string();

        // Wrap the entire transaction in a timeout to prevent indefinite holds.
        // Transaction lifecycle (begin/commit/rollback) is managed by pool.with_transaction;
        // the timeout cancels the future on drop which triggers automatic rollback.
        let timeout_duration = self.config.timeout;
        let analysis_future = self.pool.with_transaction(async |tx| {
            self.analyze_cascades_in_transaction(tx, event_ids, &session_id)
                .await
                .map_err(|error| {
                    SinexError::processing("Cascade analysis failed").with_source(error)
                })
        });

        match tokio::time::timeout(timeout_duration, analysis_future).await {
            Ok(Ok(analysis)) => Ok(analysis),
            Ok(Err(error)) => Err(error),
            Err(_elapsed) => {
                warn!(
                    timeout_secs = timeout_duration.as_secs(),
                    event_count = event_ids.len(),
                    session_id = %session_id,
                    "Cascade analysis exceeded timeout - transaction aborted"
                );
                Err(SinexError::timeout("Cascade analysis timed out")
                    .with_context("timeout_secs", timeout_duration.as_secs().to_string())
                    .with_context("event_count", event_ids.len().to_string())
                    .with_context(
                        "hint",
                        "increase SINEX_CASCADE_TIMEOUT_SECS or reduce max_depth",
                    ))
            }
        }
    }

    /// Internal method to perform analysis within a transaction
    async fn analyze_cascades_in_transaction(
        &self,
        tx: &mut sqlx::Transaction<'_, sqlx::Postgres>,
        event_ids: &[Uuid],
        session_id: &str,
    ) -> Result<CascadeAnalysis> {
        // Create temp table with unique name (transaction-scoped)
        let temp_table = self.create_temp_tables_tx(tx, session_id).await?;

        // Populate with initial events
        self.populate_initial_events_tx(tx, &temp_table, event_ids)
            .await?;

        // Build dependency graph iteratively
        let max_depth = self.build_dependency_graph_tx(tx, &temp_table).await?;

        // Calculate statistics
        let depth_histogram = self.calculate_depth_histogram_tx(tx, &temp_table).await?;
        let total_affected = self.count_affected_events_tx(tx, &temp_table).await?;

        // Enforce memory limit before doing expensive violation/cycle detection
        let memory_estimate = total_affected * 256;
        if let Some(limit) = self.config.memory_limit_bytes
            && memory_estimate > limit
        {
            self.cleanup_temp_tables_tx(tx, &temp_table).await?;
            return Err(SinexError::resource_exhausted(
                "Cascade analysis memory estimate exceeds configured limit",
            )
            .with_context("memory_estimate_bytes", memory_estimate.to_string())
            .with_context("event_count", total_affected.to_string())
            .with_context("memory_limit_bytes", limit.to_string())
            .with_context(
                "hint",
                "increase SINEX_CASCADE_MEMORY_LIMIT_BYTES or reduce scope",
            ));
        }

        // Find integrity violations
        let integrity_violations = self.find_integrity_violations_tx(tx, &temp_table).await?;

        // Detect circular dependencies
        let circular_dependencies = self
            .detect_circular_dependencies_tx(tx, &temp_table)
            .await?;

        // Clean up temp tables (within transaction)
        self.cleanup_temp_tables_tx(tx, &temp_table).await?;

        Ok(CascadeAnalysis {
            max_depth,
            depth_histogram,
            integrity_violations,
            total_affected,
            circular_dependencies,
            memory_estimate,
        })
    }

    /// Create temporary tables for analysis (transaction version)
    async fn create_temp_tables_tx(
        &self,
        tx: &mut sqlx::Transaction<'_, sqlx::Postgres>,
        session_id: &str,
    ) -> Result<String> {
        // Validate session_id to prevent SQL injection
        Self::validate_session_id(session_id)?;
        let mut repo = EventRepositoryTx::new(tx);
        let table_name = repo
            .prepare_cascade_session(session_id, true)
            .await
            .map_err(|error| {
                SinexError::database("Failed to prepare cascade session").with_source(error)
            })?;
        debug!("Created temp table: {}", table_name);
        Ok(table_name)
    }

    /// Populate initial events to analyze (transaction version)
    async fn populate_initial_events_tx(
        &self,
        tx: &mut sqlx::Transaction<'_, sqlx::Postgres>,
        table_name: &str,
        event_ids: &[Uuid],
    ) -> Result<()> {
        if event_ids.is_empty() {
            return Ok(());
        }

        let mut repo = EventRepositoryTx::new(tx);
        repo.populate_cascade_roots(table_name, event_ids)
            .await
            .map_err(|error| {
                SinexError::database("Failed to populate cascade roots").with_source(error)
            })?;
        debug!("Populated {} initial events", event_ids.len());
        Ok(())
    }

    /// Build dependency graph using iterative deepening (transaction version)
    async fn build_dependency_graph_tx(
        &self,
        tx: &mut sqlx::Transaction<'_, sqlx::Postgres>,
        table_name: &str,
    ) -> Result<usize> {
        let mut repo = EventRepositoryTx::new(tx);
        let depth = repo
            .expand_cascade(table_name, self.config.max_depth as i32)
            .await
            .map_err(|error| {
                SinexError::database("Failed to expand cascade graph").with_source(error)
            })?;

        Ok(depth)
    }

    /// Calculate depth histogram (transaction version)
    async fn calculate_depth_histogram_tx(
        &self,
        tx: &mut sqlx::Transaction<'_, sqlx::Postgres>,
        table_name: &str,
    ) -> Result<HashMap<usize, usize>> {
        let mut repo = EventRepositoryTx::new(tx);
        let rows = repo
            .cascade_depth_histogram(table_name)
            .await
            .map_err(|error| {
                SinexError::database("Failed to calculate cascade depth histogram")
                    .with_source(error)
            })?;

        let mut histogram = HashMap::new();
        for (depth, count) in rows {
            histogram.insert(depth as usize, count as usize);
        }

        Ok(histogram)
    }

    /// Count affected events (transaction version)
    async fn count_affected_events_tx(
        &self,
        tx: &mut sqlx::Transaction<'_, sqlx::Postgres>,
        table_name: &str,
    ) -> Result<usize> {
        let mut repo = EventRepositoryTx::new(tx);
        let count = repo.cascade_node_count(table_name).await.map_err(|error| {
            SinexError::database("Failed to count cascade nodes").with_source(error)
        })?;
        Ok(count as usize)
    }

    /// Find integrity violations (transaction version)
    async fn find_integrity_violations_tx(
        &self,
        tx: &mut sqlx::Transaction<'_, sqlx::Postgres>,
        table_name: &str,
    ) -> Result<Vec<IntegrityViolation>> {
        let mut repo = EventRepositoryTx::new(tx);

        let mut violations = Vec::new();
        let mut offset = 0;
        const BATCH_SIZE: i32 = 1000;
        // Safety limit to prevent infinite loops or OOM on massive violations
        const MAX_VIOLATIONS: usize = 100_000;

        loop {
            // Use paginated query to avoid timeout on large result sets
            let rows = repo
                .cascade_integrity_violations_paginated(table_name, BATCH_SIZE, offset)
                .await
                .map_err(|error| {
                    SinexError::database("Failed to find cascade integrity violations")
                        .with_source(error)
                })?;

            if rows.is_empty() {
                break;
            }

            offset += rows.len() as i32;

            for (live_id, archived_id) in rows {
                violations.push(IntegrityViolation {
                    archived_event_id: archived_id,
                    live_event_id: live_id,
                    violation_type: ViolationType::LiveToArchived,
                    severity: Severity::Critical,
                });
            }

            if violations.len() >= MAX_VIOLATIONS {
                warn!(
                    "Violation scan exceeded {} rows, stopping (results truncated)",
                    MAX_VIOLATIONS
                );
                break;
            }
        }

        if !violations.is_empty() {
            warn!("Found {} integrity violations", violations.len());
        }

        Ok(violations)
    }

    /// Detect circular dependencies using Tarjan's SCC algorithm
    ///
    /// Loads all parent→child edges from the cascade temp table into an in-memory
    /// directed graph, then runs Tarjan's strongly connected components algorithm.
    /// SCCs with more than one node are genuine cycles. This is guaranteed O(V+E)
    /// and detects cycles at any depth, unlike the previous recursive CTE approach.
    async fn detect_circular_dependencies_tx(
        &self,
        tx: &mut sqlx::Transaction<'_, sqlx::Postgres>,
        table_name: &str,
    ) -> Result<Vec<CircularDependency>> {
        let quoted_table = Self::quote_identifier(table_name);

        // Load all edges: (child_id, parent_id) from the cascade temp table.
        let query = format!(
            r"
            SELECT id, unnest(parent_ids)
            FROM {quoted_table}
            WHERE parent_ids IS NOT NULL
              AND array_length(parent_ids, 1) > 0
            "
        );

        let rows = sqlx::query_as::<_, (Uuid, Uuid)>(&query)
            .fetch_all(&mut **tx)
            .await
            .map_err(|e| db_error(e, "load edges for cycle detection"))?;

        if rows.is_empty() {
            return Ok(Vec::new());
        }

        // Build directed graph: edge from parent → child
        let mut graph: DiGraphMap<Uuid, ()> = DiGraphMap::new();
        for (child_id, parent_id) in &rows {
            graph.add_edge(*parent_id, *child_id, ());
        }

        // Run Tarjan's SCC — O(V+E) guaranteed
        let sccs = petgraph::algo::tarjan_scc(&graph);

        // Filter to actual cycles (SCCs with more than 1 node)
        let mut cycles = Vec::new();
        for scc in sccs {
            if scc.len() > 1 {
                let converted: Vec<Uuid> = scc;
                cycles.push(CircularDependency {
                    cycle: converted,
                    is_strong: true,
                });
            }
        }

        if !cycles.is_empty() {
            warn!(
                "Found {} circular dependencies via Tarjan's SCC",
                cycles.len()
            );
        }

        Ok(cycles)
    }

    /// Clean up temp tables (transaction version)
    async fn cleanup_temp_tables_tx(
        &self,
        tx: &mut sqlx::Transaction<'_, sqlx::Postgres>,
        table_name: &str,
    ) -> Result<()> {
        let mut repo = EventRepositoryTx::new(tx);
        repo.cleanup_cascade_session(table_name)
            .await
            .map_err(|error| {
                SinexError::database("Failed to cleanup cascade session").with_source(error)
            })?;
        Ok(())
    }

    /// Plan safe execution order for cascade operations
    pub async fn plan_cascade_order(&self, event_ids: &[Uuid]) -> Result<Vec<Uuid>> {
        // Perform topological sort to get safe execution order
        // Events with no dependencies first, then their children, etc.

        info!("Planning cascade order for {} events", event_ids.len());

        // Build dependency map
        let mut dependencies: HashMap<Uuid, Vec<Uuid>> = HashMap::new();
        let mut in_degree: HashMap<Uuid, usize> = HashMap::new();

        for &event_id in event_ids {
            in_degree.insert(event_id, 0);
            dependencies.insert(event_id, Vec::new());
        }

        // Query dependencies - need to use raw query due to UUIDv7 type limitations
        use sqlx::Row;
        let rows = sqlx::query(
            r"
            SELECT 
                id as event_id,
                CASE
                    WHEN source_event_ids IS NULL THEN NULL
                    ELSE ARRAY(SELECT elem FROM unnest(source_event_ids) AS elem)
                END as source_event_ids
            FROM core.events
            WHERE id = ANY($1::uuid[])
            ",
        )
        .bind(event_ids)
        .fetch_all(&self.pool)
        .await
        .map_err(|e| db_error(e, "plan cascade order - query dependencies"))?;

        // Build graph
        for row in rows {
            let event_id: Uuid = row.get("event_id");
            let source_ids: Option<Vec<Uuid>> = row.get("source_event_ids");

            if let Some(source_ids) = source_ids {
                for source_id in source_ids {
                    if event_ids.contains(&source_id) {
                        record_dependency(&mut dependencies, &mut in_degree, source_id, event_id);
                    }
                }
            }
        }

        // Topological sort using Kahn's algorithm
        let mut queue: VecDeque<Uuid> = VecDeque::new();
        let mut result = Vec::new();

        // Start with nodes that have no dependencies
        for (&event_id, &degree) in &in_degree {
            if degree == 0 {
                queue.push_back(event_id);
            }
        }

        while let Some(event_id) = queue.pop_front() {
            result.push(event_id);

            // Process children
            if let Some(children) = dependencies.get(&event_id) {
                for &child_id in children {
                    if let Some(degree) = in_degree.get_mut(&child_id) {
                        *degree -= 1;
                        if *degree == 0 {
                            queue.push_back(child_id);
                        }
                    }
                }
            }
        }

        // Check for cycles
        if result.len() != event_ids.len() {
            return Err(
                SinexError::validation("Circular dependencies detected in cascade plan")
                    .with_context("error_class", "cascade_cycle_detected")
                    .with_context("processed_events", result.len().to_string())
                    .with_context("requested_events", event_ids.len().to_string()),
            );
        }

        // Reverse to get deletion order (children before parents)
        result.reverse();

        info!("Planned cascade order for {} events", result.len());
        Ok(result)
    }
}

fn record_dependency(
    dependencies: &mut HashMap<Uuid, Vec<Uuid>>,
    in_degree: &mut HashMap<Uuid, usize>,
    source_id: Uuid,
    event_id: Uuid,
) {
    dependencies.entry(source_id).or_default().push(event_id);
    *in_degree.entry(event_id).or_insert(0) += 1;
}

#[cfg(test)]
#[path = "cascade_analyzer_test.rs"]
mod tests;
