//! Gateway configuration via a typed env-first loader.

use camino::Utf8PathBuf;
use serde::{Deserialize, Serialize};
use sinex_db::{PoolConfig, resolve_effective_database_url};
use sinex_macros::SinexConfig;
use sinex_primitives::domain::SanitizedPath;
use sinex_primitives::error::SinexError;
use sinex_primitives::nats::NatsConnectionConfig;
use sinex_primitives::privacy::resolve_private_mode_state_dir;
use std::num::NonZeroU32;
use std::path::PathBuf;
use std::time::Duration;

/// Gateway configuration.
///
/// Loaded as: struct defaults → environment variables → CLI args.
/// Environment variables use the `SINEX_API_` prefix for gateway-owned fields
/// (for example, `SINEX_API_POOL_MAX_CONNECTIONS=20`) plus a small number of
/// shared `SINEX_*` variables for cross-cutting transport/auth settings.
///
/// The `from_env()` method is generated by `#[derive(SinexConfig)]`.  It reads
/// all non-skip fields strictly (returns `Result`). `load()` builds on top of
/// `from_env()` and applies database-URL resolution.
#[derive(Debug, Clone, Serialize, Deserialize, SinexConfig)]
#[sinex_config(
    prefix = "SINEX_API",
    context = "gateway config",
    fallible,
    normalize_fn = "normalize"
)]
pub struct GatewayConfig {
    /// Database URL for `PostgreSQL` connection.
    #[serde(default = "default_database_url")]
    #[sinex_config(env = "DATABASE_URL", default_expr = "default_database_url()")]
    pub database_url: String,

    /// TCP listen address for the RPC server.
    #[serde(default = "default_tcp_listen")]
    #[sinex_config(env = "SINEX_API_TCP_LISTEN", default_expr = "default_tcp_listen()")]
    pub tcp_listen: String,

    /// Comma-separated CORS origins. Empty means localhost only.
    #[serde(default)]
    #[sinex_config(env = "SINEX_API_CORS_ORIGINS", default_expr = "String::new()")]
    pub cors_origins: String,

    /// Maximum database connections per service pool.
    #[serde(default = "default_pool_max_connections")]
    #[sinex_config(
        env = "SINEX_API_POOL_MAX_CONNECTIONS",
        default_expr = "default_pool_max_connections()"
    )]
    pub pool_max_connections: u32,

    /// Minimum database connections per service pool.
    #[serde(default = "default_pool_min_connections")]
    #[sinex_config(
        env = "SINEX_API_POOL_MIN_CONNECTIONS",
        default_expr = "default_pool_min_connections()"
    )]
    pub pool_min_connections: u32,

    /// Connection acquisition timeout in seconds.
    #[serde(default = "default_pool_acquire_timeout_secs")]
    #[sinex_config(
        env = "SINEX_API_POOL_ACQUIRE_TIMEOUT_SECS",
        default_expr = "default_pool_acquire_timeout_secs()"
    )]
    pub pool_acquire_timeout_secs: u64,

    /// Content-store root path.
    ///
    /// Reads `SINEX_API_CONTENT_STORE_PATH` (gateway-specific) with fallback
    /// to `SINEX_CONTENT_STORE_PATH` (shared). The gateway-specific key takes
    /// priority; set the shared key to override both gateway and event-engine.
    #[serde(default = "default_content_store_path")]
    #[sinex_config(
        env = "SINEX_API_CONTENT_STORE_PATH",
        default_expr = "default_content_store_path()"
    )]
    pub content_store_path: String,

    /// Runtime state root used for gateway-owned local state.
    #[serde(default = "default_state_dir")]
    #[sinex_config(env = "SINEX_STATE_DIR", default_fn = "default_state_dir")]
    pub state_dir: PathBuf,

    /// Bearer token used for RPC authentication.
    /// Read from `SINEX_API_TOKEN`; value is trimmed.
    #[serde(default)]
    #[sinex_config(skip)]
    pub rpc_token: Option<String>,

    /// File containing the bearer token used for RPC authentication.
    #[serde(default)]
    #[sinex_config(env = "SINEX_API_TOKEN_FILE")]
    pub rpc_token_file: Option<String>,

    /// Higher-priority file containing the API admin token.
    #[serde(default)]
    #[sinex_config(env = "SINEX_API_ADMIN_TOKEN_FILE")]
    pub admin_token_file: Option<String>,

    /// Shared NATS connection configuration used by replay control and coordination.
    #[serde(default)]
    #[sinex_config(nested)]
    pub nats: NatsConnectionConfig,

    /// TLS certificate path for the RPC server.
    #[serde(default)]
    #[sinex_config(env = "SINEX_API_TLS_CERT")]
    pub tls_cert: Option<String>,

    /// TLS private key path for the RPC server.
    #[serde(default)]
    #[sinex_config(env = "SINEX_API_TLS_KEY")]
    pub tls_key: Option<String>,

    /// Client CA bundle path for mTLS.
    #[serde(default)]
    #[sinex_config(env = "SINEX_API_TLS_CLIENT_CA")]
    pub tls_client_ca: Option<String>,

    /// Require mTLS even on loopback bindings.
    #[serde(default)]
    #[sinex_config(env = "SINEX_API_REQUIRE_CLIENT_TLS", default = false)]
    pub require_client_tls: bool,

    /// Maximum concurrent RPC requests.
    #[serde(default = "default_max_concurrency")]
    #[sinex_config(
        env = "SINEX_API_MAX_CONCURRENCY",
        default_expr = "default_max_concurrency()"
    )]
    pub max_concurrency: usize,

    /// RPC request timeout in seconds.
    #[serde(default = "default_request_timeout_secs")]
    #[sinex_config(
        env = "SINEX_API_REQUEST_TIMEOUT_SECS",
        default_expr = "default_request_timeout_secs()"
    )]
    pub request_timeout_secs: u64,

    /// Maximum JSON-RPC request body size in bytes.
    #[serde(default = "default_max_body_bytes")]
    #[sinex_config(
        env = "SINEX_API_MAX_BODY_BYTES",
        default_expr = "default_max_body_bytes()"
    )]
    pub max_body_bytes: u64,

    /// Maximum decoded blob payload size in bytes.
    #[serde(default = "default_max_blob_bytes")]
    #[sinex_config(
        env = "SINEX_API_MAX_BLOB_BYTES",
        default_expr = "default_max_blob_bytes()"
    )]
    pub max_blob_bytes: usize,

    /// Replay-control request timeout in seconds.
    #[serde(default = "default_replay_control_timeout_secs")]
    #[sinex_config(
        env = "SINEX_REPLAY_CONTROL_TIMEOUT_SECS",
        default_expr = "default_replay_control_timeout_secs()"
    )]
    pub replay_control_timeout_secs: u64,

    /// NATS consumer creation timeout in seconds for RPC handlers.
    #[serde(default = "default_nats_consumer_create_timeout_secs")]
    #[sinex_config(
        env = "SINEX_NATS_CONSUMER_CREATE_TIMEOUT_SECS",
        default_expr = "default_nats_consumer_create_timeout_secs()"
    )]
    pub nats_consumer_create_timeout_secs: u64,

    /// Trusted extension allow-list for native messaging.
    #[serde(default)]
    #[sinex_config(env = "SINEX_NATIVE_MESSAGING_TRUSTED_EXTENSIONS")]
    pub native_messaging_trusted_extensions: Option<String>,

    /// Trusted native-messaging hosts.
    #[serde(default)]
    #[sinex_config(env = "SINEX_NATIVE_MESSAGING_TRUSTED_HOSTS")]
    pub native_messaging_trusted_hosts: Option<String>,

    /// Enforced native-messaging protocol version.
    #[serde(default)]
    #[sinex_config(env = "SINEX_NATIVE_MESSAGING_PROTOCOL_VERSION")]
    pub native_messaging_protocol_version: Option<String>,

    /// Capability map for native messaging extensions as JSON.
    #[serde(default)]
    #[sinex_config(env = "SINEX_NATIVE_MESSAGING_CAPABILITIES")]
    pub native_messaging_capabilities: Option<String>,

    /// Per-extension role map for native messaging as JSON.
    #[serde(default)]
    #[sinex_config(env = "SINEX_NATIVE_MESSAGING_EXTENSION_ROLES")]
    pub native_messaging_extension_roles: Option<String>,

    /// Native-messaging read timeout in seconds.
    #[serde(default = "default_native_messaging_read_timeout_secs")]
    #[sinex_config(
        env = "SINEX_NATIVE_MESSAGING_READ_TIMEOUT_SECS",
        default_expr = "default_native_messaging_read_timeout_secs()"
    )]
    pub native_messaging_read_timeout_secs: u64,

    /// Maximum native-messaging payload size in bytes.
    #[serde(default = "default_native_messaging_max_size_bytes")]
    #[sinex_config(
        env = "SINEX_NATIVE_MESSAGING_MAX_SIZE_BYTES",
        default_expr = "default_native_messaging_max_size_bytes()"
    )]
    pub native_messaging_max_size_bytes: usize,

    /// Whether RPC rate limiting is enabled.
    #[serde(default = "default_rate_limit_enabled")]
    #[sinex_config(
        env = "SINEX_API_RATE_LIMIT_ENABLED",
        default_expr = "default_rate_limit_enabled()"
    )]
    pub rpc_rate_limit_enabled: bool,

    /// In-memory token bucket refill rate.
    #[serde(default = "default_rate_limit_requests_per_second")]
    #[sinex_config(
        env = "SINEX_API_RATE_LIMIT_REQUESTS_PER_SEC",
        default_expr = "default_rate_limit_requests_per_second()"
    )]
    pub rpc_rate_limit_requests_per_sec: u32,

    /// Per-role refill rate for `ReadOnly` tokens (overrides the global rate).
    #[serde(default = "default_rate_limit_readonly_rps")]
    #[sinex_config(
        env = "SINEX_API_RATE_LIMIT_READONLY_RPS",
        default_expr = "default_rate_limit_readonly_rps()"
    )]
    pub rpc_rate_limit_readonly_rps: u32,

    /// Per-role refill rate for `Write` tokens (overrides the global rate).
    #[serde(default = "default_rate_limit_write_rps")]
    #[sinex_config(
        env = "SINEX_API_RATE_LIMIT_WRITE_RPS",
        default_expr = "default_rate_limit_write_rps()"
    )]
    pub rpc_rate_limit_write_rps: u32,

    /// Per-role refill rate for `Admin` tokens (overrides the global rate;
    /// tighter than write because admin operations have higher impact).
    #[serde(default = "default_rate_limit_admin_rps")]
    #[sinex_config(
        env = "SINEX_API_RATE_LIMIT_ADMIN_RPS",
        default_expr = "default_rate_limit_admin_rps()"
    )]
    pub rpc_rate_limit_admin_rps: u32,

    /// In-memory token bucket burst capacity.
    #[serde(default = "default_rate_limit_burst")]
    #[sinex_config(
        env = "SINEX_API_RATE_LIMIT_BURST",
        default_expr = "default_rate_limit_burst()"
    )]
    pub rpc_rate_limit_burst: u32,

    /// How long to retain idle in-memory token buckets.
    #[serde(default = "default_rate_limit_idle_timeout_secs")]
    #[sinex_config(
        env = "SINEX_API_RATE_LIMIT_IDLE_TIMEOUT_SECS",
        default_expr = "default_rate_limit_idle_timeout_secs()"
    )]
    pub rpc_rate_limit_idle_timeout_secs: u64,

    /// Distributed rate-limit window in seconds.
    #[serde(default = "default_rate_limit_window_secs")]
    #[sinex_config(
        env = "SINEX_API_RATE_LIMIT_WINDOW_SECS",
        default_expr = "default_rate_limit_window_secs()"
    )]
    pub rpc_rate_limit_window_secs: u64,

    /// Distributed rate-limit allowance per minute.
    #[serde(default = "default_rate_limit_per_minute")]
    #[sinex_config(
        env = "SINEX_API_RATE_LIMIT_PER_MINUTE",
        default_expr = "default_rate_limit_per_minute()"
    )]
    pub rpc_rate_limit_per_minute: u32,

    /// Pipeline namespace (`SINEX_NAMESPACE`), used for NATS subject/stream
    /// isolation in tests. The SSE SubscriptionBus subscribes to
    /// `{namespace}.events.confirmations.>`; it MUST match the namespace the
    /// paired event_engine publishes confirmations under, or the bus never sees them
    /// and SSE delivery silently never completes. Unset in production.
    #[serde(default)]
    #[sinex_config(env = "SINEX_NAMESPACE")]
    pub namespace: Option<String>,
}

fn default_database_url() -> String {
    String::new()
}

fn default_tcp_listen() -> String {
    crate::api::rpc_server::DEFAULT_TCP_LISTEN.to_string()
}

fn default_content_store_path() -> String {
    // Check shared env key first; gateway-specific key is handled by the macro
    // (it reads SINEX_API_CONTENT_STORE_PATH and overrides this default).
    if let Ok(v) = std::env::var("SINEX_CONTENT_STORE_PATH") {
        return v;
    }
    std::env::var("HOME").map_or_else(
        |_| {
            sinex_primitives::environment::environment()
                .work_directory("content-store")
                .to_string_lossy()
                .into_owned()
        },
        |home| format!("{home}/.local/share/sinex/content-store"),
    )
}

fn default_state_dir() -> PathBuf {
    resolve_private_mode_state_dir(None)
}

fn default_pool_max_connections() -> u32 {
    PoolConfig::default().max_connections
}

fn default_pool_min_connections() -> u32 {
    PoolConfig::default().min_connections
}

fn default_pool_acquire_timeout_secs() -> u64 {
    PoolConfig::default().acquire_timeout_secs.as_secs()
}

fn default_max_concurrency() -> usize {
    100
}

fn default_request_timeout_secs() -> u64 {
    30
}

fn default_max_body_bytes() -> u64 {
    2 * 1024 * 1024
}

fn default_max_blob_bytes() -> usize {
    5 * 1024 * 1024
}

fn default_replay_control_timeout_secs() -> u64 {
    30
}

fn default_nats_consumer_create_timeout_secs() -> u64 {
    10
}

fn default_rate_limit_enabled() -> bool {
    true
}

fn default_rate_limit_requests_per_second() -> u32 {
    100
}

fn default_rate_limit_readonly_rps() -> u32 {
    200
}

fn default_rate_limit_write_rps() -> u32 {
    100
}

fn default_rate_limit_admin_rps() -> u32 {
    50
}

fn default_rate_limit_burst() -> u32 {
    50
}

fn default_rate_limit_idle_timeout_secs() -> u64 {
    3600
}

fn default_rate_limit_window_secs() -> u64 {
    60
}

fn default_rate_limit_per_minute() -> u32 {
    6000
}

fn default_native_messaging_read_timeout_secs() -> u64 {
    30
}

fn default_native_messaging_max_size_bytes() -> usize {
    1024 * 1024
}

impl Default for GatewayConfig {
    fn default() -> Self {
        Self {
            database_url: default_database_url(),
            tcp_listen: default_tcp_listen(),
            cors_origins: String::new(),
            pool_max_connections: default_pool_max_connections(),
            pool_min_connections: default_pool_min_connections(),
            pool_acquire_timeout_secs: default_pool_acquire_timeout_secs(),
            content_store_path: default_content_store_path(),
            state_dir: default_state_dir(),
            rpc_token: None,
            rpc_token_file: None,
            admin_token_file: None,
            nats: NatsConnectionConfig::default(),
            tls_cert: None,
            tls_key: None,
            tls_client_ca: None,
            require_client_tls: false,
            max_concurrency: default_max_concurrency(),
            request_timeout_secs: default_request_timeout_secs(),
            max_body_bytes: default_max_body_bytes(),
            max_blob_bytes: default_max_blob_bytes(),
            replay_control_timeout_secs: default_replay_control_timeout_secs(),
            nats_consumer_create_timeout_secs: default_nats_consumer_create_timeout_secs(),
            native_messaging_trusted_extensions: None,
            native_messaging_trusted_hosts: None,
            native_messaging_protocol_version: None,
            native_messaging_capabilities: None,
            native_messaging_extension_roles: None,
            native_messaging_read_timeout_secs: default_native_messaging_read_timeout_secs(),
            native_messaging_max_size_bytes: default_native_messaging_max_size_bytes(),
            rpc_rate_limit_enabled: default_rate_limit_enabled(),
            rpc_rate_limit_requests_per_sec: default_rate_limit_requests_per_second(),
            rpc_rate_limit_readonly_rps: default_rate_limit_readonly_rps(),
            rpc_rate_limit_write_rps: default_rate_limit_write_rps(),
            rpc_rate_limit_admin_rps: default_rate_limit_admin_rps(),
            rpc_rate_limit_burst: default_rate_limit_burst(),
            rpc_rate_limit_idle_timeout_secs: default_rate_limit_idle_timeout_secs(),
            rpc_rate_limit_window_secs: default_rate_limit_window_secs(),
            rpc_rate_limit_per_minute: default_rate_limit_per_minute(),
            namespace: None,
        }
    }
}

impl GatewayConfig {
    /// Post-construction normalization: read `SINEX_API_TOKEN` (with trim),
    /// and fall back to the shared `SINEX_CONTENT_STORE_PATH` override if the
    /// gateway-specific key wasn't set.
    fn normalize(mut self) -> Result<Self, SinexError> {
        // rpc_token is skipped in the macro because it needs whitespace trimming.
        if let Some(token) = sinex_primitives::env::strict_var("SINEX_API_TOKEN")? {
            self.rpc_token = Some(token.trim().to_string());
        }
        // `default_content_store_path()` reads the shared `SINEX_CONTENT_STORE_PATH`
        // leniently and silently falls back to the default on a non-UTF8 value.
        // Enforce the same strict UTF-8 contract the macro applies to other
        // env-backed fields (e.g. DATABASE_URL) so an invalid override fails loudly
        // instead of silently resolving to a different path.
        sinex_primitives::env::strict_var("SINEX_CONTENT_STORE_PATH")?;
        Ok(self)
    }

    /// Load configuration from defaults and environment variables.
    pub fn load() -> Result<Self, SinexError> {
        let mut config = Self::from_env()?;
        if config.database_url.trim().is_empty() {
            return Err(SinexError::configuration(
                "Database URL not provided — set DATABASE_URL or pass --database-url",
            ));
        }
        config.database_url = resolve_effective_database_url(&config.database_url)?;
        Ok(config)
    }

    /// Load defaults and environment overrides, then force a specific database URL.
    ///
    /// This is used by tests and helper binaries that need the normal runtime wiring
    /// (NATS, TLS, content store, auth) but provide the database URL out-of-band.
    pub fn load_with_database_url(database_url: impl Into<String>) -> Result<Self, SinexError> {
        let mut config = Self::from_env()?;
        config.database_url = database_url.into();
        if config.database_url.trim().is_empty() {
            return Err(SinexError::configuration(
                "Database URL not provided — set DATABASE_URL or pass --database-url",
            ));
        }
        config.database_url = resolve_effective_database_url(&config.database_url)?;
        Ok(config)
    }

    /// Apply CLI overrides on top of loaded config.
    #[must_use]
    pub fn with_cli_overrides(
        mut self,
        database_url: Option<String>,
        tcp_listen: Option<String>,
        cors_origins: Option<String>,
    ) -> Self {
        if let Some(url) = database_url {
            self.database_url = url;
        }
        if let Some(listen) = tcp_listen {
            self.tcp_listen = listen;
        }
        if let Some(origins) = cors_origins {
            self.cors_origins = origins;
        }
        self
    }

    /// Build a sinex-db `PoolConfig` from the flattened pool fields.
    #[must_use]
    pub fn pool_config(&self) -> PoolConfig {
        let mut config = PoolConfig::default();
        config.max_connections = self.pool_max_connections;
        config.min_connections = self.pool_min_connections;
        config.acquire_timeout_secs =
            sinex_primitives::units::Seconds::from_secs(self.pool_acquire_timeout_secs);
        config
    }

    /// Resolve and validate the content-store path.
    pub fn resolve_content_store_path(&self) -> Result<Utf8PathBuf, SinexError> {
        let sanitized = SanitizedPath::from_str_validated(&self.content_store_path)
            .map_err(|e| SinexError::validation(format!("Invalid content_store_path: {e}")))?;
        Ok(Utf8PathBuf::from(sanitized.as_str()))
    }

    /// Parse CORS origins from the comma-separated string.
    #[must_use]
    pub fn cors_origins_list(&self) -> Vec<String> {
        if self.cors_origins.is_empty() {
            Vec::new()
        } else {
            self.cors_origins
                .split(',')
                .map(|o| o.trim().to_string())
                .collect()
        }
    }

    #[must_use]
    pub fn rpc_token_path(&self) -> Option<PathBuf> {
        self.rpc_token_file
            .as_ref()
            .map(PathBuf::from)
            .or_else(|| self.admin_token_file.as_ref().map(PathBuf::from))
    }

    pub fn auth_token_from_config(&self) -> Result<(Option<String>, Option<PathBuf>), SinexError> {
        if let Some(path_str) = &self.admin_token_file {
            let path = PathBuf::from(path_str);
            let contents = std::fs::read_to_string(&path).map_err(|e| {
                SinexError::configuration("Failed to read admin token file")
                    .with_path(path.display().to_string())
                    .with_source(e.to_string())
            })?;
            return Ok((Some(contents.trim().to_string()), Some(path)));
        }

        if let Some(path_str) = &self.rpc_token_file {
            let path = PathBuf::from(path_str);
            let contents = std::fs::read_to_string(&path).map_err(|e| {
                SinexError::configuration("Failed to read RPC token file")
                    .with_path(path.display().to_string())
                    .with_source(e.to_string())
            })?;
            return Ok((Some(contents.trim().to_string()), Some(path)));
        }

        Ok((
            self.rpc_token
                .as_ref()
                .map(|token| token.trim().to_string()),
            None,
        ))
    }

    #[must_use]
    pub fn request_timeout(&self) -> Duration {
        Duration::from_secs(self.request_timeout_secs)
    }

    #[must_use]
    pub fn replay_control_timeout(&self) -> Duration {
        Duration::from_secs(self.replay_control_timeout_secs)
    }

    #[must_use]
    pub fn nats_consumer_create_timeout(&self) -> Duration {
        Duration::from_secs(self.nats_consumer_create_timeout_secs)
    }

    // SAFETY: these are known non-zero compile-time constants.
    const DEFAULT_RATE_RPS: NonZeroU32 = NonZeroU32::new(100).unwrap();
    const DEFAULT_RATE_READONLY_RPS: NonZeroU32 = NonZeroU32::new(200).unwrap();
    const DEFAULT_RATE_WRITE_RPS: NonZeroU32 = NonZeroU32::new(100).unwrap();
    const DEFAULT_RATE_ADMIN_RPS: NonZeroU32 = NonZeroU32::new(50).unwrap();
    const DEFAULT_RATE_BURST: NonZeroU32 = NonZeroU32::new(50).unwrap();
    const DEFAULT_RATE_PER_MIN: NonZeroU32 = NonZeroU32::new(6000).unwrap();

    #[must_use]
    pub fn rate_limit_requests_per_second(&self) -> NonZeroU32 {
        NonZeroU32::new(self.rpc_rate_limit_requests_per_sec).unwrap_or(Self::DEFAULT_RATE_RPS)
    }

    #[must_use]
    pub fn rate_limit_readonly_rps(&self) -> NonZeroU32 {
        NonZeroU32::new(self.rpc_rate_limit_readonly_rps).unwrap_or(Self::DEFAULT_RATE_READONLY_RPS)
    }

    #[must_use]
    pub fn rate_limit_write_rps(&self) -> NonZeroU32 {
        NonZeroU32::new(self.rpc_rate_limit_write_rps).unwrap_or(Self::DEFAULT_RATE_WRITE_RPS)
    }

    #[must_use]
    pub fn rate_limit_admin_rps(&self) -> NonZeroU32 {
        NonZeroU32::new(self.rpc_rate_limit_admin_rps).unwrap_or(Self::DEFAULT_RATE_ADMIN_RPS)
    }

    #[must_use]
    pub fn rate_limit_burst(&self) -> NonZeroU32 {
        NonZeroU32::new(self.rpc_rate_limit_burst).unwrap_or(Self::DEFAULT_RATE_BURST)
    }

    #[must_use]
    pub fn rate_limit_per_minute(&self) -> NonZeroU32 {
        NonZeroU32::new(self.rpc_rate_limit_per_minute).unwrap_or(Self::DEFAULT_RATE_PER_MIN)
    }

    #[must_use]
    pub fn nats_connection_config(&self) -> NatsConnectionConfig {
        self.nats.clone()
    }
}
