//! Schema auto-convergence engine.
//!
//! Diffs declared sea-query [`TableCreateStatement`] definitions against the
//! actual database state and emits the minimal DDL needed to bring them into
//! alignment — without touching existing data or recreating tables.
//!
//! ## How it works
//!
//! For each [`ConvergibleTable`] in the registry:
//!
//! 1. **Column convergence** — compares declared columns (from the sea-query
//!    statement) against `information_schema.columns`. Missing columns are added
//!    with `ALTER TABLE … ADD COLUMN IF NOT EXISTS`. The ADD COLUMN SQL is
//!    generated by sea-query itself via `Table::alter().add_column_if_not_exists()`,
//!    so it uses the same type system as CREATE TABLE — no custom type mapping needed.
//!
//! 2. **Legacy column removal** — drops columns listed in `columns_to_drop` with
//!    a single `ALTER TABLE … DROP COLUMN IF EXISTS …` statement.
//!
//! 3. **Named constraint convergence** — compares declared named CHECK constraints
//!    against `pg_constraint`. Missing constraints are added with `NOT VALID` and
//!    then validated in a second pass (avoids full table scan on large tables).
//!
//! 4. **Mirror table** — `audit.archived_events` mirrors `core.events` via
//!    `LIKE … INCLUDING ALL` at creation time. Since LIKE is a one-shot, new
//!    columns added to `core.events` must be explicitly mirrored. The engine
//!    handles this automatically, skipping generated columns that cannot be
//!    replicated as-is.
//!
//! 5. **Obsolete index cleanup** — drops renamed/replaced indexes in a single
//!    round trip so the replacement `IF NOT EXISTS` creations succeed cleanly.
//!
//! ## Send-safety design
//!
//! `sea_query::TableCreateStatement` contains `Rc<dyn Iden>` — it is `!Send`.
//! Holding it across `.await` points would prevent the future from being spawned
//! on tokio's thread pool. To avoid this, every function that touches a statement
//! **extracts all needed information into owned `String`s synchronously** before
//! the first `.await`. No sea-query type ever crosses an async boundary.
//!
//! ## Single source of truth
//!
//! After this module is wired in, the sea-query `create_table_statement()`
//! methods are the **only** place schema changes need to be made. Adding a column
//! there causes it to be created on fresh databases and added to existing ones
//! automatically on the next `apply()` call.

use std::collections::HashSet;

use crate::apply::ApplyError;
use crate::schema::{Events, NodeManifests, TableMeta};
use sea_query::{
    Alias, ColumnDef, ColumnSpec, ForeignKeyCreateStatement, PostgresQueryBuilder, Table,
    TableCreateStatement,
};
use sqlx::{Executor, PgPool};

// ─── Public types ────────────────────────────────────────────────────────────

/// A named CHECK constraint managed by the convergence engine.
///
/// Named constraints (as opposed to anonymous inline CHECKs in CREATE TABLE)
/// can be dropped and recreated by name, making them safe to converge without
/// data loss.
pub struct NamedConstraint {
    pub name: &'static str,
    pub expression: &'static str,
}

/// A named foreign key managed by the convergence engine.
///
/// Foreign keys declared inline in `CREATE TABLE` statements do not get added to
/// long-lived existing tables unless convergence handles them explicitly.
pub struct NamedForeignKey {
    pub name: &'static str,
    pub statement_fn: fn() -> ForeignKeyCreateStatement,
}

/// Specification for a mirror table that tracks a primary table's column set.
///
/// `audit.archived_events` is created with `LIKE core.events INCLUDING ALL`
/// which copies columns only once at creation time. This spec causes the
/// convergence engine to propagate any new columns to the mirror automatically.
pub struct MirrorSpec {
    pub schema: &'static str,
    pub table: &'static str,
    /// Legacy columns to drop from the mirror (may differ from primary).
    pub columns_to_drop: &'static [&'static str],
    /// When true, skip columns that use `.extra("GENERATED ALWAYS AS …")`.
    /// Required for the archived_events mirror since generated expressions
    /// cannot be replicated — the mirror uses plain TIMESTAMPTZ for ts_coided.
    pub skip_extra_generated: bool,
}

/// A table whose column set and named constraints are auto-converged on each
/// `apply()` call.
///
/// Uses a `fn() -> TableCreateStatement` function pointer instead of a stored
/// statement to avoid capturing `Rc<dyn Iden>` in the struct (sea-query uses
/// `Rc` internally, making `TableCreateStatement` `!Send`).
pub struct ConvergibleTable {
    pub meta: &'static TableMeta,
    /// Factory function that produces the sea-query CREATE TABLE statement.
    /// Called synchronously before any await point to extract column metadata.
    pub statement_fn: fn() -> TableCreateStatement,
    /// Named CHECK constraints that the convergence engine should ensure exist.
    pub named_constraints: Vec<NamedConstraint>,
    /// Named foreign keys that the convergence engine should ensure exist.
    pub foreign_keys: Vec<NamedForeignKey>,
    /// Columns that are no longer part of the schema and should be dropped.
    pub columns_to_drop: &'static [&'static str],
    /// Optional mirror table (e.g., audit.archived_events for core.events).
    pub mirror: Option<MirrorSpec>,
}

// ─── Column helpers ──────────────────────────────────────────────────────────

/// Returns true when a column uses either the sea-query `Generated` spec or
/// a `.extra("GENERATED ALWAYS AS …")` string — both produce generated columns.
fn col_is_generated(col: &ColumnDef) -> bool {
    col.get_column_spec().iter().any(|s| match s {
        ColumnSpec::Generated { .. } => true,
        ColumnSpec::Extra(extra) => extra.to_uppercase().contains("GENERATED"),
        _ => false,
    })
}

/// Extracts `(column_name, full ALTER TABLE ADD COLUMN IF NOT EXISTS SQL)` pairs
/// from a `TableCreateStatement`.
///
/// This is a **synchronous** function. All sea-query types (`Rc<dyn Iden>` etc.)
/// are consumed here and converted to plain `String`s that are `Send`-safe.
fn extract_column_sqls(
    stmt: &TableCreateStatement,
    schema: &str,
    table: &str,
    skip_generated: bool,
) -> Vec<(String, String)> {
    stmt.get_columns()
        .iter()
        .filter(|col| !(skip_generated && col_is_generated(col)))
        .map(|col| {
            let name = col.get_column_name();
            // sea-query renders the full ALTER TABLE … ADD COLUMN IF NOT EXISTS DDL,
            // using the same type system as the original CREATE TABLE statement.
            let sql = Table::alter()
                .table((Alias::new(schema), Alias::new(table)))
                .add_column_if_not_exists(col.clone())
                .to_string(PostgresQueryBuilder);
            (name, sql)
        })
        .collect()
}

/// Extracts just the column names from a statement (for gap reporting).
fn extract_column_names(stmt: &TableCreateStatement) -> Vec<String> {
    stmt.get_columns()
        .iter()
        .map(|col| col.get_column_name())
        .collect()
}

// ─── Database introspection ───────────────────────────────────────────────────

async fn actual_columns(pool: &PgPool, schema: &str, table: &str) -> Result<Vec<String>, ApplyError> {
    let rows = sqlx::query_scalar::<_, String>(
        "SELECT column_name
         FROM information_schema.columns
         WHERE table_schema = $1 AND table_name = $2",
    )
    .bind(schema)
    .bind(table)
    .fetch_all(pool)
    .await?;
    Ok(rows)
}

async fn actual_named_constraints(
    pool: &PgPool,
    schema: &str,
    table: &str,
) -> Result<Vec<String>, ApplyError> {
    let rows = sqlx::query_scalar::<_, String>(
        "SELECT c.conname
         FROM pg_constraint c
         JOIN pg_class r ON c.conrelid = r.oid
         JOIN pg_namespace n ON r.relnamespace = n.oid
         WHERE n.nspname = $1 AND r.relname = $2 AND c.contype = 'c'",
    )
    .bind(schema)
    .bind(table)
    .fetch_all(pool)
    .await?;
    Ok(rows)
}

async fn actual_named_foreign_keys(
    pool: &PgPool,
    schema: &str,
    table: &str,
) -> Result<Vec<String>, ApplyError> {
    let rows = sqlx::query_scalar::<_, String>(
        "SELECT c.conname
         FROM pg_constraint c
         JOIN pg_class r ON c.conrelid = r.oid
         JOIN pg_namespace n ON r.relnamespace = n.oid
         WHERE n.nspname = $1 AND r.relname = $2 AND c.contype = 'f'",
    )
    .bind(schema)
    .bind(table)
    .fetch_all(pool)
    .await?;
    Ok(rows)
}

// ─── DDL application ─────────────────────────────────────────────────────────

/// Applies `ALTER TABLE ADD COLUMN IF NOT EXISTS` for any declared column
/// not present in the actual table. Takes pre-extracted `(name, sql)` pairs
/// so no sea-query types need to be held across `.await` points.
///
/// Caller must verify the table exists before calling.
async fn add_missing_columns(
    pool: &PgPool,
    schema: &str,
    table: &str,
    declared: &[(String, String)],
) -> Result<(), ApplyError> {
    let existing: HashSet<String> =
        actual_columns(pool, schema, table).await?.into_iter().collect();

    for (name, sql) in declared {
        if !existing.contains(name) {
            pool.execute(sql.as_str()).await?;
        }
    }

    Ok(())
}

/// Drops columns that are no longer part of the declared schema, batched into
/// a single `ALTER TABLE` statement.
///
/// Caller must verify the table exists before calling.
async fn drop_legacy_columns(
    pool: &PgPool,
    schema: &str,
    table: &str,
    columns: &[&'static str],
) -> Result<(), ApplyError> {
    if columns.is_empty() {
        return Ok(());
    }
    let clauses: Vec<String> = columns
        .iter()
        .map(|col| format!("DROP COLUMN IF EXISTS {col}"))
        .collect();
    let sql = format!("ALTER TABLE {schema}.{table} {}", clauses.join(", "));
    pool.execute(sql.as_str()).await?;
    Ok(())
}

/// Ensures all named CHECK constraints are present on the table.
///
/// Missing constraints are added with `NOT VALID` (skips full table scan) and
/// then validated in a second pass. Changed constraint expressions are NOT
/// auto-converged — this function only adds missing ones.
///
/// Caller must verify the table exists before calling.
async fn converge_named_constraints(
    pool: &PgPool,
    schema: &str,
    table: &str,
    constraints: &[NamedConstraint],
) -> Result<(), ApplyError> {
    if constraints.is_empty() {
        return Ok(());
    }

    let existing: HashSet<String> = actual_named_constraints(pool, schema, table)
        .await?
        .into_iter()
        .collect();

    let missing: Vec<&NamedConstraint> = constraints
        .iter()
        .filter(|nc| !existing.contains(nc.name))
        .collect();

    if missing.is_empty() {
        return Ok(());
    }

    // Batch drop-if-exists + add NOT VALID in one ALTER TABLE.
    let clauses: Vec<String> = missing
        .iter()
        .flat_map(|nc| {
            [
                format!("DROP CONSTRAINT IF EXISTS {}", nc.name),
                format!("ADD CONSTRAINT {} CHECK ({}) NOT VALID", nc.name, nc.expression),
            ]
        })
        .collect();
    let alter = format!("ALTER TABLE {schema}.{table} {}", clauses.join(", "));
    pool.execute(alter.as_str()).await?;

    // Validate each constraint separately — allows per-constraint error isolation.
    for nc in &missing {
        let sql = format!("ALTER TABLE {schema}.{table} VALIDATE CONSTRAINT {}", nc.name);
        pool.execute(sql.as_str()).await?;
    }

    Ok(())
}

/// Ensures all named foreign keys are present on the table.
///
/// Missing foreign keys are added exactly once. Changed definitions are not
/// auto-converged; this matches the current named CHECK behavior.
async fn converge_named_foreign_keys(
    pool: &PgPool,
    schema: &str,
    table: &str,
    foreign_keys: &[(String, String)],
) -> Result<(), ApplyError> {
    if foreign_keys.is_empty() {
        return Ok(());
    }

    let existing: HashSet<String> = actual_named_foreign_keys(pool, schema, table)
        .await?
        .into_iter()
        .collect();

    for (name, sql) in foreign_keys {
        if !existing.contains(name) {
            pool.execute(sql.as_str()).await?;
        }
    }

    Ok(())
}

/// Drops indexes that have been renamed or superseded, in a single round trip.
///
/// These are one-time cleanup operations. The `IF NOT EXISTS` on the replacement
/// index creations (in `create_indexes()`) depends on the old names being gone.
async fn drop_obsolete_indexes(pool: &PgPool) -> Result<(), ApplyError> {
    // All six drops in a single round trip via the PostgreSQL simple query protocol.
    pool.execute(
        "DROP INDEX IF EXISTS core.ix_events_source_type_ts;
         DROP INDEX IF EXISTS audit.ix_archived_events_source;
         DROP INDEX IF EXISTS audit.ix_archived_events_ts_orig;
         DROP INDEX IF EXISTS audit.ix_archived_events_archived_at;
         DROP INDEX IF EXISTS audit.ix_archived_events_superseded_by_event_id;
         DROP INDEX IF EXISTS audit.ix_archived_events_source_event_ids;
         DROP INDEX IF EXISTS raw.uk_temporal_ledger_material_offset",
    )
    .await?;
    Ok(())
}

// ─── Lookup helper ────────────────────────────────────────────────────────────

/// Returns a `&'static TableMeta` from the canonical `ALL_TABLES` registry.
///
/// Panics if `qualified_name` is not registered — this is a programmer error,
/// not a runtime condition.
fn find_meta_in<'a>(tables: &'a [TableMeta], qualified_name: &str) -> Result<&'a TableMeta, ApplyError> {
    tables
        .iter()
        .find(|m| m.qualified_name == qualified_name)
        .ok_or_else(|| {
            ApplyError::Internal(format!(
                "convergence registry references unknown table metadata: {qualified_name}"
            ))
        })
}

fn find_meta(qualified_name: &str) -> Result<&'static TableMeta, ApplyError> {
    find_meta_in(crate::schema::all_tables(), qualified_name)
}

// ─── Public API ───────────────────────────────────────────────────────────────

/// The convergence registry: tables whose columns and named constraints are
/// auto-converged on each `apply()` call.
///
/// Add a table here when its `create_table_statement()` is the single source of
/// truth and you want column additions to propagate automatically to existing
/// databases without manual `ALTER TABLE` statements.
pub fn convergible_tables() -> Result<Vec<ConvergibleTable>, ApplyError> {
    Ok(vec![
        ConvergibleTable {
            meta: find_meta("core.events")?,
            statement_fn: Events::create_table_statement,
            // Named provenance constraints — identified and idempotently recreated
            // by name. Anonymous CREATE TABLE CHECKs (the XOR provenance invariant)
            // are excluded here; they're set-and-forget at table creation.
            named_constraints: vec![
                NamedConstraint {
                    name: "events_anchor_byte_non_negative",
                    expression: "anchor_byte IS NULL OR anchor_byte >= 0",
                },
                NamedConstraint {
                    name: "events_source_event_ids_non_empty",
                    expression: "source_event_ids IS NULL OR cardinality(source_event_ids) > 0",
                },
                NamedConstraint {
                    name: "events_source_event_ids_no_nulls",
                    expression: "source_event_ids IS NULL OR array_position(source_event_ids, NULL) IS NULL",
                },
                NamedConstraint {
                    name: "events_source_material_only_offsets",
                    expression: "source_material_id IS NOT NULL OR (anchor_byte IS NULL AND offset_start IS NULL AND offset_end IS NULL AND offset_kind IS NULL)",
                },
                NamedConstraint {
                    name: "events_material_anchor_required",
                    expression: "source_material_id IS NULL OR anchor_byte IS NOT NULL",
                },
                NamedConstraint {
                    name: "events_offsets_pairing",
                    expression: "(offset_start IS NULL) = (offset_end IS NULL)",
                },
                NamedConstraint {
                    name: "events_offsets_require_kind",
                    expression: "offset_kind IS NULL OR (offset_start IS NOT NULL AND offset_end IS NOT NULL)",
                },
                NamedConstraint {
                    name: "events_offset_order",
                    expression: "offset_start IS NULL OR offset_end IS NULL OR offset_end >= offset_start",
                },
                NamedConstraint {
                    name: "events_temporal_policy_valid",
                    expression: "temporal_policy IS NULL OR temporal_policy IN ('inherit_parent', 'latest_input', 'window_boundary', 'declared_effective')",
                },
                NamedConstraint {
                    name: "events_node_model_valid",
                    expression: "node_model IS NULL OR node_model IN ('transducer', 'windowed', 'scope_reconciler')",
                },
            ],
            foreign_keys: vec![NamedForeignKey {
                name: "events_node_run_id_fkey",
                statement_fn: Events::create_node_run_foreign_key,
            }],
            // node_version was the predecessor to node_run_id.
            columns_to_drop: &["node_version"],
            // audit.archived_events was created with LIKE core.events INCLUDING ALL.
            // LIKE only runs at CREATE TABLE time, so new columns added to core.events
            // must be explicitly propagated to the mirror.
            mirror: Some(MirrorSpec {
                schema: "audit",
                table: "archived_events",
                columns_to_drop: &["node_version"],
                // ts_coided is GENERATED ALWAYS AS in core.events, but must be a plain
                // TIMESTAMPTZ in audit.archived_events (the expression is dropped by
                // create_table_sql()). Skip it here — it already exists from LIKE
                // INCLUDING ALL so ADD COLUMN IF NOT EXISTS would be a no-op anyway.
                // Skipping avoids any edge-case where the expression is re-added.
                skip_extra_generated: true,
            }),
        },
        ConvergibleTable {
            meta: find_meta("core.node_manifests")?,
            statement_fn: NodeManifests::create_table_statement,
            named_constraints: vec![],
            foreign_keys: vec![],
            columns_to_drop: &[],
            mirror: None,
        },
    ])
}

#[cfg(test)]
mod tests {
    // Exception to per-crate tests/: this exercises private registry lookup helpers
    // without widening the convergence API.
    use super::*;
    use xtask::sandbox::prelude::*;

    #[sinex_test]
    async fn find_meta_surfaces_missing_registry_entries() -> TestResult<()> {
        let tables: &[TableMeta] = &[];
        let err = find_meta_in(tables, "core.missing").expect_err("missing table should fail");
        assert!(matches!(err, ApplyError::Internal(_)));
        assert_eq!(
            err.to_string(),
            "convergence registry references unknown table metadata: core.missing"
        );
        Ok(())
    }

    #[sinex_test]
    async fn convergible_tables_resolve_known_metadata() -> TestResult<()> {
        let tables = convergible_tables()?;
        assert_eq!(tables.len(), 2);
        assert_eq!(tables[0].meta.qualified_name, "core.events");
        assert_eq!(tables[1].meta.qualified_name, "core.node_manifests");
        Ok(())
    }
}

/// Converges each registered table against the live database.
///
/// Designed to be called from `apply()` after `create_tables()`. Idempotent —
/// safe to call on both fresh databases (all columns already exist, no-ops) and
/// existing databases (only new columns are added).
///
/// ## Send-safety
///
/// All sea-query statement data is extracted into `Vec<(String, String)>` before
/// the first `.await`. No `Rc`-based sea-query types cross async boundaries.
pub async fn converge_tables(
    pool: &PgPool,
    tables: &[ConvergibleTable],
) -> Result<(), ApplyError> {
    for ct in tables {
        // Phase 1 (sync): materialize column SQL from the sea-query statement.
        // `TableCreateStatement` is !Send (contains Rc<dyn Iden>), so we must
        // extract everything into owned Strings before the first await.
        // The statement is called once and used for both primary and mirror extraction.
        let (primary_cols, mirror_cols) = {
            let stmt = (ct.statement_fn)();
            let primary = extract_column_sqls(&stmt, ct.meta.schema, ct.meta.name, false);
            let mirror = ct.mirror.as_ref().map(|m| {
                let cols = extract_column_sqls(&stmt, m.schema, m.table, m.skip_extra_generated);
                (m, cols)
            });
            (primary, mirror)
        };
        let declared_foreign_keys: Vec<(String, String)> = ct
            .foreign_keys
            .iter()
            .map(|foreign_key| {
                (
                    foreign_key.name.to_string(),
                    (foreign_key.statement_fn)().to_string(PostgresQueryBuilder),
                )
            })
            .collect();

        // Phase 2 (async): apply DDL using only Send-safe String data.
        // One existence check per table — helpers skip the check since we gate here.
        let primary_exists =
            crate::apply::relation_exists(pool, ct.meta.qualified_name).await?;
        if primary_exists {
            add_missing_columns(pool, ct.meta.schema, ct.meta.name, &primary_cols).await?;
            drop_legacy_columns(pool, ct.meta.schema, ct.meta.name, ct.columns_to_drop).await?;
            converge_named_constraints(pool, ct.meta.schema, ct.meta.name, &ct.named_constraints)
                .await?;
            converge_named_foreign_keys(
                pool,
                ct.meta.schema,
                ct.meta.name,
                &declared_foreign_keys,
            )
            .await?;
        }

        if let Some((mirror, mirror_col_sqls)) = mirror_cols {
            let mirror_exists =
                crate::apply::relation_exists(pool, &format!("{}.{}", mirror.schema, mirror.table))
                    .await?;
            if mirror_exists {
                add_missing_columns(pool, mirror.schema, mirror.table, &mirror_col_sqls).await?;
                drop_legacy_columns(pool, mirror.schema, mirror.table, mirror.columns_to_drop)
                    .await?;
            }
        }
    }

    drop_obsolete_indexes(pool).await?;
    Ok(())
}

/// Reports schema gaps (missing columns, missing named constraints) for use by
/// `diff()`. Does not modify the database.
///
/// Like `converge_tables`, extracts all sea-query data synchronously before
/// any `.await` point.
pub async fn report_column_gaps(
    pool: &PgPool,
    tables: &[ConvergibleTable],
) -> Result<Vec<String>, ApplyError> {
    let mut gaps = Vec::new();

    for ct in tables {
        let qname = ct.meta.qualified_name;

        if !crate::apply::relation_exists(pool, qname).await? {
            continue;
        }

        // Sync: extract column names before first await.
        let declared_cols = {
            let stmt = (ct.statement_fn)();
            extract_column_names(&stmt)
        };

        let existing: HashSet<String> =
            actual_columns(pool, ct.meta.schema, ct.meta.name)
                .await?
                .into_iter()
                .collect();

        for name in &declared_cols {
            if !existing.contains(name) {
                gaps.push(format!("missing {qname}.{name}"));
            }
        }

        let existing_constraints: HashSet<String> =
            actual_named_constraints(pool, ct.meta.schema, ct.meta.name)
                .await?
                .into_iter()
                .collect();

        for nc in &ct.named_constraints {
            if !existing_constraints.contains(nc.name) {
                gaps.push(format!("missing {qname} constraint {}", nc.name));
            }
        }

        let existing_foreign_keys: HashSet<String> =
            actual_named_foreign_keys(pool, ct.meta.schema, ct.meta.name)
                .await?
                .into_iter()
                .collect();

        for foreign_key in &ct.foreign_keys {
            if !existing_foreign_keys.contains(foreign_key.name) {
                gaps.push(format!("missing {qname} foreign key {}", foreign_key.name));
            }
        }
    }

    Ok(gaps)
}
