//! Proposal, judgment, and finalization payloads.
//!
//! These events form the authority boundary for ambiguous or inferred facts:
//! producers emit proposals, authorized actors record judgments, and
//! deterministic finalizers emit canonical outputs from accepted/modified
//! judgments. They do not create a third provenance class; finalizer outputs
//! should use ordinary derived provenance pointing at proposal + judgment
//! events.

use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use serde_json::Value as JsonValue;
use sinex_macros::EventPayload;

use crate::authority::{Judgment, Proposal};
use crate::{Result, SinexError, Timestamp, Uuid};

/// Lifecycle state for a proposal record.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum CurationProposalStatus {
    Pending,
    Superseded,
    Judged,
    Finalized,
    Expired,
}

/// Actor class authorized to record a judgment.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum CurationJudgmentActorKind {
    User,
    Operator,
    DeterministicPolicy,
    TestFixture,
}

/// Decision recorded by an authority actor.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum CurationJudgmentDecision {
    Accept,
    Reject,
    Modify,
    Defer,
}

/// Outcome recorded by a deterministic finalizer.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum CurationFinalizationStatus {
    Applied,
    Noop,
    Conflict,
}

/// Producer-owned candidate assertion or operation.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, EventPayload)]
#[event_payload(
    source = "curation",
    event_type = "curation.proposal",
    version = "1.0.0"
)]
pub struct CurationProposalPayload {
    /// Stable proposal id generated by the producer.
    pub proposal_id: Uuid,
    /// Replay-stable key for deduplicating regenerated identical candidates.
    pub proposal_key: String,
    /// Domain-specific kind, e.g. `knowledge.tag_applied` or `task.created`.
    pub proposal_kind: String,
    /// Optional existing object being modified.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub target_ref: Option<String>,
    /// Candidate canonical event source to emit if finalized.
    pub candidate_source: String,
    /// Candidate canonical event type to emit if finalized.
    pub candidate_event_type: String,
    /// Candidate canonical payload.
    pub candidate_payload: JsonValue,
    /// Shared authority proposal, when this curation proposal is governed by
    /// the `Proposal -> Judgment -> Operation` authority seam.
    ///
    /// Legacy curation proposals can still use the curation-local fields above
    /// for replay/listing compatibility. Finalizers must prefer this shared
    /// DTO when it is present so confidence cannot become authority.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub authority_proposal: Option<Proposal<JsonValue>>,
    /// Parent event evidence used by the producer.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub evidence_event_ids: Vec<Uuid>,
    /// Source material evidence used by the producer.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub evidence_material_ids: Vec<Uuid>,
    /// Producer identifier and version, e.g. `fixture-tagger@1`.
    pub producer: String,
    /// Confidence in `[0.0, 1.0]`; consumers must not treat it as authority.
    pub confidence: f64,
    /// Safe display rationale.
    pub rationale: String,
    pub status: CurationProposalStatus,
}

/// Authority-owned judgment over one proposal.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, EventPayload)]
#[event_payload(
    source = "curation",
    event_type = "curation.judgment",
    version = "1.0.0"
)]
pub struct CurationJudgmentPayload {
    pub judgment_id: Uuid,
    pub proposal_id: Uuid,
    pub actor_kind: CurationJudgmentActorKind,
    pub actor_id: String,
    pub decision: CurationJudgmentDecision,
    /// Shared authority judgment for proposals carrying
    /// [`CurationProposalPayload::authority_proposal`].
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub authority_judgment: Option<Judgment>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub corrected_payload: Option<JsonValue>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    pub judged_at: Timestamp,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub authorization_context: Option<JsonValue>,
}

impl CurationJudgmentPayload {
    /// Payload a finalizer should use for this judgment, if any.
    pub fn effective_payload(&self, proposal: &CurationProposalPayload) -> Result<JsonValue> {
        if self.proposal_id != proposal.proposal_id {
            return Err(
                SinexError::validation("judgment references a different proposal")
                    .with_context("judgment_proposal_id", self.proposal_id.to_string())
                    .with_context("proposal_id", proposal.proposal_id.to_string()),
            );
        }

        if let Some(authority_proposal) = proposal.authority_proposal.clone() {
            let authority_judgment = self.authority_judgment.as_ref().ok_or_else(|| {
                SinexError::validation(
                    "authority-backed proposal requires a shared authority judgment",
                )
                .with_context("proposal_id", proposal.proposal_id.to_string())
                .with_context("judgment_id", self.judgment_id.to_string())
            })?;
            return authority_proposal.apply(authority_judgment);
        }

        match self.decision {
            CurationJudgmentDecision::Accept => Ok(proposal.candidate_payload.clone()),
            CurationJudgmentDecision::Modify => self.corrected_payload.clone().ok_or_else(|| {
                SinexError::validation("modify judgment requires corrected_payload")
                    .with_context("proposal_id", proposal.proposal_id.to_string())
                    .with_context("judgment_id", self.judgment_id.to_string())
            }),
            CurationJudgmentDecision::Reject | CurationJudgmentDecision::Defer => Err(
                SinexError::validation("only accept or modify judgments can be finalized")
                    .with_context("proposal_id", proposal.proposal_id.to_string())
                    .with_context("judgment_id", self.judgment_id.to_string()),
            ),
        }
    }
}

/// Deterministic record of applying a judged proposal.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, EventPayload)]
#[event_payload(
    source = "curation",
    event_type = "curation.finalized",
    version = "1.0.0"
)]
pub struct CurationFinalizedPayload {
    pub finalization_id: Uuid,
    pub proposal_id: Uuid,
    pub judgment_id: Uuid,
    pub output_source: String,
    pub output_event_type: String,
    pub output_payload: JsonValue,
    pub status: CurationFinalizationStatus,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub caveat: Option<String>,
    pub finalized_at: Timestamp,
}

impl CurationFinalizedPayload {
    /// Build the deterministic finalizer output for an accepted or modified
    /// judgment.
    pub fn from_judgment(
        finalization_id: Uuid,
        proposal: &CurationProposalPayload,
        judgment: &CurationJudgmentPayload,
        finalized_at: Timestamp,
    ) -> Result<Self> {
        let output_payload = judgment.effective_payload(proposal)?;
        Ok(Self {
            finalization_id,
            proposal_id: proposal.proposal_id,
            judgment_id: judgment.judgment_id,
            output_source: proposal.candidate_source.clone(),
            output_event_type: proposal.candidate_event_type.clone(),
            output_payload,
            status: CurationFinalizationStatus::Applied,
            caveat: None,
            finalized_at,
        })
    }
}

#[cfg(any(test, feature = "testing"))]
impl CurationProposalPayload {
    #[must_use]
    pub fn test_fixture_tag() -> Self {
        Self {
            proposal_id: Uuid::from_u128(1),
            proposal_key: "fixture:knowledge-tag:test-note:review".to_string(),
            proposal_kind: "knowledge.tag_applied".to_string(),
            target_ref: Some("entity:00000000-0000-0000-0000-000000000002".to_string()),
            candidate_source: "knowledge-graph".to_string(),
            candidate_event_type: "knowledge.tag_applied".to_string(),
            candidate_payload: serde_json::json!({
                "entity_id": "00000000-0000-0000-0000-000000000002",
                "tag_name": "review",
                "tag_source": "curation.fixture"
            }),
            authority_proposal: None,
            evidence_event_ids: vec![Uuid::from_u128(3)],
            evidence_material_ids: vec![Uuid::from_u128(4)],
            producer: "fixture-tagger@1".to_string(),
            confidence: 0.82,
            rationale: "deterministic fixture matched the note title".to_string(),
            status: CurationProposalStatus::Pending,
        }
    }
}

#[cfg(any(test, feature = "testing"))]
impl CurationJudgmentPayload {
    #[must_use]
    pub fn test_accept(proposal_id: Uuid) -> Self {
        Self {
            judgment_id: Uuid::from_u128(5),
            proposal_id,
            actor_kind: CurationJudgmentActorKind::TestFixture,
            actor_id: "fixture-judge".to_string(),
            decision: CurationJudgmentDecision::Accept,
            authority_judgment: None,
            corrected_payload: None,
            comment: Some("fixture accepts proposal".to_string()),
            judged_at: Timestamp::UNIX_EPOCH,
            authorization_context: None,
        }
    }
}
