use super::TableDef;
use sea_query::{Alias, ColumnDef, Expr, Index, IndexOrder, PostgresQueryBuilder, Table};

/// Processor manifests table schema definition
#[derive(Copy, Clone)]
pub struct ProcessorManifests;

impl TableDef for ProcessorManifests {
    fn table_name() -> &'static str {
        "processor_manifests"
    }
    fn schema_name() -> &'static str {
        "core"
    }
    fn primary_key() -> &'static str {
        "id"
    }
}

impl ProcessorManifests {
    pub const TABLE: &'static str = "processor_manifests";
    pub const SCHEMA: &'static str = "core";

    pub const ID: &'static str = "id";
    pub const NAME: &'static str = "name";
    pub const VERSION: &'static str = "version";
    pub const DESCRIPTION: &'static str = "description";
    pub const PROCESSOR_TYPE: &'static str = "processor_type";
    pub const INPUT_SCHEMAS: &'static str = "input_schemas";
    pub const OUTPUT_SCHEMAS: &'static str = "output_schemas";
    pub const CONFIGURATION_SCHEMA: &'static str = "configuration_schema";
    pub const RUNTIME_REQUIREMENTS: &'static str = "runtime_requirements";
    pub const DEPLOYMENT_STATUS: &'static str = "deployment_status";
    pub const CREATED_AT: &'static str = "created_at";
    pub const UPDATED_AT: &'static str = "updated_at";
    pub const BUILD_METADATA: &'static str = "build_metadata";

    /// Create the processor manifests table
    pub fn create_table() -> String {
        Table::create()
            .table((Alias::new(Self::SCHEMA), Alias::new(Self::TABLE)))
            .if_not_exists()
            .col(
                ColumnDef::new(Alias::new(Self::ID))
                    .integer()
                    .not_null()
                    .primary_key()
                    .extra("GENERATED BY DEFAULT AS IDENTITY"),
            )
            .col(ColumnDef::new(Alias::new(Self::NAME)).text().not_null())
            .col(ColumnDef::new(Alias::new(Self::VERSION)).text().not_null())
            .col(ColumnDef::new(Alias::new(Self::DESCRIPTION)).text())
            .col(
                ColumnDef::new(Alias::new(Self::PROCESSOR_TYPE))
                    .text()
                    .not_null(),
            )
            .col(
                ColumnDef::new(Alias::new(Self::INPUT_SCHEMAS))
                    .json_binary()
                    .default(Expr::cust("'[]'::jsonb")),
            )
            .col(
                ColumnDef::new(Alias::new(Self::OUTPUT_SCHEMAS))
                    .json_binary()
                    .default(Expr::cust("'[]'::jsonb")),
            )
            .col(ColumnDef::new(Alias::new(Self::CONFIGURATION_SCHEMA)).json_binary())
            .col(
                ColumnDef::new(Alias::new(Self::RUNTIME_REQUIREMENTS))
                    .json_binary()
                    .default(Expr::cust("'{}'::jsonb")),
            )
            .col(
                ColumnDef::new(Alias::new(Self::DEPLOYMENT_STATUS))
                    .text()
                    .default("inactive"),
            )
            .col(
                ColumnDef::new(Alias::new(Self::CREATED_AT))
                    .timestamp_with_time_zone()
                    .not_null()
                    .default(Expr::current_timestamp()),
            )
            .col(
                ColumnDef::new(Alias::new(Self::UPDATED_AT))
                    .timestamp_with_time_zone()
                    .not_null()
                    .default(Expr::current_timestamp()),
            )
            .col(
                ColumnDef::new(Alias::new(Self::BUILD_METADATA))
                    .json_binary()
                    .default(Expr::cust("'{}'::jsonb")),
            )
            .build(PostgresQueryBuilder)
    }

    /// Create indexes for the processor manifests table
    pub fn create_indexes() -> Vec<String> {
        vec![
            // Unique index on (name, version)
            Index::create()
                .table((Alias::new(Self::SCHEMA), Alias::new(Self::TABLE)))
                .name("idx_processor_manifests_name_version")
                .col(Alias::new(Self::NAME))
                .col(Alias::new(Self::VERSION))
                .unique()
                .build(PostgresQueryBuilder),
            // Index on deployment_status
            Index::create()
                .table((Alias::new(Self::SCHEMA), Alias::new(Self::TABLE)))
                .name("idx_processor_manifests_status")
                .col(Alias::new(Self::DEPLOYMENT_STATUS))
                .build(PostgresQueryBuilder),
        ]
    }
}

/// Processor checkpoints table schema definition
#[derive(Copy, Clone)]
pub struct ProcessorCheckpoints;

impl TableDef for ProcessorCheckpoints {
    fn table_name() -> &'static str {
        "processor_checkpoints"
    }
    fn schema_name() -> &'static str {
        "core"
    }
    fn primary_key() -> &'static str {
        "id"
    }
}

impl ProcessorCheckpoints {
    pub const TABLE: &'static str = "processor_checkpoints";
    pub const SCHEMA: &'static str = "core";

    pub const ID: &'static str = "id";
    pub const PROCESSOR_NAME: &'static str = "processor_name";
    pub const PROCESSOR_VERSION: &'static str = "processor_version";
    pub const CHECKPOINT_TYPE: &'static str = "checkpoint_type";
    pub const STREAM_ID: &'static str = "stream_id";
    pub const POSITION: &'static str = "position";
    pub const SEQUENCE_NUMBER: &'static str = "sequence_number";
    pub const TIMESTAMP: &'static str = "timestamp";
    pub const STATE_DATA: &'static str = "state_data";
    pub const METRICS: &'static str = "metrics";
    pub const ERROR_COUNT: &'static str = "error_count";
    pub const LAST_ERROR: &'static str = "last_error";
    pub const CREATED_AT: &'static str = "created_at";
    pub const UPDATED_AT: &'static str = "updated_at";
    pub const PROCESSING_DURATION_MS: &'static str = "processing_duration_ms";
    pub const EVENTS_PROCESSED: &'static str = "events_processed";
    pub const LAST_EVENT_ID: &'static str = "last_event_id";

    /// Create the processor checkpoints table
    pub fn create_table() -> String {
        Table::create()
            .table((Alias::new(Self::SCHEMA), Alias::new(Self::TABLE)))
            .if_not_exists()
            .col(
                ColumnDef::new(Alias::new(Self::ID))
                    .custom(Alias::new("ULID"))
                    .primary_key()
                    .default(Expr::cust("gen_ulid()")),
            )
            .col(
                ColumnDef::new(Alias::new(Self::PROCESSOR_NAME))
                    .text()
                    .not_null(),
            )
            .col(
                ColumnDef::new(Alias::new(Self::PROCESSOR_VERSION))
                    .text()
                    .not_null(),
            )
            .col(
                ColumnDef::new(Alias::new(Self::CHECKPOINT_TYPE))
                    .text()
                    .not_null(),
            )
            .col(ColumnDef::new(Alias::new(Self::STREAM_ID)).text())
            .col(ColumnDef::new(Alias::new(Self::POSITION)).text())
            .col(ColumnDef::new(Alias::new(Self::SEQUENCE_NUMBER)).big_integer())
            .col(
                ColumnDef::new(Alias::new(Self::TIMESTAMP))
                    .timestamp_with_time_zone()
                    .not_null(),
            )
            .col(
                ColumnDef::new(Alias::new(Self::STATE_DATA))
                    .json_binary()
                    .default(Expr::cust("'{}'::jsonb")),
            )
            .col(
                ColumnDef::new(Alias::new(Self::METRICS))
                    .json_binary()
                    .default(Expr::cust("'{}'::jsonb")),
            )
            .col(
                ColumnDef::new(Alias::new(Self::ERROR_COUNT))
                    .integer()
                    .default(0),
            )
            .col(ColumnDef::new(Alias::new(Self::LAST_ERROR)).text())
            .col(
                ColumnDef::new(Alias::new(Self::CREATED_AT))
                    .timestamp_with_time_zone()
                    .not_null()
                    .default(Expr::current_timestamp()),
            )
            .col(
                ColumnDef::new(Alias::new(Self::UPDATED_AT))
                    .timestamp_with_time_zone()
                    .not_null()
                    .default(Expr::current_timestamp()),
            )
            .col(ColumnDef::new(Alias::new(Self::PROCESSING_DURATION_MS)).big_integer())
            .col(ColumnDef::new(Alias::new(Self::EVENTS_PROCESSED)).big_integer())
            .col(ColumnDef::new(Alias::new(Self::LAST_EVENT_ID)).custom(Alias::new("ULID")))
            .build(PostgresQueryBuilder)
    }

    /// Create indexes for the processor checkpoints table
    pub fn create_indexes() -> Vec<String> {
        vec![
            // Index on processor name and version
            Index::create()
                .table((Alias::new(Self::SCHEMA), Alias::new(Self::TABLE)))
                .name("idx_processor_checkpoints_processor")
                .col(Alias::new(Self::PROCESSOR_NAME))
                .col(Alias::new(Self::PROCESSOR_VERSION))
                .build(PostgresQueryBuilder),
            // Index on stream_id for stream-specific queries
            format!(
                "CREATE INDEX idx_processor_checkpoints_stream ON {}.{} ({}) WHERE {} IS NOT NULL",
                Self::SCHEMA,
                Self::TABLE,
                Self::STREAM_ID,
                Self::STREAM_ID
            ),
            // Index on timestamp for time-based queries
            Index::create()
                .table((Alias::new(Self::SCHEMA), Alias::new(Self::TABLE)))
                .name("idx_processor_checkpoints_timestamp")
                .col((Alias::new(Self::TIMESTAMP), IndexOrder::Desc))
                .build(PostgresQueryBuilder),
            // Composite index for latest checkpoint queries
            Index::create()
                .table((Alias::new(Self::SCHEMA), Alias::new(Self::TABLE)))
                .name("idx_processor_checkpoints_latest")
                .col(Alias::new(Self::PROCESSOR_NAME))
                .col(Alias::new(Self::CHECKPOINT_TYPE))
                .col((Alias::new(Self::TIMESTAMP), IndexOrder::Desc))
                .build(PostgresQueryBuilder),
        ]
    }
}
