use crate::schema::TableDef;
use sea_query::{Alias, ColumnDef, Expr, Index, IndexOrder, PostgresQueryBuilder, Table};

/// Processor manifests table schema definition
#[derive(Copy, Clone)]
pub struct ProcessorManifests;

impl TableDef for ProcessorManifests {
    fn table_name() -> &'static str {
        "processor_manifests"
    }
    fn schema_name() -> &'static str {
        "core"
    }
    fn primary_key() -> &'static str {
        "id"
    }
}

impl ProcessorManifests {
    pub const TABLE: &'static str = "processor_manifests";
    pub const SCHEMA: &'static str = "core";

    pub const ID: &'static str = "id";
    pub const NAME: &'static str = "name";
    pub const VERSION: &'static str = "version";
    pub const DESCRIPTION: &'static str = "description";
    pub const PROCESSOR_TYPE: &'static str = "processor_type";
    pub const INPUT_SCHEMAS: &'static str = "input_schemas";
    pub const OUTPUT_SCHEMAS: &'static str = "output_schemas";
    pub const CONFIGURATION_SCHEMA: &'static str = "configuration_schema";
    pub const RUNTIME_REQUIREMENTS: &'static str = "runtime_requirements";
    pub const DEPLOYMENT_STATUS: &'static str = "deployment_status";
    pub const CREATED_AT: &'static str = "created_at";
    pub const UPDATED_AT: &'static str = "updated_at";
    pub const BUILD_METADATA: &'static str = "build_metadata";

    /// Create the processor manifests table
    pub fn create_table() -> String {
        Table::create()
            .table((Alias::new(Self::SCHEMA), Alias::new(Self::TABLE)))
            .if_not_exists()
            .col(
                ColumnDef::new(Alias::new(Self::ID))
                    .integer()
                    .not_null()
                    .primary_key()
                    .extra("GENERATED BY DEFAULT AS IDENTITY"),
            )
            .col(ColumnDef::new(Alias::new(Self::NAME)).text().not_null())
            .col(ColumnDef::new(Alias::new(Self::VERSION)).text().not_null())
            .col(ColumnDef::new(Alias::new(Self::DESCRIPTION)).text())
            .col(
                ColumnDef::new(Alias::new(Self::PROCESSOR_TYPE))
                    .text()
                    .not_null(),
            )
            .col(
                ColumnDef::new(Alias::new(Self::INPUT_SCHEMAS))
                    .json_binary()
                    .default(Expr::cust("'[]'::jsonb")),
            )
            .col(
                ColumnDef::new(Alias::new(Self::OUTPUT_SCHEMAS))
                    .json_binary()
                    .default(Expr::cust("'[]'::jsonb")),
            )
            .col(ColumnDef::new(Alias::new(Self::CONFIGURATION_SCHEMA)).json_binary())
            .col(
                ColumnDef::new(Alias::new(Self::RUNTIME_REQUIREMENTS))
                    .json_binary()
                    .default(Expr::cust("'{}'::jsonb")),
            )
            .col(
                ColumnDef::new(Alias::new(Self::DEPLOYMENT_STATUS))
                    .text()
                    .default("inactive"),
            )
            .col(
                ColumnDef::new(Alias::new(Self::CREATED_AT))
                    .timestamp_with_time_zone()
                    .not_null()
                    .default(Expr::current_timestamp()),
            )
            .col(
                ColumnDef::new(Alias::new(Self::UPDATED_AT))
                    .timestamp_with_time_zone()
                    .not_null()
                    .default(Expr::current_timestamp()),
            )
            .col(
                ColumnDef::new(Alias::new(Self::BUILD_METADATA))
                    .json_binary()
                    .default(Expr::cust("'{}'::jsonb")),
            )
            .build(PostgresQueryBuilder)
    }

    /// Create indexes for the processor manifests table
    pub fn create_indexes() -> Vec<String> {
        vec![
            // Unique index on (name, version)
            Index::create()
                .table((Alias::new(Self::SCHEMA), Alias::new(Self::TABLE)))
                .name("idx_processor_manifests_name_version")
                .col(Alias::new(Self::NAME))
                .col(Alias::new(Self::VERSION))
                .unique()
                .build(PostgresQueryBuilder),
            // Index on deployment_status
            Index::create()
                .table((Alias::new(Self::SCHEMA), Alias::new(Self::TABLE)))
                .name("idx_processor_manifests_status")
                .col(Alias::new(Self::DEPLOYMENT_STATUS))
                .build(PostgresQueryBuilder),
        ]
    }

    /// Create constraints (none needed)
    pub fn create_constraints() -> Vec<String> {
        vec![]
    }
}

/// Processor checkpoints table schema definition
#[derive(Copy, Clone)]
pub struct ProcessorCheckpoints;

impl TableDef for ProcessorCheckpoints {
    fn table_name() -> &'static str {
        "processor_checkpoints"
    }
    fn schema_name() -> &'static str {
        "core"
    }
    fn primary_key() -> &'static str {
        "id"
    }
}

impl ProcessorCheckpoints {
    pub const TABLE: &'static str = "processor_checkpoints";
    pub const SCHEMA: &'static str = "core";

    pub const ID: &'static str = "id";
    pub const PROCESSOR_NAME: &'static str = "processor_name";
    pub const CONSUMER_GROUP: &'static str = "consumer_group";
    pub const CONSUMER_NAME: &'static str = "consumer_name";
    pub const LAST_PROCESSED_ID: &'static str = "last_processed_id";
    pub const LAST_PROCESSED_TS: &'static str = "last_processed_ts";
    pub const PROCESSED_COUNT: &'static str = "processed_count";
    pub const CHECKPOINT_DATA: &'static str = "checkpoint_data";
    pub const STATE_DATA: &'static str = "state_data";
    pub const CHECKPOINT_VERSION: &'static str = "checkpoint_version";
    pub const LAST_ACTIVITY: &'static str = "last_activity";
    pub const CREATED_AT: &'static str = "created_at";
    pub const UPDATED_AT: &'static str = "updated_at";

    /// Create the processor checkpoints table
    pub fn create_table() -> String {
        Table::create()
            .table((Alias::new(Self::SCHEMA), Alias::new(Self::TABLE)))
            .if_not_exists()
            .col(
                ColumnDef::new(Alias::new(Self::ID))
                    .custom(Alias::new("ULID"))
                    .primary_key()
                    .default(Expr::cust("gen_ulid()")),
            )
            .col(ColumnDef::new(Alias::new(Self::NAME)).text().not_null())
            .col(
                ColumnDef::new(Alias::new(Self::CONSUMER_GROUP))
                    .text()
                    .not_null(),
            )
            .col(
                ColumnDef::new(Alias::new(Self::CONSUMER_NAME))
                    .text()
                    .not_null(),
            )
            .col(ColumnDef::new(Alias::new(Self::LAST_PROCESSED_ID)).custom(Alias::new("ULID")))
            .col(ColumnDef::new(Alias::new(Self::LAST_PROCESSED_TS)).timestamp_with_time_zone())
            .col(
                ColumnDef::new(Alias::new(Self::PROCESSED_COUNT))
                    .big_integer()
                    .not_null()
                    .default(0),
            )
            .col(ColumnDef::new(Alias::new(Self::CHECKPOINT_DATA)).json_binary())
            .col(ColumnDef::new(Alias::new(Self::STATE_DATA)).json_binary())
            .col(
                ColumnDef::new(Alias::new(Self::CHECKPOINT_VERSION))
                    .integer()
                    .not_null()
                    .default(1),
            )
            .col(
                ColumnDef::new(Alias::new(Self::LAST_ACTIVITY))
                    .timestamp_with_time_zone()
                    .not_null()
                    .default(Expr::current_timestamp()),
            )
            .col(
                ColumnDef::new(Alias::new(Self::CREATED_AT))
                    .timestamp_with_time_zone()
                    .not_null()
                    .default(Expr::current_timestamp()),
            )
            .col(
                ColumnDef::new(Alias::new(Self::UPDATED_AT))
                    .timestamp_with_time_zone()
                    .not_null()
                    .default(Expr::current_timestamp()),
            )
            .build(PostgresQueryBuilder)
    }

    /// Create indexes for the processor checkpoints table
    pub fn create_indexes() -> Vec<String> {
        vec![
            // Unique index on (processor_name, consumer_group, consumer_name)
            Index::create()
                .table((Alias::new(Self::SCHEMA), Alias::new(Self::TABLE)))
                .name("idx_processor_checkpoints_unique")
                .col(Alias::new(Self::PROCESSOR_NAME))
                .col(Alias::new(Self::CONSUMER_GROUP))
                .col(Alias::new(Self::CONSUMER_NAME))
                .unique()
                .build(PostgresQueryBuilder),
            // Index on last_activity for cleanup queries
            Index::create()
                .table((Alias::new(Self::SCHEMA), Alias::new(Self::TABLE)))
                .name("idx_processor_checkpoints_activity")
                .col((Alias::new(Self::LAST_ACTIVITY), IndexOrder::Desc))
                .build(PostgresQueryBuilder),
        ]
    }

    /// Create constraints
    pub fn create_constraints() -> Vec<String> {
        vec![
            // Create named constraint for ON CONFLICT handling
            format!(
                "ALTER TABLE {}.{} ADD CONSTRAINT unique_processor_consumer UNIQUE ({}, {}, {})",
                Self::SCHEMA,
                Self::TABLE,
                Self::PROCESSOR_NAME,
                Self::CONSUMER_GROUP,
                Self::CONSUMER_NAME
            ),
        ]
    }
}
