//! Event source trait and context for satellite event sources

use crate::{grpc_client::EventBatcher, IngestClient, SatelliteError, SatelliteResult};
use async_trait::async_trait;
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use sinex_core::RawEvent;
use sinex_ulid::Ulid;
use std::collections::HashMap;
use std::time::Duration;
use tokio::sync::mpsc;
use tracing::{debug, error, info, warn};

/// Context passed to event sources during initialization
#[derive(Debug)]
pub struct EventSourceContext {
    /// Service name
    pub service_name: String,

    /// Hostname where the service is running
    pub host: String,

    /// Working directory for temporary files
    pub work_dir: std::path::PathBuf,

    /// Whether running in dry-run mode
    pub dry_run: bool,

    /// Source-specific configuration
    pub config: HashMap<String, serde_json::Value>,

    /// Channel for sending events to the ingestion pipeline
    pub event_sender: mpsc::UnboundedSender<RawEvent>,
}

/// Arguments for scanner mode execution
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScannerArgs {
    /// Paths to scan (directories, files, databases, etc.)
    pub paths: Vec<String>,
    
    /// Time range filter for historical data
    pub time_range: Option<(DateTime<Utc>, DateTime<Utc>)>,
    
    /// Dry run mode - don't write events, just analyze
    pub dry_run: bool,
    
    /// Interactive mode - prompt user for decisions
    pub interactive: bool,
    
    /// Maximum events to generate (0 = unlimited)
    pub max_events: u64,
    
    /// Skip events that already exist in the database
    pub skip_existing: bool,
}

impl Default for ScannerArgs {
    fn default() -> Self {
        Self {
            paths: Vec::new(),
            time_range: None,
            dry_run: false,
            interactive: false,
            max_events: 0,
            skip_existing: true,
        }
    }
}

/// Report generated by scanner mode execution
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScanReport {
    /// Total events generated
    pub events_generated: u64,
    
    /// Duration of the scan operation
    pub duration: Duration,
    
    /// Blob ID if file was stored (for large files/databases)
    pub blob_id: Option<Ulid>,
    
    /// Time range covered by the scan
    pub time_range: Option<(DateTime<Utc>, DateTime<Utc>)>,
    
    /// Hash for deduplication (e.g., git-annex hash)
    pub content_hash: Option<String>,
    
    /// Source-specific statistics
    pub source_stats: HashMap<String, u64>,
    
    /// Version information for reproducibility
    pub version_info: VersionInfo,
    
    /// Paths that were successfully processed
    pub processed_paths: Vec<String>,
    
    /// Paths that failed processing with error messages
    pub failed_paths: Vec<(String, String)>,
}

/// Version information for scan reproducibility
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VersionInfo {
    /// Git revision hash of the scanner implementation
    pub git_revision: String,
    
    /// Hash of the binary (blake3 of the executable)
    pub binary_hash: String,
    
    /// Component name and version
    pub component_version: String,
    
    /// Timestamp when scan was executed
    pub scan_timestamp: DateTime<Utc>,
}

/// Trait that all event source satellites must implement
/// 
/// This trait supports dual-mode operation:
/// - **Sensor mode**: Real-time event streaming via `start_streaming()`
/// - **Scanner mode**: Batch historical processing via `run_scanner()`
#[async_trait]
pub trait EventSource: Send + Sync {
    /// Initialize the event source with the given context
    async fn initialize(&mut self, ctx: EventSourceContext) -> SatelliteResult<()>;

    /// Start streaming events (sensor mode)
    /// This should run indefinitely until a shutdown signal is received
    async fn start_streaming(&mut self) -> SatelliteResult<()>;

    /// Graceful shutdown
    async fn shutdown(&mut self) -> SatelliteResult<()> {
        info!("Event source shutting down");
        Ok(())
    }

    /// Health check
    async fn health_check(&self) -> SatelliteResult<bool> {
        Ok(true)
    }

    /// Get source name (used for event tagging)
    fn source_name(&self) -> &str;

    /// Get supported event types
    fn event_types(&self) -> Vec<&str> {
        vec![]
    }

    // ===== Dual-Mode Extensions =====
    
    /// Check if this source supports sensor mode (real-time monitoring)
    fn supports_sensor(&self) -> bool {
        true // Default: most sources are sensors
    }
    
    /// Check if this source supports scanner mode (batch historical processing)
    fn supports_scanner(&self) -> bool {
        false // Default: opt-in for scanner support
    }
    
    /// Run in scanner mode for batch historical processing
    /// 
    /// This method should:
    /// 1. Discover or validate paths if args.paths is empty
    /// 2. Process historical data within time_range if specified
    /// 3. Generate events and send them via the event_sender from context
    /// 4. Return comprehensive report with timing and statistics
    /// 5. Support dry_run mode for analysis without event generation
    /// 6. Handle interactive mode with user prompts if needed
    async fn run_scanner(
        &mut self,
        args: ScannerArgs,
    ) -> SatelliteResult<ScanReport> {
        let _ = args; // Suppress unused warning
        Err(SatelliteError::EventSource(
            "Scanner mode not supported by this source".to_string()
        ))
    }

    /// Get scanner-specific configuration schema
    /// Returns JSON schema for validating scanner arguments
    fn scanner_config_schema(&self) -> Option<serde_json::Value> {
        None
    }

    /// Estimate scanner operation scope
    /// Returns estimated number of events and processing time
    async fn estimate_scanner_scope(&self, args: &ScannerArgs) -> SatelliteResult<ScannerEstimate> {
        let _ = args;
        Ok(ScannerEstimate::default())
    }
}

/// Estimation of scanner operation scope
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScannerEstimate {
    /// Estimated number of events to be generated
    pub estimated_events: u64,
    
    /// Estimated processing duration
    pub estimated_duration: Duration,
    
    /// Estimated data size to be processed
    pub estimated_data_size: u64,
    
    /// Number of paths that will be processed
    pub estimated_paths: u64,
    
    /// Warnings about potential issues
    pub warnings: Vec<String>,
}

impl Default for ScannerEstimate {
    fn default() -> Self {
        Self {
            estimated_events: 0,
            estimated_duration: Duration::from_secs(0),
            estimated_data_size: 0,
            estimated_paths: 0,
            warnings: Vec::new(),
        }
    }
}

/// Event source runner that manages the lifecycle of an event source
pub struct EventSourceRunner<T: EventSource> {
    source: T,
    context: Option<EventSourceContext>,
    ingest_client: IngestClient,
    batcher: Option<EventBatcher>,
    shutdown_receiver: Option<tokio::sync::oneshot::Receiver<()>>,
}

impl<T: EventSource + 'static> EventSourceRunner<T> {
    /// Create a new event source runner
    pub fn new(source: T, ingest_client: IngestClient) -> Self {
        Self {
            source,
            context: None,
            ingest_client,
            batcher: None,
            shutdown_receiver: None,
        }
    }

    /// Initialize the event source with configuration
    pub async fn initialize(
        &mut self,
        service_name: String,
        config: HashMap<String, serde_json::Value>,
        batch_size: usize,
        batch_timeout_secs: u64,
        work_dir: std::path::PathBuf,
        dry_run: bool,
    ) -> SatelliteResult<()> {
        // Create event channel
        let (event_sender, mut event_receiver) = mpsc::unbounded_channel::<RawEvent>();

        // Create shutdown channel
        let (shutdown_sender, shutdown_receiver) = tokio::sync::oneshot::channel();
        self.shutdown_receiver = Some(shutdown_receiver);

        // Create event batcher
        let batcher = EventBatcher::new(self.ingest_client.clone(), batch_size, batch_timeout_secs);
        self.batcher = Some(batcher);

        // Get hostname
        let host = gethostname::gethostname().to_string_lossy().to_string();

        // Create context
        let context = EventSourceContext {
            service_name: service_name.clone(),
            host,
            work_dir,
            dry_run,
            config,
            event_sender,
        };

        // Initialize the event source
        self.source.initialize(context).await?;

        info!(
            service = %service_name,
            source = %self.source.source_name(),
            "Event source initialized"
        );

        // Start event processing task
        let mut batcher = self.batcher.take().unwrap();
        let source_name = self.source.source_name().to_string();
        
        tokio::spawn(async move {
            let mut flush_interval = tokio::time::interval(tokio::time::Duration::from_secs(1));
            
            loop {
                tokio::select! {
                    // Process incoming events
                    event = event_receiver.recv() => {
                        match event {
                            Some(event) => {
                                if let Err(e) = Self::handle_event(&mut batcher, event, dry_run).await {
                                    error!(
                                        source = %source_name,
                                        error = %e,
                                        "Failed to process event"
                                    );
                                }
                            }
                            None => {
                                debug!("Event channel closed, stopping event processor");
                                break;
                            }
                        }
                    }

                    // Periodic flush
                    _ = flush_interval.tick() => {
                        if let Err(e) = batcher.flush().await {
                            error!(
                                source = %source_name,
                                error = %e,
                                "Failed to flush event batch"
                            );
                        }
                    }
                }
            }

            // Final flush on shutdown
            if let Err(e) = batcher.flush().await {
                error!(
                    source = %source_name,
                    error = %e,
                    "Failed to flush final event batch"
                );
            }

            info!(source = %source_name, "Event processor stopped");
        });

        Ok(())
    }

    /// Run the event source
    pub async fn run(&mut self) -> SatelliteResult<()> {
        if self.context.is_none() {
            return Err(SatelliteError::Lifecycle(
                "Event source not initialized".to_string(),
            ));
        }

        info!(
            source = %self.source.source_name(),
            "Starting event source"
        );

        // Start the event source streaming
        let streaming_task = tokio::spawn({
            let mut source = unsafe { std::ptr::read(&self.source as *const T) };
            async move {
                if let Err(e) = source.start_streaming().await {
                    error!(
                        source = %source.source_name(),
                        error = %e,
                        "Event source streaming failed"
                    );
                    return Err(e);
                }
                Ok(())
            }
        });

        // Wait for shutdown signal or streaming to complete
        let shutdown_receiver = self.shutdown_receiver.take().unwrap();
        
        tokio::select! {
            result = streaming_task => {
                match result {
                    Ok(Ok(())) => {
                        info!("Event source completed successfully");
                    }
                    Ok(Err(e)) => {
                        error!("Event source failed: {}", e);
                        return Err(e);
                    }
                    Err(e) => {
                        error!("Event source task panicked: {}", e);
                        return Err(SatelliteError::Lifecycle(format!("Task panic: {}", e)));
                    }
                }
            }
            _ = shutdown_receiver => {
                info!("Shutdown signal received, stopping event source");
                self.source.shutdown().await?;
            }
        }

        Ok(())
    }

    /// Handle a single event
    async fn handle_event(
        batcher: &mut EventBatcher,
        event: RawEvent,
        dry_run: bool,
    ) -> SatelliteResult<()> {
        if dry_run {
            info!(
                source = %event.source,
                event_type = %event.event_type,
                "DRY RUN: Would ingest event"
            );
            return Ok(());
        }

        match batcher.add_event(event).await? {
            Some(result) => {
                if !result.success {
                    warn!(
                        processed = result.processed_count,
                        failed = result.failed_count,
                        error = ?result.error,
                        "Batch ingestion completed with failures"
                    );
                } else {
                    debug!(
                        processed = result.processed_count,
                        "Batch ingestion completed successfully"
                    );
                }
            }
            None => {
                // Event added to batch but not yet flushed
            }
        }

        Ok(())
    }

    /// Run in scanner mode
    pub async fn run_scanner(
        &mut self,
        args: ScannerArgs,
    ) -> SatelliteResult<ScanReport> {
        if !self.source.supports_scanner() {
            return Err(SatelliteError::EventSource(
                format!("Source '{}' does not support scanner mode", self.source.source_name())
            ));
        }

        if self.context.is_none() {
            return Err(SatelliteError::Lifecycle(
                "Event source not initialized".to_string(),
            ));
        }

        info!(
            source = %self.source.source_name(),
            paths = ?args.paths,
            dry_run = args.dry_run,
            "Starting scanner mode"
        );

        let start_time = std::time::Instant::now();
        let result = self.source.run_scanner(args).await;
        
        match &result {
            Ok(report) => {
                info!(
                    source = %self.source.source_name(),
                    events_generated = report.events_generated,
                    duration_ms = start_time.elapsed().as_millis(),
                    "Scanner mode completed successfully"
                );
            }
            Err(e) => {
                error!(
                    source = %self.source.source_name(),
                    error = %e,
                    duration_ms = start_time.elapsed().as_millis(),
                    "Scanner mode failed"
                );
            }
        }

        result
    }

    /// Get scanner estimation
    pub async fn estimate_scanner_scope(&self, args: &ScannerArgs) -> SatelliteResult<ScannerEstimate> {
        if !self.source.supports_scanner() {
            return Err(SatelliteError::EventSource(
                format!("Source '{}' does not support scanner mode", self.source.source_name())
            ));
        }

        self.source.estimate_scanner_scope(args).await
    }

    /// Check dual-mode capabilities
    pub fn get_capabilities(&self) -> (bool, bool) {
        (self.source.supports_sensor(), self.source.supports_scanner())
    }

    /// Graceful shutdown
    pub async fn shutdown(&mut self) -> SatelliteResult<()> {
        info!("Shutting down event source runner");
        self.source.shutdown().await
    }
}