//! Preflight checks and automatic setup for xtask commands.
//!
//! This module provides infrastructure readiness checks and lazy-start capabilities.
//! Commands that need Postgres, NATS, TLS, or declarative schema apply can call `ensure_ready()`
//! to prompt the user and set up infrastructure automatically.
//!
//! ## Preflight Result Cache
//!
//! After a successful preflight, the result is cached in `{state_dir()}/preflight-cache.json`.
//! Subsequent invocations within the TTL window skip preflight entirely if nothing relevant
//! changed: schema files, contract payload files, or the git HEAD commit.
//!
//! Cache is invalidated by:
//! - TTL expiry (60 seconds, configurable via `SINEX_PREFLIGHT_TTL_SECS`)
//! - Declarative schema source changes (detected via blake3 hash)
//! - Contract payload file content changes (detected via blake3 hash)
//! - Git HEAD commit change (new commit or branch switch)
//! - `xtask infra reset` (deletes the entire `.sinex/preflight/` directory)
//! - `xtask db reset` (explicitly invalidates the cache)

use color_eyre::eyre::{Result, WrapErr, bail, eyre};
use serde::{Deserialize, Serialize};
use std::sync::Arc;
use std::sync::atomic::{AtomicBool, Ordering};

/// Spawn a watchdog thread that prints a "still waiting..." message every `interval` seconds.
/// Returns a handle that stops the watchdog when dropped.
fn spawn_watchdog(label: &str, interval_secs: u64) -> WatchdogGuard {
    let done = Arc::new(AtomicBool::new(false));
    let done_clone = done.clone();
    let label = label.to_string();
    std::thread::spawn(move || {
        let mut elapsed = 0u64;
        loop {
            std::thread::sleep(std::time::Duration::from_secs(1));
            if done_clone.load(Ordering::Relaxed) {
                break;
            }
            elapsed += 1;
            if elapsed.is_multiple_of(interval_secs) {
                eprintln!("  ⏳ {label}... still waiting ({elapsed}s)");
            }
        }
    });
    WatchdogGuard(done)
}

struct WatchdogGuard(Arc<AtomicBool>);

impl Drop for WatchdogGuard {
    fn drop(&mut self) {
        self.0.store(true, Ordering::Relaxed);
    }
}

/// Check if Postgres is available.
#[must_use]
pub fn is_postgres_ready() -> bool {
    std::process::Command::new("pg_isready")
        .arg("-q")
        .status()
        .is_ok_and(|s| s.success())
}

/// Check if NATS is available on the configured port.
#[must_use]
pub fn is_nats_ready() -> bool {
    let nats_port = std::env::var("SINEX_DEV_NATS_PORT")
        .ok()
        .and_then(|s| s.parse::<u16>().ok())
        .unwrap_or(4222);
    std::net::TcpStream::connect(format!("127.0.0.1:{nats_port}")).is_ok()
}

/// Check if TLS certificates exist.
#[must_use]
pub fn tls_certs_exist() -> bool {
    // TLS certs are in the project's certs/ directory or .tls/ directory
    let certs_dir = std::path::Path::new("certs");
    let tls_dir = std::path::Path::new(".tls");

    let check_dir = |dir: &std::path::Path| {
        // Check for .pem files (generated by TLS module)
        (dir.join("ca.pem").exists()
            && dir.join("server.pem").exists()
            && dir.join("client.pem").exists())
            // Also check for .crt files (alternative naming)
            || (dir.join("ca.crt").exists()
                && dir.join("server.crt").exists()
                && dir.join("client.crt").exists())
    };

    check_dir(certs_dir) || check_dir(tls_dir)
}

/// Get the state directory for caching preflight state.
fn state_dir() -> std::path::PathBuf {
    let crate_dir = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    crate_dir.join("../.sinex/preflight")
}

/// Path to the preflight result cache file.
fn cache_path() -> std::path::PathBuf {
    state_dir().join("preflight-cache.json")
}

/// Default TTL for the preflight cache in seconds.
const PREFLIGHT_CACHE_DEFAULT_TTL_SECS: u64 = 60;

/// Preflight result cache — persisted as JSON after a successful preflight run.
///
/// All four fields must match for the cache to be considered valid:
/// - `timestamp_secs`: unix timestamp of last successful preflight (for TTL check)
/// - `schema_hash`: blake3 hash of declarative schema source contents
/// - `contracts_hash`: blake3 hash of all event payload source file contents
/// - `git_head`: current git HEAD commit SHA (or symref target for detached HEAD)
#[derive(Debug, Clone, Serialize, Deserialize)]
struct PreflightCache {
    /// Unix timestamp (seconds) when this cache entry was written.
    timestamp_secs: u64,
    /// blake3 hash of declarative schema source contents.
    schema_hash: String,
    /// blake3 hash of contract payload source file contents.
    contracts_hash: String,
    /// Git HEAD commit SHA or symbolic ref target.
    git_head: String,
}

impl PreflightCache {
    /// Load the cache from disk. Returns `None` if absent or malformed.
    fn load() -> Option<Self> {
        let path = cache_path();
        let contents = std::fs::read_to_string(&path).ok()?;
        serde_json::from_str(&contents).ok()
    }

    /// Write this cache entry to disk atomically (R1 fix). Non-fatal on failure (best-effort).
    ///
    /// Uses a temp file + rename to avoid partial writes being read by concurrent xtask
    /// processes — `fs::write` is not atomic; rename within the same filesystem is.
    fn save(&self) {
        let path = cache_path();
        if let Some(parent) = path.parent() {
            let _ = std::fs::create_dir_all(parent);
        }
        let json = match serde_json::to_string_pretty(self) {
            Ok(j) => j,
            Err(e) => {
                tracing::debug!("preflight cache: failed to serialize: {e}");
                return;
            }
        };
        // Write to a sibling temp file then rename for atomic visibility.
        let tmp = path.with_extension("tmp");
        if let Err(e) = std::fs::write(&tmp, &json) {
            tracing::debug!(
                "preflight cache: failed to write tmp {}: {e}",
                tmp.display()
            );
            return;
        }
        if let Err(e) = std::fs::rename(&tmp, &path) {
            tracing::debug!("preflight cache: failed to rename tmp→cache: {e}");
            let _ = std::fs::remove_file(&tmp);
        }
    }

    /// Build a fresh cache entry using the current state.
    fn current() -> Self {
        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_secs();

        Self {
            timestamp_secs: now,
            schema_hash: hash_schema_sources(),
            contracts_hash: hash_contracts_dir(),
            git_head: read_git_head(),
        }
    }

    /// Check whether this cache entry is still valid.
    ///
    /// Returns `true` (cache hit) if all of the following hold:
    /// - Age is within `ttl_secs` seconds
    /// - Declarative schema hash matches current files
    /// - Contracts hash matches current files
    /// - Git HEAD hasn't changed
    fn is_valid(&self, ttl_secs: u64) -> bool {
        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_secs();

        let age = now.saturating_sub(self.timestamp_secs);
        if age >= ttl_secs {
            tracing::debug!("preflight cache: expired (age={age}s, ttl={ttl_secs}s)");
            return false;
        }

        let schema_hash = hash_schema_sources();
        if self.schema_hash != schema_hash {
            tracing::debug!(
                "preflight cache: schema hash mismatch (cached={}, current={})",
                self.schema_hash,
                schema_hash
            );
            return false;
        }

        let contracts_hash = hash_contracts_dir();
        if self.contracts_hash != contracts_hash {
            tracing::debug!(
                "preflight cache: contracts hash mismatch (cached={}, current={})",
                self.contracts_hash,
                contracts_hash
            );
            return false;
        }

        let git_head = read_git_head();
        if self.git_head != git_head {
            tracing::debug!(
                "preflight cache: git HEAD changed (cached={}, current={})",
                self.git_head,
                git_head
            );
            return false;
        }

        tracing::debug!("preflight cache: hit (age={age}s)");
        true
    }
}

/// Read the current git HEAD commit SHA without spawning a subprocess.
///
/// Reads `.git/HEAD` directly. If it contains a symbolic ref (`ref: refs/heads/main`),
/// resolves it to the commit SHA by reading the corresponding packed or loose ref.
/// Falls back to the symref string itself if the commit file doesn't exist yet
/// (e.g., initial empty repo).
fn read_git_head() -> String {
    let workspace_root = crate::config::workspace_root();
    let head_path = workspace_root.join(".git/HEAD");

    let head_contents = match std::fs::read_to_string(&head_path) {
        Ok(s) => s.trim().to_string(),
        Err(_) => return String::from("unknown"),
    };

    // Symbolic ref: "ref: refs/heads/main"
    if let Some(refname) = head_contents.strip_prefix("ref: ") {
        let ref_path = workspace_root.join(".git").join(refname);
        // Try loose ref first
        if let Ok(sha) = std::fs::read_to_string(&ref_path) {
            return sha.trim().to_string();
        }
        // Try packed-refs
        let packed_refs = workspace_root.join(".git/packed-refs");
        if let Ok(contents) = std::fs::read_to_string(&packed_refs) {
            for line in contents.lines() {
                if line.starts_with('#') {
                    continue;
                }
                let parts: Vec<&str> = line.splitn(2, ' ').collect();
                if parts.len() == 2 && parts[1] == refname {
                    return parts[0].to_string();
                }
            }
        }
        // Ref exists but no commit yet (empty branch)
        return head_contents;
    }

    // Detached HEAD: the content is the commit SHA directly
    head_contents
}

/// Compute a blake3 hash of declarative schema sources.
///
/// Hashes file contents in `sinex-schema/src/schema/**` plus `apply.rs`,
/// sorted by filename for deterministic ordering.
/// Returns a hex string. Returns `"empty"` if no files were found.
fn hash_schema_sources() -> String {
    use std::collections::BTreeMap;

    let crate_dir = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let schema_dir = crate_dir.join("../crate/lib/sinex-schema/src/schema");
    let apply_file = crate_dir.join("../crate/lib/sinex-schema/src/apply.rs");
    let registry_file = crate_dir.join("../crate/lib/sinex-schema/src/schema_registry.rs");

    let mut file_contents: BTreeMap<String, Vec<u8>> = BTreeMap::new();

    if let Ok(entries) = std::fs::read_dir(&schema_dir) {
        for entry in entries.filter_map(Result::ok) {
            let name = entry.file_name().to_string_lossy().to_string();
            if name.ends_with(".rs")
                && let Ok(contents) = std::fs::read(entry.path())
            {
                file_contents.insert(format!("schema/{name}"), contents);
            }
        }
    }

    for (name, path) in [
        ("apply.rs", apply_file.as_path()),
        ("schema_registry.rs", registry_file.as_path()),
    ] {
        if let Ok(contents) = std::fs::read(path) {
            file_contents.insert(name.to_string(), contents);
        }
    }

    if file_contents.is_empty() {
        return "empty".to_string();
    }

    let mut hasher = blake3::Hasher::new();
    for (name, contents) in &file_contents {
        hasher.update(name.as_bytes());
        hasher.update(b"\0");
        hasher.update(contents);
        hasher.update(b"\0");
    }
    hasher.finalize().to_hex()[..16].to_string()
}

/// Compute a blake3 hash of the event payload contracts directory contents.
///
/// Hashes file *contents* sorted by filename for deterministic ordering.
/// Returns a hex string. Returns `"empty"` if the directory doesn't exist or
/// contains no `.rs` files.
fn hash_contracts_dir() -> String {
    use std::collections::BTreeMap;

    let crate_dir = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let payloads_dir = crate_dir.join("../crate/lib/sinex-primitives/src/types/events/payloads");

    let mut file_contents: BTreeMap<String, Vec<u8>> = BTreeMap::new();

    if let Ok(entries) = std::fs::read_dir(&payloads_dir) {
        for entry in entries.filter_map(Result::ok) {
            let name = entry.file_name().to_string_lossy().to_string();
            if name.ends_with(".rs")
                && let Ok(contents) = std::fs::read(entry.path())
            {
                file_contents.insert(name, contents);
            }
        }
    }

    if file_contents.is_empty() {
        return "empty".to_string();
    }

    let mut hasher = blake3::Hasher::new();
    for (name, contents) in &file_contents {
        hasher.update(name.as_bytes());
        hasher.update(b"\0");
        hasher.update(contents);
        hasher.update(b"\0");
    }
    hasher.finalize().to_hex()[..16].to_string()
}

/// Delete the preflight result cache file, forcing a full preflight on the next run.
///
/// Called by `xtask db reset` after dropping and recreating the database.
/// `xtask infra reset` achieves the same by deleting the entire `.sinex/preflight/` directory.
pub fn invalidate_cache() {
    let path = cache_path();
    if path.exists() {
        if let Err(e) = std::fs::remove_file(&path) {
            tracing::debug!("preflight cache: failed to remove {}: {e}", path.display());
        } else {
            tracing::debug!("preflight cache: invalidated");
        }
    }
}

/// Check whether declarative schema sources changed since last apply.
#[must_use]
pub fn schema_changed_since_last_apply() -> bool {
    let state_dir = state_dir();
    let hash_file = state_dir.join("schema-apply-hash.txt");

    let current_hash = hash_schema_sources();
    let cached_hash = std::fs::read_to_string(&hash_file).ok();

    cached_hash.as_deref() != Some(&current_hash)
}

/// Record that declarative schema apply completed for current source state.
///
/// Uses atomic rename (R2 fix) so concurrent readers never see a partial write.
pub fn record_schema_applied() {
    let state_dir = state_dir();
    if std::fs::create_dir_all(&state_dir).is_err() {
        return;
    }
    let hash_file = state_dir.join("schema-apply-hash.txt");
    let tmp = hash_file.with_extension("tmp");
    if std::fs::write(&tmp, hash_schema_sources()).is_ok() {
        let _ = std::fs::rename(&tmp, &hash_file);
    }
}

/// Check for pending declarative schema apply work.
///
/// Uses:
/// 1. Schema hash state (source changed since last apply)
/// 2. Lightweight DB probes for required core objects
pub fn has_pending_schema_apply() -> Result<bool> {
    // Only check if Postgres is already running
    if !is_postgres_ready() {
        return Ok(false);
    }

    // Get config for database connection
    let config: crate::infra::stack::StackConfig =
        match crate::infra::stack::StackConfig::for_current_checkout() {
            Ok(c) => c,
            Err(_) => return Ok(false),
        };

    // Strategy 1: hash changed since last apply
    if schema_changed_since_last_apply() {
        return Ok(true);
    }

    // Strategy 2: check core declarative objects exist
    let output = std::process::Command::new("psql")
        .env("PGHOST", config.run_dir())
        .env("PGPORT", config.postgres.port.to_string())
        .env("PGUSER", &config.postgres.user)
        .env("PGDATABASE", &config.postgres.database)
        .args([
            "-tAc",
            "SELECT CASE
                 WHEN to_regclass('core.events') IS NULL THEN 1
                 WHEN to_regclass('core.operations_log') IS NULL THEN 1
                 WHEN NOT EXISTS (
                     SELECT 1 FROM information_schema.columns
                     WHERE table_schema='core' AND table_name='events' AND column_name='ts_persisted'
                 ) THEN 1
                 ELSE 0
             END",
        ])
        .output();

    match output {
        Ok(out) if out.status.success() => {
            let pending_flag: i32 = String::from_utf8_lossy(&out.stdout)
                .trim()
                .parse()
                .unwrap_or(0);
            Ok(pending_flag != 0)
        }
        _ => {
            // Query failed: let preflight continue and attempt auto-apply.
            Ok(true)
        }
    }
}

/// Infrastructure status for preflight checks.
#[derive(Debug)]
pub struct InfraStatus {
    pub postgres: bool,
    pub nats: bool,
    pub tls: bool,
    pub schema_apply_pending: bool,
}

impl InfraStatus {
    /// Capture current infrastructure status.
    #[must_use]
    pub fn capture() -> Self {
        Self {
            postgres: is_postgres_ready(),
            nats: is_nats_ready(),
            tls: tls_certs_exist(),
            schema_apply_pending: has_pending_schema_apply().unwrap_or(false),
        }
    }

    /// Check if all infrastructure is ready.
    #[must_use]
    pub fn all_ready(&self) -> bool {
        self.postgres && self.nats && !self.schema_apply_pending
    }

    /// Check if stack (Postgres + NATS) is running.
    #[must_use]
    pub fn stack_running(&self) -> bool {
        self.postgres && self.nats
    }
}

/// Auto-start stack if not running.
///
/// Returns Ok(true) if stack is now running, Ok(false) if start failed.
/// No prompts - just auto-starts. This is agent-friendly.
///
/// Kills the subprocess if it runs longer than `SINEX_INFRA_START_TIMEOUT`
/// seconds (default: 120s) to prevent indefinite hangs.
pub fn auto_start_stack(verbose: bool) -> Result<()> {
    let status = InfraStatus::capture();

    if status.stack_running() {
        return Ok(());
    }

    // Always report what we're starting (even in quiet mode)
    if !status.postgres && !status.nats {
        eprintln!("⚡ Auto-starting stack (Postgres + NATS)...");
    } else if !status.postgres {
        eprintln!("⚡ Auto-starting Postgres...");
    } else {
        eprintln!("⚡ Auto-starting NATS...");
    }

    let timeout_secs = std::env::var("SINEX_INFRA_START_TIMEOUT")
        .ok()
        .and_then(|v| v.parse::<u64>().ok())
        .unwrap_or(120);

    let start = std::time::Instant::now();
    let _watchdog = spawn_watchdog("Starting stack", 5);

    let mut child = match std::process::Command::new("xtask")
        .args(["infra", "start"])
        .stdout(if verbose {
            std::process::Stdio::inherit()
        } else {
            std::process::Stdio::null()
        })
        .stderr(std::process::Stdio::inherit())
        .spawn()
    {
        Ok(c) => c,
        Err(e) => {
            eprintln!("✗ Failed to start stack: {e}");
            return Err(eyre!("failed to spawn infra start: {e}"));
        }
    };

    let pid = child.id();
    let timeout = std::time::Duration::from_secs(timeout_secs);

    // Spawn a watchdog that kills the child if it runs too long.
    // Uses a channel to signal early exit when the child finishes before timeout.
    let (done_tx, done_rx) = std::sync::mpsc::channel::<()>();
    std::thread::spawn(move || {
        if done_rx.recv_timeout(timeout).is_err() {
            // Timeout — kill the process group
            eprintln!("✗ Stack start timed out after {timeout_secs}s — killing subprocess");
            unsafe {
                libc::kill(-(pid as i32), libc::SIGTERM);
            }
            std::thread::sleep(std::time::Duration::from_secs(2));
            unsafe {
                libc::kill(-(pid as i32), libc::SIGKILL);
            }
        }
    });

    let exit_status = child.wait();
    let _ = done_tx.send(()); // Signal watchdog: we're done

    let elapsed = start.elapsed();
    match exit_status {
        Ok(exit) if exit.success() => {
            eprintln!("✓ Stack started ({:.1}s)", elapsed.as_secs_f64());
            Ok(())
        }
        Ok(status) => {
            eprintln!("✗ Failed to start stack ({:.1}s)", elapsed.as_secs_f64());
            Err(eyre!("infra start exited with {status}"))
        }
        Err(e) => {
            eprintln!("✗ Failed to start stack: {e}");
            Err(e).wrap_err("failed to wait for infra start")
        }
    }
}

/// Generate TLS certificates if they don't exist and set environment variables.
pub fn ensure_tls_certs(is_interactive: bool) -> Result<()> {
    let tls_dir = std::path::Path::new(".tls");

    if !tls_certs_exist() {
        if is_interactive {
            eprintln!("Generating development TLS certificates...");
        }

        // Call TLS generation directly instead of spawning subprocess
        let config = crate::tls::CertConfig {
            output_dir: tls_dir.to_path_buf(),
            san: vec!["localhost".to_string(), "127.0.0.1".to_string()],
            ca_name: "Sinex Dev CA".to_string(),
            validity_days: 365,
            force: false,
        };
        crate::tls::generate_dev_certs(&config)?;

        if is_interactive {
            eprintln!("✓ TLS certificates generated");
        }
    }

    // Auto-set TLS environment variables for gateway if not already set
    set_tls_env_if_missing(tls_dir);

    // Auto-set dev RPC token if not already set (for gateway auth)
    set_dev_token_if_missing();

    Ok(())
}

/// Set a development RPC token if not already set.
/// This allows `xtask run gateway` to work without manual token setup.
/// Only sets the token in non-production environments.
fn set_dev_token_if_missing() {
    // Don't auto-set in production
    if std::env::var("SINEX_ENVIRONMENT")
        .ok()
        .is_some_and(|e| e == "production")
    {
        return;
    }

    // Check if any token source is already set
    let has_token = std::env::var("SINEX_RPC_TOKEN").is_ok()
        || std::env::var("SINEX_RPC_TOKEN_FILE").is_ok()
        || std::env::var("SINEX_GATEWAY_ADMIN_TOKEN_FILE").is_ok();

    if !has_token {
        // Generate a deterministic dev token based on hostname (for consistency across runs)
        // but still unique enough that it's clearly a dev token
        let hostname = gethostname::gethostname().to_string_lossy().to_string();
        let dev_token = format!("dev-token-{hostname}");
        unsafe { std::env::set_var("SINEX_RPC_TOKEN", &dev_token) };
        eprintln!("⚡ Auto-set SINEX_RPC_TOKEN={dev_token} (dev mode)");
    }
}

/// Set TLS environment variables if they're not already set.
/// This allows `xtask run gateway` to work without manual `source .env.tls`.
fn set_tls_env_if_missing(tls_dir: &std::path::Path) {
    // Check both .tls/ and certs/ directories for certificates
    let cert_locations = [
        (tls_dir.join("server.pem"), tls_dir.join("server-key.pem")),
        (
            std::path::Path::new("certs").join("server.pem"),
            std::path::Path::new("certs").join("server-key.pem"),
        ),
        (
            std::path::Path::new("certs").join("server.crt"),
            std::path::Path::new("certs").join("server.key"),
        ),
    ];

    for (cert_path, key_path) in &cert_locations {
        if cert_path.exists() && key_path.exists() {
            if std::env::var("SINEX_GATEWAY_TLS_CERT").is_err() {
                unsafe { std::env::set_var("SINEX_GATEWAY_TLS_CERT", cert_path) };
            }
            if std::env::var("SINEX_GATEWAY_TLS_KEY").is_err() {
                unsafe { std::env::set_var("SINEX_GATEWAY_TLS_KEY", key_path) };
            }
            break;
        }
    }
}

/// Auto-apply pending declarative schema.
///
/// Calls `sinex_db::apply_schema_for_url()` in-process via `block_in_place`.
///
/// On success, records the current schema source hash to prevent
/// unnecessary re-runs.
///
/// **Serialization:** acquires an exclusive flock on `{state_dir}/schema-apply.lock`
/// before running. If the lock is already held (another apply in progress),
/// skips with an informational message — the lock holder will complete the apply.
fn auto_apply_schema(verbose: bool) -> Result<bool> {
    // Serialize concurrent schema-apply runs. If another process is already applying,
    // skip — it will complete the work. Use LOCK_NB (non-blocking) so we never wait.
    let lock_path = state_dir().join("schema-apply.lock");
    let _ = std::fs::create_dir_all(state_dir());
    let lock_file = std::fs::OpenOptions::new()
        .create(true)
        .write(true)
        .truncate(false)
        .open(&lock_path);

    let lock_file = match lock_file {
        Ok(f) => f,
        Err(e) => {
            eprintln!("⚠️  Could not open schema-apply lock ({e}), proceeding without lock");
            // Continue without lock rather than failing
            return run_schema_apply_inner(verbose);
        }
    };

    use std::os::fd::AsRawFd;
    // LOCK_EX | LOCK_NB — exclusive, non-blocking
    let lock_result = unsafe { libc::flock(lock_file.as_raw_fd(), libc::LOCK_EX | libc::LOCK_NB) };
    if lock_result != 0 {
        // Another process is applying schema — skip, it'll complete it
        eprintln!("ℹ️  Schema apply already in progress (lock held) — skipping");
        return Ok(true);
    }

    // Lock acquired — run schema apply, drop lock when done
    let result = run_schema_apply_inner(verbose);
    // Lock released automatically when lock_file is dropped
    drop(lock_file);
    result
}

/// Inner implementation of schema apply, separated for the flock wrapper.
///
/// Calls `sinex_db::apply_schema_for_url()` directly (in-process, no subprocess).
/// Uses `block_in_place` since we're inside a multi-threaded tokio runtime but
/// this function is sync (called from `ensure_ready`).
fn run_schema_apply_inner(verbose: bool) -> Result<bool> {
    let config = crate::infra::stack::StackConfig::for_current_checkout()?;

    eprintln!("⚡ Applying pending declarative schema...");

    let start = std::time::Instant::now();
    let _watchdog = spawn_watchdog("Applying declarative schema", 5);

    let handle = tokio::runtime::Handle::current();
    let result = tokio::task::block_in_place(|| {
        handle.block_on(sinex_db::apply_schema_for_url(&config.database_url()))
    });

    let elapsed = start.elapsed();
    match result {
        Ok(()) => {
            if verbose {
                eprintln!(
                    "✓ Declarative schema applied ({:.1}s)",
                    elapsed.as_secs_f64()
                );
            }
            record_schema_applied();
            Ok(true)
        }
        Err(e) => {
            eprintln!(
                "✗ Failed to apply declarative schema ({:.1}s): {e}",
                elapsed.as_secs_f64()
            );
            bail!("declarative schema apply failed: {e:#}");
        }
    }
}

/// Check if contracts directory has changed since last deploy.
fn contracts_changed_since_last_deploy() -> bool {
    let state_dir = state_dir();
    let hash_file = state_dir.join("contracts-hash.txt");

    let current_hash = hash_contracts_dir();
    let cached_hash = std::fs::read_to_string(&hash_file).ok();

    cached_hash.as_deref() != Some(&current_hash)
}

/// Record that contracts were deployed with current directory state.
fn record_contracts_deployed() {
    let state_dir = state_dir();
    if std::fs::create_dir_all(&state_dir).is_ok() {
        let hash_file = state_dir.join("contracts-hash.txt");
        let _ = std::fs::write(hash_file, hash_contracts_dir());
    }
}

/// Auto-deploy contracts if schemas have changed.
///
/// Only deploys if:
/// 1. Database is ready (contracts check-ready passes)
/// 2. Schema files have changed since last deploy
fn auto_deploy_contracts(verbose: bool) -> bool {
    // Skip if no changes detected
    if !contracts_changed_since_last_deploy() {
        return false;
    }

    let Ok(config) = crate::infra::stack::StackConfig::for_current_checkout() else {
        return false;
    };

    // Check if database is ready for contracts (tables exist)
    let check_output = std::process::Command::new("psql")
        .env("PGHOST", config.run_dir())
        .env("PGPORT", config.postgres.port.to_string())
        .env("PGUSER", &config.postgres.user)
        .env("PGDATABASE", &config.postgres.database)
        .args([
            "-tAc",
            "SELECT 1 FROM pg_tables WHERE schemaname='sinex_schemas' AND tablename='event_payload_schemas'",
        ])
        .output();

    let tables_exist = check_output.is_ok_and(|out| out.status.success() && !out.stdout.is_empty());

    if !tables_exist {
        // Database not ready for contracts yet
        return false;
    }

    eprintln!("⚡ Auto-deploying event payload contracts (schemas changed)...");

    let start = std::time::Instant::now();
    let _watchdog = spawn_watchdog("Deploying contracts", 5);

    let result = std::process::Command::new("xtask")
        .args([
            "contracts",
            "deploy",
            "--database-url",
            &config.database_url(),
        ])
        .stdout(if verbose {
            std::process::Stdio::inherit()
        } else {
            std::process::Stdio::null()
        })
        // Always show stderr so errors are visible
        .stderr(std::process::Stdio::inherit())
        .status();

    let elapsed = start.elapsed();
    match result {
        Ok(exit) if exit.success() => {
            eprintln!("✓ Contracts deployed ({:.1}s)", elapsed.as_secs_f64());
            record_contracts_deployed();
            true
        }
        Ok(_) => {
            // Non-fatal: contracts deploy failure shouldn't block tests.
            // Don't record hash — will retry next invocation so transient failures self-heal.
            eprintln!(
                "⚠️  Contracts deploy failed ({:.1}s, non-fatal, will retry next run)",
                elapsed.as_secs_f64()
            );
            false
        }
        Err(e) => {
            eprintln!("⚠️  Contracts deploy failed: {e} (non-fatal, will retry next run)");
            false
        }
    }
}

/// Check for required external tools.
///
/// Returns an error with a clear message if any required tools are missing.
/// This helps users understand they need to enter the devshell.
///
/// Only checks for tools that are essential for preflight operations:
/// - pg_isready: Check if Postgres is running
/// - psql: Run schema apply checks and queries
/// - createdb: Create databases
///
/// NATS-related tools are checked separately when NATS is needed.
fn check_required_tools() -> Result<()> {
    // Core database tools needed for all preflight operations
    let tools = ["pg_isready", "psql", "createdb"];
    let missing: Vec<_> = tools
        .iter()
        .filter(|t| which::which(t).is_err())
        .copied()
        .collect();

    if !missing.is_empty() {
        bail!(
            "Missing required tools: {}. Enter devshell with `nix develop` or ensure these are on PATH.",
            missing.join(", ")
        );
    }
    Ok(())
}

/// Ensure all infrastructure is ready for a command.
///
/// This is the main entry point for preflight checks. It will:
/// 1. Check required tools are available
/// 2. Check if stack is running, auto-start if not
/// 3. Generate TLS certs if missing (interactive only)
/// 4. Auto-apply pending declarative schema
/// 5. Auto-deploy contracts if payload schemas changed
///
/// **Caching**: After a successful preflight, a cache entry is written to
/// `.sinex/preflight/preflight-cache.json`. Subsequent calls within the TTL
/// window (default 60s, override via `SINEX_PREFLIGHT_TTL_SECS`) skip preflight
/// entirely if schema files, contract payload files, and git HEAD are unchanged.
///
/// **Nextest context**: when running inside `cargo nextest`, this function is a
/// no-op. The test sandbox (TestContext) already manages DB/NATS/schema apply.
///
/// **IMPORTANT — NOT a deadlock guard**: This no-op does not protect callers against
/// the cargo target/ lock deadlock. Commands that invoke cargo subprocesses (`build`,
/// `fix`, `run`) must add their own `NEXTEST_RUN_ID` check. Relying on `ensure_ready`
/// as a nextest gate is WRONG — it only skips infra setup, not subprocess prevention.
pub fn ensure_ready(ctx: &crate::command::CommandContext) -> Result<()> {
    // Skip preflight entirely when running inside nextest.
    // nextest holds the cargo target/ lock — any cargo subprocess would deadlock.
    // The test sandbox (TestContext) already handles DB/NATS/schema apply.
    if crate::config::is_nextest_run() {
        return Ok(());
    }

    // Check the preflight result cache before doing any real work.
    let ttl_secs = std::env::var("SINEX_PREFLIGHT_TTL_SECS")
        .ok()
        .and_then(|v| v.parse::<u64>().ok())
        .unwrap_or(PREFLIGHT_CACHE_DEFAULT_TTL_SECS);

    if let Some(cache) = PreflightCache::load()
        && cache.is_valid(ttl_secs)
    {
        tracing::debug!("preflight cache: skipping preflight (cache valid)");
        return Ok(());
    }

    // 0. Check required tools are available
    check_required_tools()?;

    let is_interactive = ctx.is_human();
    let status = InfraStatus::capture();

    // 1. Auto-start stack if not running
    // Note: infra start also applies schema, so we only need to check schema apply
    // in the case where the stack was already running
    if !status.stack_running() {
        let stage = ctx.start_stage("stack-start");
        let started = auto_start_stack(is_interactive);
        ctx.finish_stage(stage, started.is_ok());
        started.wrap_err(
            "Failed to auto-start infrastructure. Check logs or start manually: xtask infra start",
        )?;
        // Stack start applies schema — write cache and return.
        PreflightCache::current().save();
        return Ok(());
    }

    // 2. Auto-generate TLS certs if missing
    if !status.tls {
        let stage = ctx.start_stage("tls-certs");
        let result = ensure_tls_certs(is_interactive);
        ctx.finish_stage(stage, result.is_ok());
        result?;
    }

    // 3. Auto-apply declarative schema if pending (stack was already running)
    if status.schema_apply_pending {
        let stage = ctx.start_stage("schema-apply");
        let result = auto_apply_schema(is_interactive);
        ctx.finish_stage(stage, result.as_ref().is_ok_and(|&ok| ok));
        result?;
    }

    // 4. Auto-deploy contracts if payload schemas changed
    let stage = ctx.start_stage("contracts-deploy");
    let deployed = auto_deploy_contracts(is_interactive);
    ctx.finish_stage(stage, deployed);

    // Write the preflight result cache so the next invocation can skip this work.
    PreflightCache::current().save();

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::sandbox::sinex_test;

    #[sinex_test]
    async fn test_infra_status_capture() -> TestResult<()> {
        // This test just verifies the capture doesn't panic
        let status = InfraStatus::capture();
        // The actual values depend on the environment
        let _ = status.all_ready();
        let _ = status.stack_running();
        Ok(())
    }
}
