//! Preflight checks and automatic setup for xtask commands.
//!
//! This module provides infrastructure readiness checks and lazy-start capabilities.
//! Commands that need Postgres, NATS, TLS, or migrations can call `ensure_ready()`
//! to prompt the user and set up infrastructure automatically.

use anyhow::Result;

/// Check if Postgres is available.
#[must_use]
pub fn is_postgres_ready() -> bool {
    std::process::Command::new("pg_isready")
        .arg("-q")
        .status()
        .is_ok_and(|s| s.success())
}

/// Check if NATS is available on the configured port.
#[must_use]
pub fn is_nats_ready() -> bool {
    let nats_port = std::env::var("SINEX_DEV_NATS_PORT")
        .ok()
        .and_then(|s| s.parse::<u16>().ok())
        .unwrap_or(4222);
    std::net::TcpStream::connect(format!("127.0.0.1:{nats_port}")).is_ok()
}

/// Check if TLS certificates exist.
#[must_use]
pub fn tls_certs_exist() -> bool {
    // TLS certs are in the project's certs/ directory or .tls/ directory
    let certs_dir = std::path::Path::new("certs");
    let tls_dir = std::path::Path::new(".tls");

    let check_dir = |dir: &std::path::Path| {
        // Check for .pem files (generated by TLS module)
        (dir.join("ca.pem").exists()
            && dir.join("server.pem").exists()
            && dir.join("client.pem").exists())
            // Also check for .crt files (alternative naming)
            || (dir.join("ca.crt").exists()
                && dir.join("server.crt").exists()
                && dir.join("client.crt").exists())
    };

    check_dir(certs_dir) || check_dir(tls_dir)
}

/// Check for pending database migrations.
///
/// Compares the count of applied migrations in the database against the
/// count of migration files on disk.
pub fn has_pending_migrations() -> Result<bool> {
    // Only check if Postgres is already running
    if !is_postgres_ready() {
        return Ok(false);
    }

    // Get config for database connection
    let config = match crate::infra::stack::StackConfig::for_current_checkout() {
        Ok(c) => c,
        Err(_) => return Ok(false),
    };

    // Query migration count from database
    let output = std::process::Command::new("psql")
        .env("PGHOST", config.run_dir())
        .env("PGPORT", config.postgres.port.to_string())
        .env("PGUSER", &config.postgres.user)
        .env("PGDATABASE", &config.postgres.database)
        .args(["-tAc", "SELECT COUNT(*) FROM seaql_migrations"])
        .output();

    match output {
        Ok(out) if out.status.success() => {
            let db_count: usize = String::from_utf8_lossy(&out.stdout)
                .trim()
                .parse()
                .unwrap_or(0);
            let file_count = migration_file_count();
            Ok(db_count < file_count)
        }
        _ => {
            // Query failed (table doesn't exist, etc.) - assume OK
            // Fresh databases will have migrations applied on stack start
            Ok(false)
        }
    }
}

/// Count migration files on disk.
fn migration_file_count() -> usize {
    let crate_dir = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let migrations_dir = crate_dir.join("../crate/lib/sinex-schema/src/migrations");

    std::fs::read_dir(&migrations_dir).map_or(17, |entries| {
        entries
            .filter_map(std::result::Result::ok)
            .filter(|e| {
                let name = e.file_name();
                let name = name.to_string_lossy();
                name.starts_with('m') && name.ends_with(".rs")
            })
            .count()
    })
}

/// Infrastructure status for preflight checks.
#[derive(Debug)]
pub struct InfraStatus {
    pub postgres: bool,
    pub nats: bool,
    pub tls: bool,
    pub migrations_pending: bool,
}

impl InfraStatus {
    /// Capture current infrastructure status.
    #[must_use]
    pub fn capture() -> Self {
        Self {
            postgres: is_postgres_ready(),
            nats: is_nats_ready(),
            tls: tls_certs_exist(),
            migrations_pending: has_pending_migrations().unwrap_or(false),
        }
    }

    /// Check if all infrastructure is ready.
    #[must_use]
    pub fn all_ready(&self) -> bool {
        self.postgres && self.nats && !self.migrations_pending
    }

    /// Check if stack (Postgres + NATS) is running.
    #[must_use]
    pub fn stack_running(&self) -> bool {
        self.postgres && self.nats
    }
}

/// Auto-start stack if not running.
///
/// Returns Ok(true) if stack is now running, Ok(false) if start failed.
/// No prompts - just auto-starts. This is agent-friendly.
pub fn auto_start_stack(verbose: bool) -> Result<bool> {
    let status = InfraStatus::capture();

    if status.stack_running() {
        return Ok(true);
    }

    // Auto-start without prompting
    if verbose {
        if !status.postgres && !status.nats {
            eprintln!("⚡ Auto-starting stack (Postgres + NATS)...");
        } else if !status.postgres {
            eprintln!("⚡ Auto-starting Postgres...");
        } else {
            eprintln!("⚡ Auto-starting NATS...");
        }
    }

    let result = std::process::Command::new("cargo")
        .args(["xtask", "stack", "start"])
        .stdout(if verbose {
            std::process::Stdio::inherit()
        } else {
            std::process::Stdio::null()
        })
        .stderr(if verbose {
            std::process::Stdio::inherit()
        } else {
            std::process::Stdio::null()
        })
        .status();

    match result {
        Ok(exit) if exit.success() => {
            if verbose {
                eprintln!("✓ Stack started");
            }
            Ok(true)
        }
        Ok(_) => {
            eprintln!("✗ Failed to start stack");
            Ok(false)
        }
        Err(e) => {
            eprintln!("✗ Failed to start stack: {e}");
            Ok(false)
        }
    }
}

/// Generate TLS certificates if they don't exist.
pub fn ensure_tls_certs(is_interactive: bool) -> Result<()> {
    if tls_certs_exist() {
        return Ok(());
    }

    if is_interactive {
        println!("Generating development TLS certificates...");
    }

    // Call TLS generation directly instead of spawning subprocess
    let config = crate::tls::CertConfig {
        output_dir: std::path::PathBuf::from(".tls"),
        san: vec!["localhost".to_string(), "127.0.0.1".to_string()],
        ca_name: "Sinex Dev CA".to_string(),
        validity_days: 365,
        force: false,
    };
    crate::tls::generate_dev_certs(&config)?;

    if is_interactive {
        println!("✓ TLS certificates generated");
    }
    Ok(())
}

/// Auto-apply pending migrations.
///
/// Runs `cargo run -p sinex-schema --bin sinex-schema -- up` to apply migrations.
fn auto_apply_migrations(verbose: bool) -> Result<bool> {
    let config = crate::infra::stack::StackConfig::for_current_checkout()?;

    if verbose {
        eprintln!("⚡ Applying pending database migrations...");
    }

    let result = std::process::Command::new("cargo")
        .args([
            "run",
            "-p",
            "sinex-schema",
            "--bin",
            "sinex-schema",
            "-q",
            "--",
            "up",
        ])
        .env("DATABASE_URL", config.database_url())
        .stdout(if verbose {
            std::process::Stdio::inherit()
        } else {
            std::process::Stdio::null()
        })
        .stderr(if verbose {
            std::process::Stdio::inherit()
        } else {
            std::process::Stdio::null()
        })
        .status();

    match result {
        Ok(exit) if exit.success() => {
            if verbose {
                eprintln!("✓ Migrations applied");
            }
            Ok(true)
        }
        Ok(_) => {
            eprintln!("✗ Failed to apply migrations");
            Ok(false)
        }
        Err(e) => {
            eprintln!("✗ Failed to apply migrations: {e}");
            Ok(false)
        }
    }
}

/// Ensure all infrastructure is ready for a command.
///
/// This is the main entry point for preflight checks. It will:
/// 1. Check if stack is running, auto-start if not
/// 2. Generate TLS certs if missing (interactive only)
/// 3. Auto-apply pending migrations
pub fn ensure_ready(ctx: &crate::command::CommandContext) -> Result<()> {
    let is_interactive = ctx.is_human();
    let status = InfraStatus::capture();

    // 1. Auto-start stack if not running
    // Note: stack start also runs migrations, so we only need to check migrations
    // in the case where the stack was already running
    if !status.stack_running() {
        auto_start_stack(is_interactive)?;
        // Stack start runs migrations, so we're done
        return Ok(());
    }

    // 2. Auto-generate TLS certs if missing
    if !status.tls {
        ensure_tls_certs(is_interactive)?;
    }

    // 3. Auto-apply migrations if pending (stack was already running)
    if status.migrations_pending {
        auto_apply_migrations(is_interactive)?;
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_infra_status_capture() {
        // This test just verifies the capture doesn't panic
        let status = InfraStatus::capture();
        // The actual values depend on the environment
        let _ = status.all_ready();
        let _ = status.stack_running();
    }
}
