//! Schema migration helpers using SeaQuery
//!
//! This module provides functions to generate migration SQL using the SeaQuery
//! schema definitions. These can be used to create new migrations or verify
//! existing schema structure.

use crate::db::schema::{
    ArchivedEvents, Entities, EntityRelations, EventPayloadSchemas, Events, OperationsLog,
    ProcessorCheckpoints, SourceMaterials,
};

/// Generate SQL to create all schemas (namespaces)
pub fn create_schemas() -> Vec<String> {
    vec![
        "CREATE SCHEMA IF NOT EXISTS core".to_string(),
        "CREATE SCHEMA IF NOT EXISTS raw".to_string(),
        "CREATE SCHEMA IF NOT EXISTS audit".to_string(),
        "CREATE SCHEMA IF NOT EXISTS sinex_schemas".to_string(),
    ]
}

/// Generate SQL to create all tables
pub fn create_all_tables() -> Vec<String> {
    vec![
        Events::create_table(),
        ProcessorCheckpoints::create_table(),
        EventPayloadSchemas::create_table(),
        SourceMaterials::create_table(),
        OperationsLog::create_table(),
        ArchivedEvents::create_table(),
        Entities::create_table(),
        EntityRelations::create_table(),
    ]
}

/// Generate SQL to create all indexes
pub fn create_all_indexes() -> Vec<String> {
    let mut indexes = Vec::new();

    indexes.extend(Events::create_indexes());
    indexes.extend(ProcessorCheckpoints::create_indexes());
    indexes.extend(EventPayloadSchemas::create_indexes());
    indexes.extend(OperationsLog::create_indexes());
    indexes.extend(ArchivedEvents::create_indexes());
    indexes.extend(Entities::create_indexes());
    indexes.extend(EntityRelations::create_indexes());

    indexes
}

/// Generate a complete migration script
pub fn generate_complete_migration() -> String {
    let mut migration = String::new();

    // Add header comment
    migration.push_str("-- Generated by SeaQuery schema definitions\n");
    migration.push_str("-- This migration creates the complete Sinex database schema\n\n");

    // Create schemas
    migration.push_str("-- Create schemas\n");
    for schema_sql in create_schemas() {
        migration.push_str(&schema_sql);
        migration.push_str(";\n");
    }
    migration.push_str("\n");

    // Create tables
    migration.push_str("-- Create tables\n");
    for table_sql in create_all_tables() {
        migration.push_str(&table_sql);
        migration.push_str(";\n\n");
    }

    // Create indexes
    migration.push_str("-- Create indexes\n");
    for index_sql in create_all_indexes() {
        migration.push_str(&index_sql);
        migration.push_str(";\n");
    }

    migration
}

/// Generate SQL to check if a table exists
pub fn table_exists_query(schema: &str, table: &str) -> String {
    format!(
        "SELECT EXISTS (
            SELECT FROM information_schema.tables 
            WHERE table_schema = '{}' 
            AND table_name = '{}'
        )",
        schema, table
    )
}

/// Generate SQL to check if an index exists
pub fn index_exists_query(schema: &str, index: &str) -> String {
    format!(
        "SELECT EXISTS (
            SELECT FROM pg_indexes 
            WHERE schemaname = '{}' 
            AND indexname = '{}'
        )",
        schema, index
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use sinex_test_utils::{sinex_test, TestContext};

    use color_eyre::eyre::Result;

    use serde_json::json;

    #[sinex_test]
    async fn test_create_schemas(_ctx: TestContext) -> Result<()> {
        let schemas = create_schemas();
        assert_eq!(schemas.len(), 4);
        assert!(schemas[0].contains("core"));
        assert!(schemas[1].contains("raw"));
        assert!(schemas[2].contains("audit"));
        assert!(schemas[3].contains("sinex_schemas"));
        Ok(())
    }

    #[sinex_test]
    async fn test_create_all_tables(_ctx: TestContext) -> Result<()> {
        let tables = create_all_tables();
        assert_eq!(tables.len(), 8);

        // Check that each table SQL is generated
        assert!(tables.iter().any(|sql| sql.contains("core.events")));
        assert!(tables
            .iter()
            .any(|sql| sql.contains("core.processor_checkpoints")));
        assert!(tables
            .iter()
            .any(|sql| sql.contains("sinex_schemas.event_payload_schemas")));
        assert!(tables
            .iter()
            .any(|sql| sql.contains("raw.source_material_registry")));
        assert!(tables.iter().any(|sql| sql.contains("core.operations_log")));
        assert!(tables
            .iter()
            .any(|sql| sql.contains("audit.archived_events")));
        assert!(tables.iter().any(|sql| sql.contains("core.entities")));
        assert!(tables
            .iter()
            .any(|sql| sql.contains("core.entity_relations")));
        Ok(())
    }

    #[sinex_test]
    async fn test_generate_complete_migration(_ctx: TestContext) -> Result<()> {
        let migration = generate_complete_migration();

        // Check that migration contains all major components
        assert!(migration.contains("CREATE SCHEMA"));
        assert!(migration.contains("CREATE TABLE"));
        assert!(migration.contains("CREATE INDEX"));

        // Check specific tables
        assert!(migration.contains("core.events"));
        assert!(migration.contains("core.processor_checkpoints"));
        assert!(migration.contains("audit.archived_events"));
        Ok(())
    }

    #[sinex_test]
    async fn test_existence_queries(_ctx: TestContext) -> Result<()> {
        let table_query = table_exists_query("core", "events");
        assert!(table_query.contains("information_schema.tables"));
        assert!(table_query.contains("table_schema = 'core'"));
        assert!(table_query.contains("table_name = 'events'"));

        let index_query = index_exists_query("core", "idx_events_source_type");
        assert!(index_query.contains("pg_indexes"));
        assert!(index_query.contains("schemaname = 'core'"));
        assert!(index_query.contains("indexname = 'idx_events_source_type'"));
        Ok(())
    }
}
