//! `#[derive(DbCheck)]` — emit a `DbCheckSpec` for an enum's `Display`-rendered
//! DB column.
//!
//! See `crate/sinex-primitives/src/schema_constraints.rs` for the runtime
//! consumer surface and `crate/sinex-schema/src/apply.rs` for how the
//! schema-apply engine reconciles the live DB against these specs.
//!
//! # Grammar
//!
//! ```ignore
//! #[derive(DbCheck)]
//! #[db_check(
//!     schema = "core",          // optional, defaults to "core"
//!     table = "manifests",
//!     column = "manifest_type",
//!     version = 1,
//! )]
//! pub enum ModuleKind {
//!     Ingestor,
//!     Automaton,
//!     Service,
//!     #[db_check(rename = "ingestor")] // optional per-variant rename
//!     Legacy,
//! }
//! ```
//!
//! The macro:
//!   1. Collects each variant's wire string. By default this is the
//!      variant ident lowercased (matching `serde(rename_all = "snake_case")`
//!      for single-word variants). A `#[db_check(rename = "...")]` override
//!      replaces it. For multi-word `PascalCase` variants, the default falls
//!      back to a `snake_case` conversion.
//!   2. Emits `impl <Enum> { pub const DB_CHECK: &'static DbCheckSpec = &... }`.
//!   3. Emits `inventory::submit! { DbCheckRegistration { spec: &<Enum>::DB_CHECK } }`.

use proc_macro::TokenStream;
use proc_macro2::TokenStream as TokenStream2;
use quote::quote;
use syn::{Data, DataEnum, DeriveInput, Expr, Lit, parse_macro_input};

pub fn expand(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    match try_expand(&input) {
        Ok(ts) => ts.into(),
        Err(e) => e.to_compile_error().into(),
    }
}

fn try_expand(input: &DeriveInput) -> syn::Result<TokenStream2> {
    let Data::Enum(DataEnum { variants, .. }) = &input.data else {
        return Err(syn::Error::new_spanned(
            input,
            "DbCheck can only be derived on enums",
        ));
    };

    let StructAttrs {
        schema,
        table,
        column,
        version,
    } = parse_struct_attrs(input)?;

    let mut allowed_values: Vec<String> = Vec::with_capacity(variants.len());
    for variant in variants {
        if !variant.fields.is_empty() {
            return Err(syn::Error::new_spanned(
                variant,
                "DbCheck enums must have only unit variants (no fields)",
            ));
        }
        let rename = parse_variant_rename(variant)?;
        let rendered = rename.unwrap_or_else(|| pascal_to_snake_case(&variant.ident.to_string()));
        allowed_values.push(rendered);
    }

    let enum_ident = &input.ident;
    let enum_name = enum_ident.to_string();
    let allowed_lits = allowed_values.iter().map(|v| quote! { #v });

    // Use a deterministic submit-fn ident derived from the enum name, so two
    // DbCheck enums in the same crate don't generate colliding `submit!` paths.
    Ok(quote! {
        impl #enum_ident {
            /// DB CHECK constraint specification derived from this enum's
            /// `Display` rendering. Generated by `#[derive(DbCheck)]`.
            pub const DB_CHECK: ::sinex_primitives::schema_constraints::DbCheckSpec =
                ::sinex_primitives::schema_constraints::DbCheckSpec {
                    schema: #schema,
                    table: #table,
                    column: #column,
                    version: #version,
                    allowed_values: &[ #(#allowed_lits),* ],
                    enum_name: #enum_name,
                };
        }

        ::sinex_primitives::__sinex_macros_reexport::inventory::submit! {
            ::sinex_primitives::schema_constraints::DbCheckRegistration {
                spec: &#enum_ident::DB_CHECK,
            }
        }
    })
}

struct StructAttrs {
    schema: String,
    table: String,
    column: String,
    version: u32,
}

fn parse_struct_attrs(input: &DeriveInput) -> syn::Result<StructAttrs> {
    let mut schema = None;
    let mut table = None;
    let mut column = None;
    let mut version = None;
    for attr in &input.attrs {
        if !attr.path().is_ident("db_check") {
            continue;
        }
        attr.parse_nested_meta(|meta| {
            if meta.path.is_ident("schema") {
                schema = Some(lit_string(&meta.value()?.parse::<Expr>()?)?);
            } else if meta.path.is_ident("table") {
                table = Some(lit_string(&meta.value()?.parse::<Expr>()?)?);
            } else if meta.path.is_ident("column") {
                column = Some(lit_string(&meta.value()?.parse::<Expr>()?)?);
            } else if meta.path.is_ident("version") {
                version = Some(lit_u32(&meta.value()?.parse::<Expr>()?)?);
            } else {
                return Err(meta.error(
                    "unknown db_check attribute (expected `schema`, `table`, `column`, `version`)",
                ));
            }
            Ok(())
        })?;
    }
    let table = table.ok_or_else(|| {
        syn::Error::new_spanned(input, "#[db_check(table = \"...\")] is required")
    })?;
    let column = column.ok_or_else(|| {
        syn::Error::new_spanned(input, "#[db_check(column = \"...\")] is required")
    })?;
    let version = version
        .ok_or_else(|| syn::Error::new_spanned(input, "#[db_check(version = N)] is required"))?;
    Ok(StructAttrs {
        schema: schema.unwrap_or_else(|| "core".to_string()),
        table,
        column,
        version,
    })
}

fn parse_variant_rename(variant: &syn::Variant) -> syn::Result<Option<String>> {
    let mut rename = None;
    for attr in &variant.attrs {
        if !attr.path().is_ident("db_check") {
            continue;
        }
        attr.parse_nested_meta(|meta| {
            if meta.path.is_ident("rename") {
                rename = Some(lit_string(&meta.value()?.parse::<Expr>()?)?);
                Ok(())
            } else {
                Err(meta.error("unknown db_check variant attribute (expected `rename`)"))
            }
        })?;
    }
    Ok(rename)
}

fn lit_string(expr: &Expr) -> syn::Result<String> {
    if let Expr::Lit(syn::ExprLit {
        lit: Lit::Str(s), ..
    }) = expr
    {
        Ok(s.value())
    } else {
        Err(syn::Error::new_spanned(expr, "expected a string literal"))
    }
}

fn lit_u32(expr: &Expr) -> syn::Result<u32> {
    if let Expr::Lit(syn::ExprLit {
        lit: Lit::Int(i), ..
    }) = expr
    {
        i.base10_parse::<u32>()
    } else {
        Err(syn::Error::new_spanned(expr, "expected an integer literal"))
    }
}

/// Convert a `PascalCase` identifier to `snake_case`, matching serde's
/// `rename_all = "snake_case"`.
fn pascal_to_snake_case(input: &str) -> String {
    let mut out = String::with_capacity(input.len() + 4);
    for (i, ch) in input.chars().enumerate() {
        if ch.is_ascii_uppercase() {
            if i != 0 {
                out.push('_');
            }
            out.push(ch.to_ascii_lowercase());
        } else {
            out.push(ch);
        }
    }
    out
}

#[cfg(test)]
#[path = "db_check_test.rs"]
mod tests;
