//! `#[derive(SinexConfig)]` — generate `from_env()` for env-driven config structs.
//!
//! See the design at `thoughtspace/crystal/decisions/sinex-config-derive.md`
//! and `sinex-macros/docs/sinex_config.md` for the attribute grammar and the
//! field-type inference table.

use proc_macro::TokenStream;
use proc_macro2::TokenStream as TokenStream2;
use quote::quote;
use syn::{Data, DataStruct, DeriveInput, Expr, Fields, Lit, Meta, Type, parse_macro_input};

pub fn expand(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    match try_expand(&input) {
        Ok(ts) => ts.into(),
        Err(e) => e.to_compile_error().into(),
    }
}

fn try_expand(input: &DeriveInput) -> syn::Result<TokenStream2> {
    let struct_attrs = parse_struct_attrs(input)?;

    let Data::Struct(DataStruct {
        fields: Fields::Named(fields),
        ..
    }) = &input.data
    else {
        return Err(syn::Error::new_spanned(
            input,
            "SinexConfig can only be derived on structs with named fields",
        ));
    };

    let mut field_inits = Vec::with_capacity(fields.named.len());
    for field in &fields.named {
        let Some(name) = field.ident.as_ref() else {
            // syn already guarantees `ident` is `Some` for named fields, but
            // give the macro a diagnostic instead of a panic if that ever drifts.
            return Err(syn::Error::new_spanned(
                field,
                "SinexConfig: named field is missing identifier",
            ));
        };
        let attrs = parse_field_attrs(field)?;
        if attrs.skip {
            field_inits.push(quote! { #name: ::std::default::Default::default() });
            continue;
        }

        if attrs.nested {
            // nested: delegate to the field type's own from_env().
            // Use `nested_fallible` on the field when the inner type's from_env()
            // is also fallible (returns Result) and you want `?`-propagation.
            let ty = &field.ty;
            let init = if attrs.nested_fallible {
                quote! { #name: <#ty>::from_env()? }
            } else {
                quote! { #name: <#ty>::from_env() }
            };
            field_inits.push(init);
            continue;
        }

        // `env = "..."` is the full env-var name. Without it, the env-var
        // name is `{prefix}_{FIELD_NAME_UPPERCASED}`.
        let env_key = match &attrs.env {
            Some(explicit) => explicit.clone(),
            None => format!(
                "{}_{}",
                struct_attrs.prefix,
                field_name_to_env(&name.to_string())
            ),
        };
        let helper_call = infer_helper(
            &field.ty,
            &env_key,
            &struct_attrs.context,
            &attrs,
            struct_attrs.fallible,
        )?;
        field_inits.push(quote! { #name: #helper_call });
    }

    let struct_ident = &input.ident;
    let (impl_generics, ty_generics, where_clause) = input.generics.split_for_impl();

    // Post-construction normalize call (if any).
    let normalize_call: TokenStream2 = match &struct_attrs.normalize_fn {
        Some(fn_name) => {
            let fn_ident: syn::Ident = syn::parse_str(fn_name).map_err(|e| {
                syn::Error::new_spanned(
                    input,
                    format!("normalize_fn `{fn_name}` is not a valid identifier: {e}"),
                )
            })?;
            if struct_attrs.fallible {
                // normalize fn returns Result<Self, SinexError>
                quote! { __sinex_cfg.#fn_ident() }
            } else {
                quote! { __sinex_cfg.#fn_ident() }
            }
        }
        None => {
            if struct_attrs.fallible {
                quote! { Ok(__sinex_cfg) }
            } else {
                quote! { __sinex_cfg }
            }
        }
    };

    let body: TokenStream2 = if struct_attrs.fallible {
        let return_ty = quote! {
            ::std::result::Result<Self, ::sinex_primitives::error::SinexError>
        };
        quote! {
            impl #impl_generics #struct_ident #ty_generics #where_clause {
                /// Load this config from environment variables.
                ///
                /// Generated by `#[derive(SinexConfig)]` with `fallible` mode. Each
                /// non-`skip` field reads from its env key using the strict
                /// `sinex_primitives::env::*` helpers; any invalid or non-UTF-8 value
                /// propagates as a `SinexError`.
                pub fn from_env() -> #return_ty {
                    let __sinex_cfg = Self {
                        #(#field_inits,)*
                    };
                    #normalize_call
                }
            }
        }
    } else {
        quote! {
            impl #impl_generics #struct_ident #ty_generics #where_clause {
                /// Load this config from environment variables.
                ///
                /// Generated by `#[derive(SinexConfig)]`. Each non-`skip` field
                /// reads from its env key (struct prefix + field-name suffix)
                /// using the appropriate `sinex_primitives::env::*` helper for
                /// its type. Parse failures and invalid UTF-8 produce `warn!`
                /// logs and the field's declared default.
                #[must_use]
                pub fn from_env() -> Self {
                    let __sinex_cfg = Self {
                        #(#field_inits,)*
                    };
                    #normalize_call
                }
            }
        }
    };

    Ok(body)
}

struct StructAttrs {
    prefix: String,
    context: String,
    /// Whether `from_env()` returns `Result<Self, SinexError>` (fallible mode).
    fallible: bool,
    /// Optional method name to call on `Self` after construction.
    normalize_fn: Option<String>,
}

fn parse_struct_attrs(input: &DeriveInput) -> syn::Result<StructAttrs> {
    let mut prefix = None;
    let mut context = None;
    let mut fallible = false;
    let mut normalize_fn = None;

    for attr in &input.attrs {
        if !attr.path().is_ident("sinex_config") {
            continue;
        }
        attr.parse_nested_meta(|meta| {
            if meta.path.is_ident("prefix") {
                prefix = Some(lit_string(&meta.value()?.parse::<Expr>()?)?);
            } else if meta.path.is_ident("context") {
                context = Some(lit_string(&meta.value()?.parse::<Expr>()?)?);
            } else if meta.path.is_ident("fallible") {
                fallible = true;
            } else if meta.path.is_ident("normalize_fn") {
                normalize_fn = Some(lit_string(&meta.value()?.parse::<Expr>()?)?);
            } else {
                return Err(meta.error(
                    "unknown sinex_config struct attribute (expected `prefix`, `context`, `fallible`, `normalize_fn`)",
                ));
            }
            Ok(())
        })?;
    }
    let prefix = prefix.ok_or_else(|| {
        syn::Error::new_spanned(
            input,
            "missing `#[sinex_config(prefix = \"SINEX_X\", context = \"...\")]` on struct",
        )
    })?;
    let context = context.ok_or_else(|| {
        syn::Error::new_spanned(
            input,
            "missing `#[sinex_config(... context = \"...\")]` on struct",
        )
    })?;

    // Strip trailing `_` from prefix so the env key format is always
    // `{prefix}_{FIELD}` without a double underscore when the caller writes
    // `prefix = "SINEX_"` (common pattern in existing hand-rolled code).
    let prefix = prefix.trim_end_matches('_').to_string();

    Ok(StructAttrs {
        prefix,
        context,
        fallible,
        normalize_fn,
    })
}

#[derive(Default)]
struct FieldAttrs {
    env: Option<String>,
    default: Option<Expr>,
    parser: Option<syn::Path>,
    skip: bool,
    /// Delegate to the field type's infallible `from_env()`.
    nested: bool,
    /// Delegate to the field type's fallible `from_env()` and propagate with `?`.
    nested_fallible: bool,
}

fn parse_field_attrs(field: &syn::Field) -> syn::Result<FieldAttrs> {
    let mut attrs = FieldAttrs::default();
    for attr in &field.attrs {
        if !attr.path().is_ident("sinex_config") {
            continue;
        }
        if matches!(attr.meta, Meta::Path(_)) {
            // Bare `#[sinex_config]` — interpret as skip
            attrs.skip = true;
            continue;
        }
        attr.parse_nested_meta(|meta| {
            if meta.path.is_ident("skip") {
                attrs.skip = true;
            } else if meta.path.is_ident("nested") {
                attrs.nested = true;
            } else if meta.path.is_ident("nested_fallible") {
                attrs.nested = true;
                attrs.nested_fallible = true;
            } else if meta.path.is_ident("env") {
                attrs.env = Some(lit_string(&meta.value()?.parse::<Expr>()?)?);
            } else if meta.path.is_ident("default") {
                attrs.default = Some(meta.value()?.parse::<Expr>()?);
            } else if meta.path.is_ident("default_expr") {
                // Accept a string literal containing a Rust expression so
                // callers can use non-literal defaults like
                // `default_expr = "Seconds::from_secs(30)"` or
                // `default_expr = "resolve_private_mode_state_dir(None)"`.
                let raw = lit_string(&meta.value()?.parse::<Expr>()?)?;
                attrs.default = Some(syn::parse_str::<Expr>(&raw).map_err(|e| {
                    meta.error(format!("could not parse default_expr as a Rust expression: {e}"))
                })?);
            } else if meta.path.is_ident("default_fn") {
                // `default_fn = "fn_name"` — sugar for `default_expr = "fn_name()"`.
                let name = lit_string(&meta.value()?.parse::<Expr>()?)?;
                let call_expr = format!("{name}()");
                attrs.default = Some(syn::parse_str::<Expr>(&call_expr).map_err(|e| {
                    meta.error(format!(
                        "could not parse default_fn `{name}` as a function call: {e}"
                    ))
                })?);
            } else if meta.path.is_ident("parser") {
                attrs.parser = Some(meta.value()?.parse::<syn::Path>()?);
            } else {
                return Err(meta.error(
                    "unknown sinex_config field attribute (expected `env`, `default`, `default_expr`, `default_fn`, `parser`, `skip`, `nested`, `nested_fallible`)",
                ));
            }
            Ok(())
        })?;
    }
    Ok(attrs)
}

fn infer_helper(
    ty: &Type,
    env_key: &str,
    context: &str,
    attrs: &FieldAttrs,
    fallible: bool,
) -> syn::Result<TokenStream2> {
    if fallible {
        return infer_helper_fallible(ty, env_key, context, attrs);
    }
    infer_helper_infallible(ty, env_key, context, attrs)
}

/// Generate infallible helper calls (original lenient behavior).
fn infer_helper_infallible(
    ty: &Type,
    env_key: &str,
    context: &str,
    attrs: &FieldAttrs,
) -> syn::Result<TokenStream2> {
    // Custom parser short-circuits inference.
    if let Some(parser) = &attrs.parser {
        let default = attrs.default.as_ref().ok_or_else(|| {
            syn::Error::new_spanned(
                ty,
                "field with `parser` must also have `default` or `default_expr`",
            )
        })?;
        return Ok(quote! {
            ::sinex_primitives::env::var_optional(#env_key, #context)
                .and_then(|raw| #parser(&raw).ok())
                .unwrap_or_else(|| #default)
        });
    }

    let kind = classify(ty);
    match kind {
        TypeKind::Bool => {
            let default = attrs
                .default
                .clone()
                .unwrap_or_else(|| syn::parse_quote!(false));
            Ok(quote! {
                ::sinex_primitives::env::bool_or(#env_key, #default, #context)
            })
        }
        TypeKind::String => {
            // Use var_optional + unwrap_or_else to accept both &str literals and
            // String-returning expressions as defaults.
            let default: Expr = attrs
                .default
                .clone()
                .unwrap_or_else(|| syn::parse_quote!("".to_string()));
            Ok(quote! {
                ::sinex_primitives::env::var_optional(#env_key, #context)
                    .unwrap_or_else(|| {
                        let __d: ::std::string::String = #default.into();
                        __d
                    })
            })
        }
        TypeKind::OptionString => Ok(quote! {
            ::sinex_primitives::env::var_optional(#env_key, #context)
        }),
        TypeKind::OptionPathBuf => Ok(quote! {
            ::sinex_primitives::env::path_optional(#env_key, #context)
        }),
        TypeKind::OptionUtf8PathBuf => Ok(quote! {
            ::sinex_primitives::env::parse_optional(#env_key, #context)
        }),
        TypeKind::OptionOther => Ok(quote! {
            ::sinex_primitives::env::parse_optional(#env_key, #context)
        }),
        TypeKind::PathBuf => {
            let default = attrs.default.as_ref().ok_or_else(|| {
                syn::Error::new_spanned(
                    ty,
                    "non-optional PathBuf field requires `default` or `default_expr`",
                )
            })?;
            Ok(quote! {
                ::sinex_primitives::env::path_optional(#env_key, #context).unwrap_or_else(|| #default)
            })
        }
        TypeKind::Utf8PathBuf => {
            let default = attrs.default.as_ref().ok_or_else(|| {
                syn::Error::new_spanned(
                    ty,
                    "non-optional Utf8PathBuf field requires `default` or `default_expr`",
                )
            })?;
            // Utf8PathBuf implements FromStr, so use parse_optional + unwrap_or_else.
            Ok(quote! {
                ::sinex_primitives::env::parse_optional(#env_key, #context).unwrap_or_else(|| #default)
            })
        }
        TypeKind::Other => {
            let default = attrs.default.as_ref().ok_or_else(|| {
                syn::Error::new_spanned(
                    ty,
                    "field requires `default`, `default_expr`, or `skip` attribute",
                )
            })?;
            Ok(quote! {
                ::sinex_primitives::env::parse_or(#env_key, #default, #context)
            })
        }
    }
}

/// Generate strict/fallible helper calls (for `fallible` structs).
fn infer_helper_fallible(
    ty: &Type,
    env_key: &str,
    _context: &str,
    attrs: &FieldAttrs,
) -> syn::Result<TokenStream2> {
    // Custom parser short-circuits inference.
    if let Some(parser) = &attrs.parser {
        let default = attrs.default.as_ref().ok_or_else(|| {
            syn::Error::new_spanned(
                ty,
                "field with `parser` must also have `default` or `default_expr`",
            )
        })?;
        // In fallible mode, parser errors are propagated (the parser must return
        // a Result whose Err is Display-able; we wrap into SinexError).
        return Ok(quote! {
            match ::sinex_primitives::env::strict_var(#env_key)? {
                Some(raw) => #parser(&raw).map_err(|e| {
                    ::sinex_primitives::error::SinexError::configuration(
                        format!("Environment variable {} has invalid value: {}", #env_key, e)
                    )
                })?,
                None => #default,
            }
        });
    }

    let kind = classify(ty);
    match kind {
        TypeKind::Bool => {
            let default = attrs
                .default
                .clone()
                .unwrap_or_else(|| syn::parse_quote!(false));
            Ok(quote! {
                ::sinex_primitives::env::strict_flag(#env_key)?.unwrap_or(#default)
            })
        }
        TypeKind::String => {
            let default = attrs
                .default
                .clone()
                .unwrap_or_else(|| syn::parse_quote!("".to_string()));
            Ok(quote! {
                ::sinex_primitives::env::strict_var(#env_key)?.unwrap_or_else(|| #default)
            })
        }
        TypeKind::OptionString => Ok(quote! {
            ::sinex_primitives::env::strict_var(#env_key)?
        }),
        TypeKind::OptionPathBuf => Ok(quote! {
            ::sinex_primitives::env::strict_var(#env_key)?.map(::std::path::PathBuf::from)
        }),
        TypeKind::OptionUtf8PathBuf => Ok(quote! {
            ::sinex_primitives::env::strict_validated_path(#env_key)?
        }),
        TypeKind::OptionOther => Ok(quote! {
            ::sinex_primitives::env::strict_parsed(#env_key)?
        }),
        TypeKind::PathBuf => {
            let default = attrs.default.as_ref().ok_or_else(|| {
                syn::Error::new_spanned(
                    ty,
                    "non-optional PathBuf field requires `default` or `default_expr`",
                )
            })?;
            Ok(quote! {
                ::sinex_primitives::env::strict_var(#env_key)?
                    .map(::std::path::PathBuf::from)
                    .unwrap_or_else(|| #default)
            })
        }
        TypeKind::Utf8PathBuf => {
            let default = attrs.default.as_ref().ok_or_else(|| {
                syn::Error::new_spanned(
                    ty,
                    "non-optional Utf8PathBuf field requires `default` or `default_expr`",
                )
            })?;
            Ok(quote! {
                ::sinex_primitives::env::strict_validated_path(#env_key)?.unwrap_or_else(|| #default)
            })
        }
        TypeKind::Other => {
            let default = attrs.default.as_ref().ok_or_else(|| {
                syn::Error::new_spanned(
                    ty,
                    "field in fallible mode requires `default`, `default_expr`, `nested`, or `skip` attribute",
                )
            })?;
            Ok(quote! {
                ::sinex_primitives::env::strict_parsed(#env_key)?.unwrap_or_else(|| #default)
            })
        }
    }
}

enum TypeKind {
    Bool,
    String,
    OptionString,
    OptionPathBuf,
    OptionUtf8PathBuf,
    OptionOther,
    PathBuf,
    Utf8PathBuf,
    Other,
}

fn classify(ty: &Type) -> TypeKind {
    let Type::Path(tp) = ty else {
        return TypeKind::Other;
    };
    let Some(last) = tp.path.segments.last() else {
        return TypeKind::Other;
    };
    let ident = last.ident.to_string();
    match ident.as_str() {
        "bool" => TypeKind::Bool,
        "String" => TypeKind::String,
        "PathBuf" => TypeKind::PathBuf,
        "Utf8PathBuf" => TypeKind::Utf8PathBuf,
        "Option" => {
            // Drill into the Option<T>'s inner type.
            let syn::PathArguments::AngleBracketed(args) = &last.arguments else {
                return TypeKind::OptionOther;
            };
            let Some(syn::GenericArgument::Type(inner)) = args.args.first() else {
                return TypeKind::OptionOther;
            };
            let Type::Path(inner_tp) = inner else {
                return TypeKind::OptionOther;
            };
            let Some(inner_last) = inner_tp.path.segments.last() else {
                return TypeKind::OptionOther;
            };
            match inner_last.ident.to_string().as_str() {
                "String" => TypeKind::OptionString,
                "PathBuf" => TypeKind::OptionPathBuf,
                "Utf8PathBuf" => TypeKind::OptionUtf8PathBuf,
                _ => TypeKind::OptionOther,
            }
        }
        _ => TypeKind::Other,
    }
}

fn lit_string(expr: &Expr) -> syn::Result<String> {
    if let Expr::Lit(syn::ExprLit {
        lit: Lit::Str(s), ..
    }) = expr
    {
        Ok(s.value())
    } else {
        Err(syn::Error::new_spanned(expr, "expected a string literal"))
    }
}

fn field_name_to_env(name: &str) -> String {
    // snake_case → SCREAMING_SNAKE_CASE. The struct's prefix is joined
    // separately, so e.g. `max_connections` → `MAX_CONNECTIONS`, paired with
    // `SINEX_DB` becomes `SINEX_DB_MAX_CONNECTIONS`.
    name.to_uppercase()
}
