use schemars::schema::RootSchema;
use std::collections::HashMap;

/// Event registry - compile-time discovered events
pub struct EventRegistry {
    /// All event types in the system
    pub event_types: &'static [&'static str],
    
    /// Mapping from event type to source name
    pub event_to_source: &'static [(&'static str, &'static str)],
    
    /// Schema generators for each event type
    pub schema_generators: HashMap<&'static str, fn() -> RootSchema>,
}

impl EventRegistry {
    /// Get source name for an event type
    pub fn source_for_event(&self, event_type: &str) -> Option<&'static str> {
        self.event_to_source
            .iter()
            .find(|(e, _)| *e == event_type)
            .map(|(_, s)| *s)
    }
    
    /// Get all events for a source
    pub fn events_for_source(&self, source: &str) -> Vec<&'static str> {
        self.event_to_source
            .iter()
            .filter(|(_, s)| *s == source)
            .map(|(e, _)| *e)
            .collect()
    }
    
    /// Get schema for an event type
    pub fn schema_for_event(&self, event_type: &str) -> Option<RootSchema> {
        self.schema_generators.get(event_type).map(|f| f())
    }
    
    /// Check if an event type exists
    pub fn has_event(&self, event_type: &str) -> bool {
        self.event_types.contains(&event_type)
    }
    
    /// Get all unique source names
    pub fn all_sources(&self) -> Vec<&'static str> {
        let mut sources: Vec<_> = self.event_to_source
            .iter()
            .map(|(_, s)| *s)
            .collect();
        sources.sort();
        sources.dedup();
        sources
    }
}

// This will be generated by a build script or macro
// For now, we'll create it manually
pub fn create_registry() -> EventRegistry {
    EventRegistry {
        event_types: &[
            "file.created",
            "file.modified", 
            "file.deleted",
            "command.executed",
            "window.focused",
            "workspace.changed",
        ],
        event_to_source: &[
            ("file.created", "filesystem"),
            ("file.modified", "filesystem"),
            ("file.deleted", "filesystem"),
            ("command.executed", "terminal.kitty"),
            ("window.focused", "window_manager.hyprland"),
            ("workspace.changed", "window_manager.hyprland"),
        ],
        schema_generators: HashMap::new(), // Will be populated by build script
    }
}