//! JUnit XML parser for extracting test outputs from nextest JUnit reports.
//!
//! nextest's `libtest-json-plus` format only includes `stdout` for failed tests.
//! However, the JUnit XML report (when `store-success-output = true` in nextest.toml)
//! includes `<system-out>` for ALL tests. This module parses the JUnit XML after a
//! test run to back-fill output for passing tests into the history database.

use color_eyre::eyre::{Result, WrapErr};
use quick_xml::escape::unescape;
use quick_xml::events::Event;
use quick_xml::reader::Reader;
use std::collections::HashMap;
use std::path::Path;

/// Path to the JUnit XML report generated by nextest.
/// Configured in `.config/nextest.toml` under `[profile.default.junit]`.
const JUNIT_XML_PATH: &str = "target/nextest/default/.sinex/nextest/junit.xml";

/// A parsed test entry from JUnit XML with its captured output.
#[derive(Debug)]
pub struct JunitTestOutput {
    /// Test function name (matches libtest-json `name` field)
    pub test_name: String,
    /// Captured stdout/stderr (from `<system-out>` element)
    pub output: String,
}

/// Parse the nextest JUnit XML report and extract test outputs.
///
/// Returns a map of `test_name -> output` for all tests that have `<system-out>` content.
/// Tests without output (empty `<testcase>` elements) are skipped.
pub fn parse_junit_outputs(path: &Path) -> Result<HashMap<String, String>> {
    let xml_content = std::fs::read_to_string(path)
        .with_context(|| format!("failed to read JUnit XML at {}", path.display()))?;

    let mut reader = Reader::from_str(&xml_content);
    let mut outputs: HashMap<String, String> = HashMap::new();

    // State machine for parsing
    let mut current_test_name: Option<String> = None;
    let mut in_system_out = false;
    let mut system_out_buf = String::new();
    let mut buf = Vec::new();

    loop {
        match reader.read_event_into(&mut buf) {
            Ok(Event::Start(ref e)) => {
                match e.name().as_ref() {
                    b"testcase" => {
                        // Extract the `name` attribute
                        current_test_name = None;
                        for attr in e.attributes().flatten() {
                            if attr.key.as_ref() == b"name" {
                                current_test_name = String::from_utf8(attr.value.to_vec()).ok();
                            }
                        }
                    }
                    b"system-out" => {
                        in_system_out = true;
                        system_out_buf.clear();
                    }
                    _ => {}
                }
            }
            Ok(Event::End(ref e)) => match e.name().as_ref() {
                b"testcase" => {
                    current_test_name = None;
                }
                b"system-out" => {
                    if in_system_out {
                        if let Some(ref name) = current_test_name {
                            let trimmed = system_out_buf.trim();
                            if !trimmed.is_empty() {
                                outputs.insert(name.clone(), trimmed.to_string());
                            }
                        }
                        in_system_out = false;
                        system_out_buf.clear();
                    }
                }
                _ => {}
            },
            Ok(Event::Empty(_)) => {
                // Self-closing <testcase ... /> — no output to extract
            }
            Ok(Event::Text(e)) => {
                if in_system_out {
                    // BytesText derefs to [u8]; convert to str then unescape XML entities
                    if let Ok(raw) = std::str::from_utf8(&e) {
                        if let Ok(text) = unescape(raw) {
                            system_out_buf.push_str(&text);
                        }
                    }
                }
            }
            Ok(Event::CData(e)) => {
                if in_system_out {
                    if let Ok(text) = std::str::from_utf8(&e) {
                        system_out_buf.push_str(text);
                    }
                }
            }
            Ok(Event::Eof) => break,
            Err(e) => {
                // Log but don't fail — partial XML is better than no output at all
                eprintln!(
                    "⚠️  JUnit XML parse error at position {}: {e}",
                    reader.error_position()
                );
                break;
            }
            _ => {}
        }
        buf.clear();
    }

    Ok(outputs)
}

/// Get the default JUnit XML path for the current nextest run.
pub fn default_junit_path() -> &'static Path {
    Path::new(JUNIT_XML_PATH)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::sandbox::sinex_test;
    use std::io::Write;
    use tempfile::NamedTempFile;

    #[sinex_test]
    fn test_parse_passing_test_with_output() -> TestResult<()> {
        let xml = r#"<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="nextest-run" tests="2" failures="0">
    <testsuite name="my-crate" tests="2">
        <testcase name="test_basic" classname="my-crate" time="0.5">
            <system-out>
running 1 test
test output here
test result: ok. 1 passed
            </system-out>
        </testcase>
        <testcase name="test_empty" classname="my-crate" time="0.1">
        </testcase>
    </testsuite>
</testsuites>"#;

        let mut f = NamedTempFile::new()?;
        f.write_all(xml.as_bytes())?;

        let outputs = parse_junit_outputs(f.path())?;
        assert_eq!(outputs.len(), 1);
        assert!(outputs.contains_key("test_basic"));
        assert!(outputs["test_basic"].contains("test output here"));
        assert!(!outputs.contains_key("test_empty"));
        Ok(())
    }

    #[sinex_test]
    fn test_parse_failure_with_output() -> TestResult<()> {
        let xml = r#"<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="nextest-run" tests="1" failures="1">
    <testsuite name="my-crate" tests="1" failures="1">
        <testcase name="test_failing" classname="my-crate" time="1.0">
            <failure message="assertion failed" type="test failure">assertion failed at line 42</failure>
            <system-out>
running 1 test
detailed failure output
test result: FAILED
            </system-out>
            <system-err>(stdout and stderr are combined)</system-err>
        </testcase>
    </testsuite>
</testsuites>"#;

        let mut f = NamedTempFile::new()?;
        f.write_all(xml.as_bytes())?;

        let outputs = parse_junit_outputs(f.path())?;
        assert_eq!(outputs.len(), 1);
        assert!(outputs.contains_key("test_failing"));
        assert!(outputs["test_failing"].contains("detailed failure output"));
        Ok(())
    }

    #[sinex_test]
    fn test_parse_multiple_suites() -> TestResult<()> {
        let xml = r#"<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="nextest-run" tests="3" failures="0">
    <testsuite name="crate-a" tests="1">
        <testcase name="test_a" classname="crate-a" time="0.1">
            <system-out>output a</system-out>
        </testcase>
    </testsuite>
    <testsuite name="crate-b" tests="2">
        <testcase name="test_b1" classname="crate-b" time="0.2">
            <system-out>output b1</system-out>
        </testcase>
        <testcase name="test_b2" classname="crate-b" time="0.3">
            <system-out>output b2</system-out>
        </testcase>
    </testsuite>
</testsuites>"#;

        let mut f = NamedTempFile::new()?;
        f.write_all(xml.as_bytes())?;

        let outputs = parse_junit_outputs(f.path())?;
        assert_eq!(outputs.len(), 3);
        assert_eq!(outputs["test_a"], "output a");
        assert_eq!(outputs["test_b1"], "output b1");
        assert_eq!(outputs["test_b2"], "output b2");
        Ok(())
    }

    #[sinex_test]
    fn test_parse_empty_system_out_skipped() -> TestResult<()> {
        let xml = r#"<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="nextest-run" tests="1" failures="0">
    <testsuite name="my-crate" tests="1">
        <testcase name="test_quiet" classname="my-crate" time="0.1">
            <system-out>
            </system-out>
        </testcase>
    </testsuite>
</testsuites>"#;

        let mut f = NamedTempFile::new()?;
        f.write_all(xml.as_bytes())?;

        let outputs = parse_junit_outputs(f.path())?;
        assert_eq!(outputs.len(), 0);
        Ok(())
    }

    #[sinex_test]
    fn test_missing_file_returns_error() -> TestResult<()> {
        let result = parse_junit_outputs(Path::new("/nonexistent/junit.xml"));
        assert!(result.is_err());
        Ok(())
    }
}
