// Comprehensive schema validation testing
//
// Tests for:
// - Malformed event detection
// - Schema constraint validation
// - JSON payload validation
// - Security validation (injection attacks, null bytes, etc.)
// - Performance under load

use sinex_test_utils::prelude::*;
use sinex_db::models::{EventFactory, services, event_types};
use sinex_db::integrity::{malformed_detection, IntegrityTestConfig, IntegrityTester};
use sinex_db::validation::{EventValidator, SchemaViolationType, ValidationError};

#[sinex_test]
async fn test_malformed_event_detection(ctx: TestContext) -> anyhow::Result<()> {
    let pool = ctx.pool().clone();
    let validator = EventValidator::load_from_db(&pool).await?;

    // Test malformed events generated by the integrity module
    let malformed_events = malformed_detection::generate_malformed_test_events();

    for (i, event) in malformed_events.iter().enumerate() {
        let result = validator.validate(event);
        assert!(
            result.is_err(),
            "Malformed event {} should fail validation",
            i
        );

        let error = result.unwrap_err();
        match event.event_type.as_str() {
            "null_payload" => {
                // Null payload should fail validation
                match error {
                    ValidationError::InvalidType { field, .. } if field == "payload" => (),
                    ValidationError::SecurityValidation(_) => (),
                    _ => panic!(
                        "Expected payload validation error for null payload, got: {:?}",
                        error
                    ),
                }
            }
            "empty_source" => {
                // Empty source should fail validation
                match error {
                    ValidationError::InvalidValue { field, .. } if field == "source" => (),
                    _ => panic!(
                        "Expected source validation error for empty source, got: {:?}",
                        error
                    ),
                }
            }
            "oversized_payload" => {
                // Large payload should be detected
                // Note: This might pass basic validation but should be caught by integrity checks
                println!("Oversized payload validation result: {:?}", error);
            }
            _ => {}
        }
    }

    Ok(())
}

#[sinex_test]
async fn test_schema_constraint_validation(ctx: TestContext) -> anyhow::Result<()> {
    let pool = ctx.pool().clone();
    let validator = EventValidator::load_from_db(&pool).await?;

    // Test filesystem events with missing required fields
    let invalid_filesystem_event = EventBuilder::generic("filesystem", "file.created")
        .payload(json!({
            // Missing required "path" field
            "size": 1024,
            "permissions": "644"
        }))
        .build();

    let result = validator.validate(&invalid_filesystem_event);
    assert!(
        result.is_err(),
        "Event missing required field should fail validation"
    );

    match result.unwrap_err() {
        ValidationError::MissingField { field } => {
            assert_eq!(field, "path", "Should detect missing path field");
        }
        _ => panic!("Expected MissingField error"),
    }

    // Test with invalid field types
    let invalid_type_event = EventBuilder::generic("filesystem", "file.created")
        .payload(json!({
            "path": "/test/file.txt",
            "size": "not_a_number", // Should be numeric
            "permissions": 644
        }))
        .build();

    let result = validator.validate(&invalid_type_event);
    assert!(
        result.is_err(),
        "Event with invalid field type should fail validation"
    );

    Ok(())
}

#[sinex_test]
async fn test_json_payload_validation(ctx: TestContext) -> anyhow::Result<()> {
    let pool = ctx.pool().clone();
    let validator = EventValidator::load_from_db(&pool).await?;

    // Test various malformed JSON scenarios
    let test_cases = vec![
        // Non-object payloads
        (json!("just a string"), "string payload should fail"),
        (json!(42), "numeric payload should fail"),
        (json!(true), "boolean payload should fail"),
        (json!(null), "null payload should fail"),
        (json!([1, 2, 3]), "array payload should fail"),
        // Empty object (should pass basic validation)
        (json!({}), "empty object should pass basic validation"),
        // Deeply nested objects (test recursion limits)
        (
            create_deeply_nested_json(50),
            "deeply nested should be handled",
        ),
    ];

    for (payload, description) in test_cases {
        let event = EventBuilder::generic("test.validation", "json_test")
            .payload(payload.clone())
            .build();

        let result = validator.validate(&event);

        // Most non-object payloads should fail, but some might pass depending on validation rules
        println!("Testing {}: {:?}", description, result);

        // The key is that validation should not crash or hang
        match result {
            Ok(_) => println!("  -> Passed validation"),
            Err(e) => println!("  -> Failed validation: {}", e),
        }
    }

    Ok(())
}

#[sinex_test]
async fn test_security_validation_injection_attacks(ctx: TestContext) -> anyhow::Result<()> {
    let pool = ctx.pool().clone();
    let validator = EventValidator::load_from_db(&pool).await?;

    // Test various injection attack payloads
    let malicious_payloads = vec![
        // SQL injection attempts
        json!({
            "path": "/test'; DROP TABLE core.events; --",
            "size": 1024
        }),
        // XSS attempts
        json!({
            "path": "/test/<script>alert('xss')</script>",
            "size": 1024
        }),
        // Path traversal attempts
        json!({
            "path": "../../../etc/passwd",
            "size": 1024
        }),
        // Null byte injection
        json!({
            "path": "/test/file\u{0000}.txt",
            "size": 1024
        }),
        // Control character injection
        json!({
            "path": "/test/file\x01\x02\x03.txt",
            "size": 1024
        }),
        // Unicode normalization attacks
        json!({
            "path": "/test/\u{202e}\u{0301}file.txt",
            "size": 1024
        }),
    ];

    for (i, payload) in malicious_payloads.iter().enumerate() {
        let event = EventBuilder::generic("filesystem", "file.created")
            .payload(payload.clone())
            .build();

        let result = validator.validate(&event);

        // Many of these should be caught by security validation
        match result {
            Err(ValidationError::SecurityValidation(msg)) => {
                println!(
                    "Security validation caught malicious payload {}: {}",
                    i, msg
                );
            }
            Err(other_error) => {
                println!("Other validation error for payload {}: {}", i, other_error);
            }
            Ok(_) => {
                // Some might pass basic validation but should be caught by deeper security checks
                println!(
                    "Malicious payload {} passed basic validation (may be caught by deeper checks)",
                    i
                );
            }
        }
    }

    Ok(())
}

#[sinex_test]
async fn test_schema_validation_performance_under_load(ctx: TestContext) -> anyhow::Result<()> {
    let pool = ctx.pool().clone();
    let validator = EventValidator::load_from_db(&pool).await?;

    // Generate a large number of events to test performance
    let num_events = 1000;
    let mut events = Vec::new();

    for i in 0..num_events {
        let event = EventBuilder::filesystem()
            .path(&format!("/test/performance/file_{}.txt", i))
            .created()
            .size(1024)
            .permissions(0o644)
            .build();
        events.push(event);
    }

    // Measure validation performance
    let start_time = std::time::Instant::now();
    let mut validation_results = Vec::new();

    for event in &events {
        let result = validator.validate(event);
        validation_results.push(result.is_ok());
    }

    let elapsed = start_time.elapsed();
    let events_per_second = num_events as f64 / elapsed.as_secs_f64();

    println!(
        "Validated {} events in {:?} ({:.2} events/sec)",
        num_events, elapsed, events_per_second
    );

    // Verify all valid events passed
    let passed_count = validation_results.iter().filter(|&&passed| passed).count();
    assert_eq!(
        passed_count, num_events,
        "All valid events should pass validation"
    );

    // Performance should be reasonable (adjust threshold as needed)
    assert!(
        events_per_second > 100.0,
        "Validation performance too slow: {:.2} events/sec",
        events_per_second
    );

    Ok(())
}

#[sinex_test]
async fn test_comprehensive_integrity_validation(ctx: TestContext) -> anyhow::Result<()> {
    let pool = ctx.pool().clone();

    // Insert some test events with known issues
    let valid_event = EventFactory::new("test.comprehensive")
        .create_event("valid_event", json!({"data": "valid"}));
    let _valid_event = sinex_db::insert_event_with_validator(&pool, &valid_event, None).await?;

    // Create integrity tester
    let integrity_tester = IntegrityTester::new(&pool).await?;

    // Run comprehensive integrity tests
    let config = IntegrityTestConfig {
        max_events_to_check: 1000,
        check_window_hours: 1,
        include_deep_validation: true,
        validate_checkpoints: true,
        validate_ulid_ordering: true,
        validate_schemas: true,
    };

    let results = integrity_tester.run_integrity_tests(config).await?;

    println!("Integrity test results:");
    println!("  Severity: {:?}", results.check_report.severity);
    println!(
        "  Events checked: {}",
        results.check_report.total_events_checked
    );
    println!(
        "  Schema violations: {}",
        results.check_report.schema_violations.len()
    );
    println!(
        "  ULID violations: {}",
        results.check_report.ulid_ordering_violations.len()
    );
    println!(
        "  Checkpoint issues: {}",
        results.check_report.checkpoint_inconsistencies.len()
    );
    println!(
        "  Corruption indicators: {}",
        results.check_report.data_corruption_indicators.len()
    );
    println!("  Recommendations: {}", results.recommendations.len());
    println!("  Test duration: {:?}", results.test_metadata.test_duration);

    // For a clean test environment, we should have minimal issues
    assert!(
        results.check_report.total_events_checked > 0,
        "Should have checked some events"
    );

    // Print any recommendations for debugging
    for rec in &results.recommendations {
        println!("Recommendation [{:?}]: {}", rec.priority, rec.description);
        for step in &rec.action_steps {
            println!("  - {}", step);
        }
    }

    Ok(())
}

#[sinex_test]
async fn test_malformed_event_anomaly_detection(ctx: TestContext) -> anyhow::Result<()> {
    let pool = ctx.pool().clone();

    // Test the anomaly detection utilities
    let test_events = vec![
        // Event with empty required fields
        EventBuilder::generic("", "empty.source")
            .payload(json!({"data": "test"}))
            .build(),
        // Event with null bytes in fields
        EventBuilder::generic("test\0source", "null.byte")
            .payload(json!({"data": "test"}))
            .build(),
        // Event with oversized payload
        EventBuilder::generic("test.source", "oversized")
            .payload(json!({"large_field": "x".repeat(500_000)}))
            .build(),
        // Valid event for comparison
        EventBuilder::generic("test.source", "valid")
            .payload(json!({"data": "valid"}))
            .build(),
    ];

    for (i, event) in test_events.iter().enumerate() {
        let anomalies = malformed_detection::detect_schema_anomalies(event);

        println!("Event {}: detected {} anomalies", i, anomalies.len());
        for anomaly in &anomalies {
            println!("  - {}", anomaly);
        }

        // Verify expected anomalies are detected
        match i {
            0 => assert!(!anomalies.is_empty(), "Should detect empty source field"),
            1 => assert!(
                anomalies.iter().any(|a| a.contains("Null bytes")),
                "Should detect null bytes"
            ),
            2 => assert!(
                anomalies.iter().any(|a| a.contains("Oversized payload")),
                "Should detect oversized payload"
            ),
            3 => assert!(anomalies.is_empty(), "Valid event should have no anomalies"),
            _ => {}
        }
    }

    Ok(())
}

// Helper function to create deeply nested JSON for testing
fn create_deeply_nested_json(depth: usize) -> Value {
    if depth == 0 {
        json!("leaf")
    } else {
        json!({
            "level": depth,
            "nested": create_deeply_nested_json(depth - 1)
        })
    }
}

// Test schema validation with various event types
#[sinex_test]
async fn test_event_type_specific_validation(ctx: TestContext) -> anyhow::Result<()> {
    let pool = ctx.pool().clone();
    let validator = EventValidator::load_from_db(&pool).await?;

    // Test filesystem events
    let filesystem_tests = vec![
        // Valid filesystem event
        (
            EventBuilder::filesystem()
                .path("/test/valid.txt")
                .created()
                .size(1024)
                .build(),
            true,
        ),
        // Invalid filesystem event - missing path
        (
            EventBuilder::generic("filesystem", "file.created")
                .payload(json!({"size": 1024}))
                .build(),
            false,
        ),
        // Invalid filesystem event - invalid size type
        (
            EventBuilder::generic("filesystem", "file.created")
                .payload(json!({"path": "/test.txt", "size": "not_a_number"}))
                .build(),
            false,
        ),
    ];

    for (event, should_pass) in filesystem_tests {
        let result = validator.validate(&event);
        if should_pass {
            assert!(
                result.is_ok(),
                "Valid filesystem event should pass: {:?}",
                result
            );
        } else {
            assert!(result.is_err(), "Invalid filesystem event should fail");
        }
    }

    // Test terminal events
    let terminal_tests = vec![
        // Valid terminal event
        (
            EventBuilder::terminal()
                .command("echo test")
                .success()
                .build(),
            true,
        ),
        // Invalid terminal event - missing command
        (
            EventBuilder::generic("terminal.kitty", "command.executed")
                .payload(json!({"exit_code": 0}))
                .build(),
            false,
        ),
    ];

    for (event, should_pass) in terminal_tests {
        let result = validator.validate(&event);
        if should_pass {
            assert!(
                result.is_ok(),
                "Valid terminal event should pass: {:?}",
                result
            );
        } else {
            assert!(result.is_err(), "Invalid terminal event should fail");
        }
    }

    Ok(())
}
