// Comprehensive schema validation testing
//
// Tests for:
// - Malformed event detection
// - Schema constraint validation
// - JSON payload validation
// - Security validation (injection attacks, null bytes, etc.)
// - Performance under load

use sinex_test_utils::prelude::*;
use rstest::*;
use insta::assert_json_snapshot;
use tracing_test::traced_test;
use sinex_db::models::{EventFactory, services, event_types};
use sinex_db::integrity::{malformed_detection, IntegrityTestConfig, IntegrityTester};
use sinex_db::validation::{EventValidator, SchemaViolationType, ValidationError};

#[sinex_test]
#[traced_test]
async fn test_malformed_event_detection(ctx: TestContext) -> color_eyre::eyre::Result<()> {
    let pool = ctx.pool().clone();
    let validator = EventValidator::load_from_db(&pool).await?;

    // Test malformed events generated by the integrity module
    let malformed_events = malformed_detection::generate_malformed_test_events();
    let mut validation_results = Vec::new();

    for (i, event) in malformed_events.iter().enumerate() {
        let result = validator.validate(event);
        
        tracing::info!(
            "Testing malformed event {} (type: {}): validation result = {}",
            i,
            event.event_type,
            result.is_ok()
        );

        assert!(
            result.is_err(),
            "Malformed event {} should fail validation",
            i
        );

        let error = result.unwrap_err();
        let error_type = match event.event_type.as_str() {
            "null_payload" => {
                // Null payload should fail validation
                match error {
                    ValidationError::InvalidType { field, .. } if field == "payload" => "payload_invalid_type",
                    ValidationError::SecurityValidation(_) => "security_validation",
                    _ => {
                        panic!(
                            "Expected payload validation error for null payload, got: {:?}",
                            error
                        );
                    }
                }
            }
            "empty_source" => {
                // Empty source should fail validation
                match error {
                    ValidationError::InvalidValue { field, .. } if field == "source" => "source_invalid_value",
                    _ => {
                        panic!(
                            "Expected source validation error for empty source, got: {:?}",
                            error
                        );
                    }
                }
            }
            "oversized_payload" => {
                // Large payload should be detected
                tracing::debug!("Oversized payload validation result: {:?}", error);
                "oversized_payload_detected"
            }
            _ => "other_validation_error"
        };

        validation_results.push(serde_json::json!({
            "event_index": i,
            "event_type": event.event_type,
            "source": event.source,
            "error_type": error_type,
            "error_message": error.to_string(),
            "payload_size": event.payload.to_string().len()
        }));
    }

    // Create comprehensive snapshot of all malformed event validation results
    ctx.snapshot_json("malformed_event_validation_summary", &serde_json::json!({
        "total_events_tested": malformed_events.len(),
        "all_failed_as_expected": true,
        "validation_results": validation_results
    }));

    Ok(())
}

#[sinex_test]
async fn test_schema_constraint_validation(ctx: TestContext) -> color_eyre::eyre::Result<()> {
    let pool = ctx.pool().clone();
    let validator = EventValidator::load_from_db(&pool).await?;

    // Test filesystem events with missing required fields
    let invalid_filesystem_event = EventBuilder::generic("filesystem", "file.created")
        .payload(json!({
            // Missing required "path" field
            "size": 1024,
            "permissions": "644"
        }))
        .build();

    let result = validator.validate(&invalid_filesystem_event);
    assert!(
        result.is_err(),
        "Event missing required field should fail validation"
    );

    match result.unwrap_err() {
        ValidationError::MissingField { field } => {
            assert_eq!(field, "path", "Should detect missing path field");
        }
        _ => panic!("Expected MissingField error"),
    }

    // Test with invalid field types
    let invalid_type_event = EventBuilder::generic("filesystem", "file.created")
        .payload(json!({
            "path": "/test/file.txt",
            "size": "not_a_number", // Should be numeric
            "permissions": 644
        }))
        .build();

    let result = validator.validate(&invalid_type_event);
    assert!(
        result.is_err(),
        "Event with invalid field type should fail validation"
    );

    Ok(())
}

/// Test JSON payload validation with various malformed scenarios
#[rstest]
#[case::string_payload(json!("just a string"), "string payload should fail", false)]
#[case::numeric_payload(json!(42), "numeric payload should fail", false)]
#[case::boolean_payload(json!(true), "boolean payload should fail", false)]
#[case::null_payload(json!(null), "null payload should fail", false)]
#[case::array_payload(json!([1, 2, 3]), "array payload should fail", false)]
#[case::empty_object(json!({}), "empty object should pass basic validation", true)]
#[case::valid_object(json!({"data": "valid", "size": 100}), "valid object should pass", true)]
#[sinex_test]
#[traced_test]
async fn test_json_payload_validation(
    ctx: TestContext,
    #[case] payload: serde_json::Value,
    #[case] description: &str,
    #[case] should_pass: bool,
) -> color_eyre::eyre::Result<()> {
    let pool = ctx.pool().clone();
    let validator = EventValidator::load_from_db(&pool).await?;

    let event = EventBuilder::generic("test.validation", "json_test")
        .payload(payload.clone())
        .build();

    let result = validator.validate(&event);

    // Log the validation result for analysis
    tracing::info!("Testing {}: result={:?}", description, result.is_ok());

    // Check that the result matches expectation
    match (result.is_ok(), should_pass) {
        (true, true) => tracing::debug!("Validation passed as expected: {}", description),
        (false, false) => tracing::debug!("Validation failed as expected: {}", description),
        (true, false) => {
            tracing::warn!("Unexpected validation pass: {}", description);
            // Some edge cases might pass - log for investigation
        }
        (false, true) => {
            let error = result.unwrap_err();
            panic!("Expected validation to pass for {}, but got error: {}", description, error);
        }
    }

    // Create snapshot of validation results
    ctx.snapshot_json(&format!("payload_validation_{}", description.replace(' ', "_").replace('.', "_")), &serde_json::json!({
        "description": description,
        "payload": payload,
        "should_pass": should_pass,
        "actual_passed": result.is_ok(),
        "error_info": result.err().map(|e| e.to_string())
    }));

    Ok(())
}

/// Test security validation against various injection attack patterns
#[rstest]
#[case::sql_injection(
    json!({"path": "/test'; DROP TABLE core.events; --", "size": 1024}),
    "sql_injection",
    "Should detect SQL injection attempts"
)]
#[case::xss_injection(
    json!({"path": "/test/<script>alert('xss')</script>", "size": 1024}),
    "xss_injection",
    "Should detect XSS injection attempts"
)]
#[case::path_traversal(
    json!({"path": "../../../etc/passwd", "size": 1024}),
    "path_traversal",
    "Should detect path traversal attempts"
)]
#[case::null_byte_injection(
    json!({"path": "/test/file\u{0000}.txt", "size": 1024}),
    "null_byte_injection",
    "Should detect null byte injection"
)]
#[case::control_char_injection(
    json!({"path": "/test/file\x01\x02\x03.txt", "size": 1024}),
    "control_char_injection",
    "Should detect control character injection"
)]
#[case::unicode_attack(
    json!({"path": "/test/\u{202e}\u{0301}file.txt", "size": 1024}),
    "unicode_attack",
    "Should detect Unicode normalization attacks"
)]
#[sinex_test]
#[traced_test]
async fn test_security_validation_injection_attacks(
    ctx: TestContext,
    #[case] malicious_payload: serde_json::Value,
    #[case] attack_type: &str,
    #[case] description: &str,
) -> color_eyre::eyre::Result<()> {
    let pool = ctx.pool().clone();
    let validator = EventValidator::load_from_db(&pool).await?;

    let event = EventBuilder::generic("filesystem", "file.created")
        .payload(malicious_payload.clone())
        .build();

    let result = validator.validate(&event);

    // Log the attack test result
    tracing::info!("Testing {} attack: {}", attack_type, description);

    match result {
        Err(ValidationError::SecurityValidation(msg)) => {
            tracing::info!("Security validation caught {} attack: {}", attack_type, msg);
        }
        Err(other_error) => {
            tracing::info!("Other validation error for {} attack: {}", attack_type, other_error);
        }
        Ok(_) => {
            tracing::warn!(
                "{} attack passed basic validation (may be caught by deeper checks)",
                attack_type
            );
        }
    }

    // Create snapshot of security validation results
    ctx.snapshot_json(&format!("security_validation_{}", attack_type), &serde_json::json!({
        "attack_type": attack_type,
        "description": description,
        "payload": malicious_payload,
        "validation_passed": result.is_ok(),
        "error_type": result.err().map(|e| format!("{:?}", e)),
        "error_message": result.err().map(|e| e.to_string())
    }));

    // The key validation is that the system should not crash or hang
    // Whether the attack is caught depends on the specific security rules
    Ok(())
}

#[sinex_test]
async fn test_schema_validation_performance_under_load(ctx: TestContext) -> color_eyre::eyre::Result<()> {
    let pool = ctx.pool().clone();
    let validator = EventValidator::load_from_db(&pool).await?;

    // Generate a large number of events to test performance
    let num_events = 1000;
    let mut events = Vec::new();

    for i in 0..num_events {
        let event = EventBuilder::filesystem()
            .path(&format!("/test/performance/file_{}.txt", i))
            .created()
            .size(1024)
            .permissions(0o644)
            .build();
        events.push(event);
    }

    // Measure validation performance
    let start_time = std::time::Instant::now();
    let mut validation_results = Vec::new();

    for event in &events {
        let result = validator.validate(event);
        validation_results.push(result.is_ok());
    }

    let elapsed = start_time.elapsed();
    let events_per_second = num_events as f64 / elapsed.as_secs_f64();

    println!(
        "Validated {} events in {:?} ({:.2} events/sec)",
        num_events, elapsed, events_per_second
    );

    // Verify all valid events passed
    let passed_count = validation_results.iter().filter(|&&passed| passed).count();
    assert_eq!(
        passed_count, num_events,
        "All valid events should pass validation"
    );

    // Performance should be reasonable (adjust threshold as needed)
    assert!(
        events_per_second > 100.0,
        "Validation performance too slow: {:.2} events/sec",
        events_per_second
    );

    Ok(())
}

#[sinex_test]
async fn test_comprehensive_integrity_validation(ctx: TestContext) -> color_eyre::eyre::Result<()> {
    let pool = ctx.pool().clone();

    // Insert some test events with known issues
    let valid_event = EventFactory::new("test.comprehensive")
        .create_event("valid_event", json!({"data": "valid"}));
    let _valid_event = sinex_db::insert_event_with_validator(&pool, &valid_event, None).await?;

    // Create integrity tester
    let integrity_tester = IntegrityTester::new(&pool).await?;

    // Run comprehensive integrity tests
    let config = IntegrityTestConfig {
        max_events_to_check: 1000,
        check_window_hours: 1,
        include_deep_validation: true,
        validate_checkpoints: true,
        validate_ulid_ordering: true,
        validate_schemas: true,
    };

    let results = integrity_tester.run_integrity_tests(config).await?;

    println!("Integrity test results:");
    println!("  Severity: {:?}", results.check_report.severity);
    println!(
        "  Events checked: {}",
        results.check_report.total_events_checked
    );
    println!(
        "  Schema violations: {}",
        results.check_report.schema_violations.len()
    );
    println!(
        "  ULID violations: {}",
        results.check_report.ulid_ordering_violations.len()
    );
    println!(
        "  Checkpoint issues: {}",
        results.check_report.checkpoint_inconsistencies.len()
    );
    println!(
        "  Corruption indicators: {}",
        results.check_report.data_corruption_indicators.len()
    );
    println!("  Recommendations: {}", results.recommendations.len());
    println!("  Test duration: {:?}", results.test_metadata.test_duration);

    // For a clean test environment, we should have minimal issues
    assert!(
        results.check_report.total_events_checked > 0,
        "Should have checked some events"
    );

    // Print any recommendations for debugging
    for rec in &results.recommendations {
        println!("Recommendation [{:?}]: {}", rec.priority, rec.description);
        for step in &rec.action_steps {
            println!("  - {}", step);
        }
    }

    Ok(())
}

/// Test malformed event anomaly detection with various problematic patterns
#[rstest]
#[case::empty_source(
    "", "empty.source", json!({"data": "test"}),
    "empty_source", true, "Should detect empty source field"
)]
#[case::null_bytes(
    "test\0source", "null.byte", json!({"data": "test"}),
    "null_bytes", true, "Should detect null bytes in source"
)]
#[case::oversized_payload(
    "test.source", "oversized", json!({"large_field": "x".repeat(500)}),
    "oversized_payload", true, "Should detect oversized payload"
)]
#[case::valid_event(
    "test.source", "valid", json!({"data": "valid"}),
    "valid_event", false, "Valid event should have no anomalies"
)]
#[sinex_test]
#[traced_test]
async fn test_malformed_event_anomaly_detection(
    ctx: TestContext,
    #[case] source: &str,
    #[case] event_type: &str,
    #[case] payload: serde_json::Value,
    #[case] anomaly_category: &str,
    #[case] should_have_anomalies: bool,
    #[case] description: &str,
) -> color_eyre::eyre::Result<()> {
    let _pool = ctx.pool().clone();

    let event = EventBuilder::generic(source, event_type)
        .payload(payload.clone())
        .build();

    let anomalies = malformed_detection::detect_schema_anomalies(&event);

    tracing::info!(
        "Testing {}: detected {} anomalies",
        description,
        anomalies.len()
    );

    for anomaly in &anomalies {
        tracing::debug!("  Detected anomaly: {}", anomaly);
    }

    // Verify anomaly detection matches expectation
    if should_have_anomalies {
        assert!(
            !anomalies.is_empty(),
            "Expected anomalies for {}, but none detected",
            description
        );

        // Verify specific anomaly types
        match anomaly_category {
            "empty_source" => assert!(
                anomalies.iter().any(|a| a.contains("empty") || a.contains("source")),
                "Should detect empty source anomaly"
            ),
            "null_bytes" => assert!(
                anomalies.iter().any(|a| a.contains("null") || a.contains("byte")),
                "Should detect null byte anomaly"
            ),
            "oversized_payload" => assert!(
                anomalies.iter().any(|a| a.contains("oversized") || a.contains("large")),
                "Should detect oversized payload anomaly"
            ),
            _ => {} // Other categories may have different detection patterns
        }
    } else {
        assert!(
            anomalies.is_empty(),
            "Expected no anomalies for {}, but detected: {:?}",
            description,
            anomalies
        );
    }

    // Create snapshot of anomaly detection results
    ctx.snapshot_json(&format!("anomaly_detection_{}", anomaly_category), &serde_json::json!({
        "source": source,
        "event_type": event_type,
        "payload": payload,
        "anomaly_category": anomaly_category,
        "description": description,
        "should_have_anomalies": should_have_anomalies,
        "detected_anomalies": anomalies,
        "anomaly_count": anomalies.len()
    }));

    Ok(())
}

// Helper function to create deeply nested JSON for testing
fn create_deeply_nested_json(depth: usize) -> Value {
    if depth == 0 {
        json!("leaf")
    } else {
        json!({
            "level": depth,
            "nested": create_deeply_nested_json(depth - 1)
        })
    }
}

// Test schema validation with various event types
#[sinex_test]
async fn test_event_type_specific_validation(ctx: TestContext) -> color_eyre::eyre::Result<()> {
    let pool = ctx.pool().clone();
    let validator = EventValidator::load_from_db(&pool).await?;

    // Test filesystem events
    let filesystem_tests = vec![
        // Valid filesystem event
        (
            EventBuilder::filesystem()
                .path("/test/valid.txt")
                .created()
                .size(1024)
                .build(),
            true,
        ),
        // Invalid filesystem event - missing path
        (
            EventBuilder::generic("filesystem", "file.created")
                .payload(json!({"size": 1024}))
                .build(),
            false,
        ),
        // Invalid filesystem event - invalid size type
        (
            EventBuilder::generic("filesystem", "file.created")
                .payload(json!({"path": "/test.txt", "size": "not_a_number"}))
                .build(),
            false,
        ),
    ];

    for (event, should_pass) in filesystem_tests {
        let result = validator.validate(&event);
        if should_pass {
            assert!(
                result.is_ok(),
                "Valid filesystem event should pass: {:?}",
                result
            );
        } else {
            assert!(result.is_err(), "Invalid filesystem event should fail");
        }
    }

    // Test terminal events
    let terminal_tests = vec![
        // Valid terminal event
        (
            EventBuilder::terminal()
                .command("echo test")
                .success()
                .build(),
            true,
        ),
        // Invalid terminal event - missing command
        (
            EventBuilder::generic("terminal.kitty", "command.executed")
                .payload(json!({"exit_code": 0}))
                .build(),
            false,
        ),
    ];

    for (event, should_pass) in terminal_tests {
        let result = validator.validate(&event);
        if should_pass {
            assert!(
                result.is_ok(),
                "Valid terminal event should pass: {:?}",
                result
            );
        } else {
            assert!(result.is_err(), "Invalid terminal event should fail");
        }
    }

    Ok(())
}
